// flow-typed signature: 71fdcb0a7ab0ca9303129dd11c0f8f04
// flow-typed version: <<STUB>>/@turf/turf_v^5.1.6/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/turf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/turf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/turf/turf.es' {
  declare module.exports: any;
}

declare module '@turf/turf/turf' {
  declare module.exports: any;
}

declare module '@turf/turf/turf.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/turf/index' {
  declare module.exports: $Exports<'@turf/turf'>;
}
declare module '@turf/turf/index.js' {
  declare module.exports: $Exports<'@turf/turf'>;
}
declare module '@turf/turf/turf.es.js' {
  declare module.exports: $Exports<'@turf/turf/turf.es'>;
}
declare module '@turf/turf/turf.js' {
  declare module.exports: $Exports<'@turf/turf/turf'>;
}
declare module '@turf/turf/turf.min.js' {
  declare module.exports: $Exports<'@turf/turf/turf.min'>;
}
