// flow-typed signature: 474725c0385eedb10cd9d7fb41454e9e
// flow-typed version: <<STUB>>/@pixi/filter-outline_v^3.1.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@pixi/filter-outline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@pixi/filter-outline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@pixi/filter-outline/dist/filter-outline' {
  declare module.exports: any;
}

declare module '@pixi/filter-outline/lib/filter-outline.cjs' {
  declare module.exports: any;
}

declare module '@pixi/filter-outline/lib/filter-outline.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@pixi/filter-outline/dist/filter-outline.js' {
  declare module.exports: $Exports<'@pixi/filter-outline/dist/filter-outline'>;
}
declare module '@pixi/filter-outline/lib/filter-outline.cjs.js' {
  declare module.exports: $Exports<'@pixi/filter-outline/lib/filter-outline.cjs'>;
}
declare module '@pixi/filter-outline/lib/filter-outline.esm.js' {
  declare module.exports: $Exports<'@pixi/filter-outline/lib/filter-outline.esm'>;
}
