// flow-typed signature: 0060a9c4c3f8ad47c6a60500026ab669
// flow-typed version: <<STUB>>/@cypress/code-coverage_v^3.8.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cypress/code-coverage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@cypress/code-coverage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@cypress/code-coverage/common-utils' {
  declare module.exports: any;
}

declare module '@cypress/code-coverage/middleware/express' {
  declare module.exports: any;
}

declare module '@cypress/code-coverage/middleware/hapi' {
  declare module.exports: any;
}

declare module '@cypress/code-coverage/middleware/nextjs' {
  declare module.exports: any;
}

declare module '@cypress/code-coverage/plugins' {
  declare module.exports: any;
}

declare module '@cypress/code-coverage/support-utils' {
  declare module.exports: any;
}

declare module '@cypress/code-coverage/support' {
  declare module.exports: any;
}

declare module '@cypress/code-coverage/task-utils' {
  declare module.exports: any;
}

declare module '@cypress/code-coverage/task' {
  declare module.exports: any;
}

declare module '@cypress/code-coverage/use-babelrc' {
  declare module.exports: any;
}

declare module '@cypress/code-coverage/use-browserify-istanbul' {
  declare module.exports: any;
}

// Filename aliases
declare module '@cypress/code-coverage/common-utils.js' {
  declare module.exports: $Exports<'@cypress/code-coverage/common-utils'>;
}
declare module '@cypress/code-coverage/middleware/express.js' {
  declare module.exports: $Exports<'@cypress/code-coverage/middleware/express'>;
}
declare module '@cypress/code-coverage/middleware/hapi.js' {
  declare module.exports: $Exports<'@cypress/code-coverage/middleware/hapi'>;
}
declare module '@cypress/code-coverage/middleware/nextjs.js' {
  declare module.exports: $Exports<'@cypress/code-coverage/middleware/nextjs'>;
}
declare module '@cypress/code-coverage/plugins.js' {
  declare module.exports: $Exports<'@cypress/code-coverage/plugins'>;
}
declare module '@cypress/code-coverage/support-utils.js' {
  declare module.exports: $Exports<'@cypress/code-coverage/support-utils'>;
}
declare module '@cypress/code-coverage/support.js' {
  declare module.exports: $Exports<'@cypress/code-coverage/support'>;
}
declare module '@cypress/code-coverage/task-utils.js' {
  declare module.exports: $Exports<'@cypress/code-coverage/task-utils'>;
}
declare module '@cypress/code-coverage/task.js' {
  declare module.exports: $Exports<'@cypress/code-coverage/task'>;
}
declare module '@cypress/code-coverage/use-babelrc.js' {
  declare module.exports: $Exports<'@cypress/code-coverage/use-babelrc'>;
}
declare module '@cypress/code-coverage/use-browserify-istanbul.js' {
  declare module.exports: $Exports<'@cypress/code-coverage/use-browserify-istanbul'>;
}
