// flow-typed signature: 5923215abfc5a04b6f1ab03eca6c41e0
// flow-typed version: <<STUB>>/@cypress/webpack-preprocessor_v^5.4.2/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cypress/webpack-preprocessor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@cypress/webpack-preprocessor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@cypress/webpack-preprocessor/dist/deferred' {
  declare module.exports: any;
}

declare module '@cypress/webpack-preprocessor/dist' {
  declare module.exports: any;
}

declare module '@cypress/webpack-preprocessor/dist/lib/typescript-overrides' {
  declare module.exports: any;
}

// Filename aliases
declare module '@cypress/webpack-preprocessor/dist/deferred.js' {
  declare module.exports: $Exports<'@cypress/webpack-preprocessor/dist/deferred'>;
}
declare module '@cypress/webpack-preprocessor/dist/index' {
  declare module.exports: $Exports<'@cypress/webpack-preprocessor/dist'>;
}
declare module '@cypress/webpack-preprocessor/dist/index.js' {
  declare module.exports: $Exports<'@cypress/webpack-preprocessor/dist'>;
}
declare module '@cypress/webpack-preprocessor/dist/lib/typescript-overrides.js' {
  declare module.exports: $Exports<'@cypress/webpack-preprocessor/dist/lib/typescript-overrides'>;
}
