// flow-typed signature: 88a7e004dad0f95b883e0a7cec99db76
// flow-typed version: <<STUB>>/@fortawesome/vue-fontawesome_v^0.1.10/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/vue-fontawesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/vue-fontawesome' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/build' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/check-versions' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/utils' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/vue-loader.conf' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/webpack.base.conf' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/webpack.dev.conf' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/webpack.prod.conf' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/config/dev.env' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/config' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/config/prod.env' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/src/main' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/index.es' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/rollup.config' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/src/components/__fixtures__/helpers' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/src/components/__fixtures__/icons' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/src/components/__tests__/FontAwesomeIcon.test' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/src/components/__tests__/FontAwesomeLayers.test' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/src/components/__tests__/FontAwesomeLayersText.test' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/src/components/FontAwesomeIcon' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/src/components/FontAwesomeLayers' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/src/components/FontAwesomeLayersText' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/src/converter' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/src' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/src/logger' {
  declare module.exports: any;
}

declare module '@fortawesome/vue-fontawesome/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/build.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/build'>;
}
declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/check-versions.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/check-versions'>;
}
declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/utils.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/utils'>;
}
declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/vue-loader.conf.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/vue-loader.conf'>;
}
declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/webpack.base.conf.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/webpack.base.conf'>;
}
declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/webpack.dev.conf.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/webpack.dev.conf'>;
}
declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/webpack.prod.conf.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/examples/vue-cli-webpack/build/webpack.prod.conf'>;
}
declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/config/dev.env.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/examples/vue-cli-webpack/config/dev.env'>;
}
declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/config/index' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/examples/vue-cli-webpack/config'>;
}
declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/config/index.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/examples/vue-cli-webpack/config'>;
}
declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/config/prod.env.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/examples/vue-cli-webpack/config/prod.env'>;
}
declare module '@fortawesome/vue-fontawesome/examples/vue-cli-webpack/src/main.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/examples/vue-cli-webpack/src/main'>;
}
declare module '@fortawesome/vue-fontawesome/index.es.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/index.es'>;
}
declare module '@fortawesome/vue-fontawesome/index' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome'>;
}
declare module '@fortawesome/vue-fontawesome/index.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome'>;
}
declare module '@fortawesome/vue-fontawesome/rollup.config.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/rollup.config'>;
}
declare module '@fortawesome/vue-fontawesome/src/components/__fixtures__/helpers.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/src/components/__fixtures__/helpers'>;
}
declare module '@fortawesome/vue-fontawesome/src/components/__fixtures__/icons.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/src/components/__fixtures__/icons'>;
}
declare module '@fortawesome/vue-fontawesome/src/components/__tests__/FontAwesomeIcon.test.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/src/components/__tests__/FontAwesomeIcon.test'>;
}
declare module '@fortawesome/vue-fontawesome/src/components/__tests__/FontAwesomeLayers.test.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/src/components/__tests__/FontAwesomeLayers.test'>;
}
declare module '@fortawesome/vue-fontawesome/src/components/__tests__/FontAwesomeLayersText.test.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/src/components/__tests__/FontAwesomeLayersText.test'>;
}
declare module '@fortawesome/vue-fontawesome/src/components/FontAwesomeIcon.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/src/components/FontAwesomeIcon'>;
}
declare module '@fortawesome/vue-fontawesome/src/components/FontAwesomeLayers.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/src/components/FontAwesomeLayers'>;
}
declare module '@fortawesome/vue-fontawesome/src/components/FontAwesomeLayersText.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/src/components/FontAwesomeLayersText'>;
}
declare module '@fortawesome/vue-fontawesome/src/converter.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/src/converter'>;
}
declare module '@fortawesome/vue-fontawesome/src/index' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/src'>;
}
declare module '@fortawesome/vue-fontawesome/src/index.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/src'>;
}
declare module '@fortawesome/vue-fontawesome/src/logger.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/src/logger'>;
}
declare module '@fortawesome/vue-fontawesome/src/utils.js' {
  declare module.exports: $Exports<'@fortawesome/vue-fontawesome/src/utils'>;
}
