# Patterns to exclude from all Restylers
exclude:
  - "**/node_modules/**/*"
  - "**/vendor/**/*"
  - ".github/workflows/**/*" # https://github.com/restyled-io/restyler/issues/73
  - "**/**/*.svg" # allow imgbot to optimize

# Leave comments on the original PR linking to the Restyle PR?
comments: true
