FROM node:16-alpine as build

WORKDIR /tmp
RUN apk add gpg gpg-agent git && \
  wget -qO - https://keybase.io/pnpm/pgp_keys.asc | gpg --import && \
  wget -q https://get.pnpm.io/SHASUMS256.txt && \
  wget -q https://get.pnpm.io/SHASUMS256.txt.sig && \
  gpg --verify SHASUMS256.txt.sig SHASUMS256.txt && \
  wget https://get.pnpm.io/v6.16.js && \
  grep v6.16.js SHASUMS256.txt | sha256sum -c - && \
  cat v6.16.js | node - add --global pnpm && \
  rm SHASUMS256.txt v6.16.js

WORKDIR /app
COPY pnpm-lock.yaml package.json ./
RUN pnpm fetch --dev
RUN pnpm install

COPY . .

# CI/General
ARG CI
ENV CI=${CI:-1}
ENV CYPRESS_INSTALL_BINARY 0
# Stage Specific Args
ARG VITE_APP_API_BASE_URL
ARG VITE_APP_BASE_URL
ARG VITE_APP_WS_URL
ARG VITE_APP_STAGE
ARG VITE_APP_AWS_CCP_URL
ARG VITE_APP_CCP_INSTANCE
ARG VITE_APP_PORTAL_KEY
ARG NODE_ENV
# Stage Env
ENV VITE_APP_API_BASE_URL=${VITE_APP_API_BASE_URL}
ENV VITE_APP_BASE_URL=${VITE_APP_BASE_URL}
ENV VITE_APP_WS_URL=${VITE_APP_WS_URL}
ENV VITE_APP_STAGE=${VITE_APP_STAGE}
ENV VITE_APP_AWS_CCP_URL=${VITE_APP_AWS_CCP_URL}
ENV VITE_APP_CCP_INSTANCE=${VITE_APP_CCP_INSTANCE}
ENV VITE_APP_PORTAL_KEY=${VITE_APP_PORTAL_KEY:-crisiscleanup_us}
ENV NODE_ENV=${NODE_ENV:-production}
# Secrets Args
ARG VITE_APP_WHAT_3_WORDS_API_KEY
ARG VITE_APP_GOOGLE_MAPS_API_KEY
ARG VITE_APP_PITNEYBOWES_API_KEY
ARG VITE_APP_PITNEYBOWES_BASIC_AUTH_TOKEN
ARG VITE_APP_PHONE_DEFAULT_USERNAME
ARG VITE_APP_PHONE_DEFAULT_PASSWORD
ARG VITE_APP_ENGLISH_PHONE_GATEWAY
ARG VITE_APP_SPANISH_PHONE_GATEWAY
ARG VITE_APP_DEFAULT_CALLER_ID
ARG SENTRY_DSN
ARG SENTRY_AUTH_TOKEN
ARG SENTRY_PROPERTIES
# Secrets env
ENV VITE_APP_WHAT_3_WORDS_API_KEY=${VITE_APP_WHAT_3_WORDS_API_KEY}
ENV VITE_APP_GOOGLE_MAPS_API_KEY=${VITE_APP_GOOGLE_MAPS_API_KEY}
ENV VITE_APP_PITNEYBOWES_API_KEY=${VITE_APP_PITNEYBOWES_API_KEY}
ENV VITE_APP_PITNEYBOWES_BASIC_AUTH_TOKEN=${VITE_APP_PITNEYBOWES_BASIC_AUTH_TOKEN}
ENV VITE_APP_DEFAULT_CALLER_ID=${VITE_APP_DEFAULT_CALLER_ID}
ENV VITE_APP_PHONE_DEFAULT_USERNAME=${VITE_APP_PHONE_DEFAULT_USERNAME}
ENV VITE_APP_PHONE_DEFAULT_PASSWORD=${VITE_APP_PHONE_DEFAULT_PASSWORD}
ENV VITE_APP_ENGLISH_PHONE_GATEWAY=${VITE_APP_ENGLISH_PHONE_GATEWAY}
ENV VITE_APP_SPANISH_PHONE_GATEWAY=${VITE_APP_SPANISH_PHONE_GATEWAY}
ENV SENTRY_DSN=${SENTRY_DSN}
ENV SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
ENV SENTRY_PROPERTIES=${SENTRY_PROPERTIES:-"sentry.properties"}

#ENV NODE_OPTIONS='--max_old_space_size=4096'

RUN pnpm build:app --mode=${VITE_APP_STAGE}

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
