import Affiliate from '@/models/Affiliate';
import Agent from '@/models/Agent';
import Incident from '@/models/Incident';
import Invitation from '@/models/Invitation';
import InvitationRequest from '@/models/InvitationRequest';
import Language from '@/models/Language';
import Layer from '@/models/Layer';
import Location from '@/models/Location';
import LocationType from '@/models/LocationType';
import Organization from '@/models/Organization';
import Pda from '@/models/Pda';
import PhoneDnis from '@/models/PhoneDnis';
import PhoneOutbound from '@/models/PhoneOutbound';
import PhoneInbound from '@/models/PhoneInbound';
import PhoneResource from '@/models/PhoneResource';
import PhoneStatus from '@/models/PhoneStatus';
import Role from '@/models/Role';
import User from '@/models/User';
import UserRole from '@/models/UserRole';
import Worksite from '@/models/Worksite';
import WorksiteRequest from '@/models/WorksiteRequest';
import { Database } from '@vuex-orm/core';

const database = new Database();

database.register(User, {});
database.register(Worksite, {});
database.register(Incident, {});
database.register(Organization, {});
database.register(InvitationRequest, {});
database.register(Invitation, {});
database.register(Location, {});
database.register(Layer, {});
database.register(WorksiteRequest, {});
database.register(LocationType, {});
database.register(Affiliate, {});
database.register(Language, {});
database.register(Role, {});
database.register(Agent, {});
database.register(UserRole, {});
database.register(Pda, {});
database.register(PhoneStatus, {});
database.register(PhoneOutbound, {});
database.register(PhoneInbound, {});
database.register(PhoneResource, {});
database.register(PhoneDnis, {});

export default database;
