// flow-typed signature: b3ba55ccc8a074664ed7bab715fc0165
// flow-typed version: <<STUB>>/@geoman-io/leaflet-geoman-free_v^2.6.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@geoman-io/leaflet-geoman-free'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@geoman-io/leaflet-geoman-free' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.min' {
  declare module.exports: any;
}

declare module '@geoman-io/leaflet-geoman-free/dist/leaflet.pm.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.min.js' {
  declare module.exports: $Exports<'@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.min'>;
}
declare module '@geoman-io/leaflet-geoman-free/dist/leaflet.pm.min.js' {
  declare module.exports: $Exports<'@geoman-io/leaflet-geoman-free/dist/leaflet.pm.min'>;
}
