// flow-typed signature: 9c64caa4e9bdcf1cadf2c2cc5c40836f
// flow-typed version: <<STUB>>/babel-preset-vue_v^2.0.2/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-vue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-vue/dist/babel-preset-vue.cjs' {
  declare module.exports: any;
}

declare module 'babel-preset-vue/dist/babel-preset-vue' {
  declare module.exports: any;
}

declare module 'babel-preset-vue/dist/babel-preset-vue.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-vue/dist/babel-preset-vue.cjs.js' {
  declare module.exports: $Exports<'babel-preset-vue/dist/babel-preset-vue.cjs'>;
}
declare module 'babel-preset-vue/dist/babel-preset-vue.js' {
  declare module.exports: $Exports<'babel-preset-vue/dist/babel-preset-vue'>;
}
declare module 'babel-preset-vue/dist/babel-preset-vue.min.js' {
  declare module.exports: $Exports<'babel-preset-vue/dist/babel-preset-vue.min'>;
}
