// flow-typed signature: 02146ee6bb72f51dc276f48d8073a875
// flow-typed version: <<STUB>>/bp-vuejs-dropdown_v^2.1.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bp-vuejs-dropdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bp-vuejs-dropdown' {
  declare module.exports: any;
}
