// flow-typed signature: 50437de7e03ba5b11fe25fe2edd6be4b
// flow-typed version: <<STUB>>/cf-agent-library_vgit+https://git@github.com/CrisisCleanup/cf-agent-library.git/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cf-agent-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cf-agent-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cf-agent-library/cf-agent-library' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cf-agent-library/cf-agent-library.js' {
  declare module.exports: $Exports<'cf-agent-library/cf-agent-library'>;
}
