// flow-typed signature: 33cf791d1029c888dc02b32f82c7c6fa
// flow-typed version: <<STUB>>/circle-to-polygon_v^2.0.2/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'circle-to-polygon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'circle-to-polygon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'circle-to-polygon/index.input-validation.specs' {
  declare module.exports: any;
}

declare module 'circle-to-polygon/index.output-validation.specs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'circle-to-polygon/index.input-validation.specs.js' {
  declare module.exports: $Exports<'circle-to-polygon/index.input-validation.specs'>;
}
declare module 'circle-to-polygon/index' {
  declare module.exports: $Exports<'circle-to-polygon'>;
}
declare module 'circle-to-polygon/index.js' {
  declare module.exports: $Exports<'circle-to-polygon'>;
}
declare module 'circle-to-polygon/index.output-validation.specs.js' {
  declare module.exports: $Exports<'circle-to-polygon/index.output-validation.specs'>;
}
