// flow-typed signature: f7c0dda74806f269ac59235fa54152c2
// flow-typed version: <<STUB>>/cypress-wait-until_v^1.6.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cypress-wait-until'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cypress-wait-until' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cypress-wait-until/cypress-run' {
  declare module.exports: any;
}

declare module 'cypress-wait-until/cypress/integration/plugin.spec' {
  declare module.exports: any;
}

declare module 'cypress-wait-until/cypress/plugins' {
  declare module.exports: any;
}

declare module 'cypress-wait-until/cypress/support/commands' {
  declare module.exports: any;
}

declare module 'cypress-wait-until/cypress/support' {
  declare module.exports: any;
}

declare module 'cypress-wait-until/cypress/types/plugin.spec' {
  declare module.exports: any;
}

declare module 'cypress-wait-until/release.config' {
  declare module.exports: any;
}

declare module 'cypress-wait-until/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cypress-wait-until/cypress-run.js' {
  declare module.exports: $Exports<'cypress-wait-until/cypress-run'>;
}
declare module 'cypress-wait-until/cypress/integration/plugin.spec.js' {
  declare module.exports: $Exports<'cypress-wait-until/cypress/integration/plugin.spec'>;
}
declare module 'cypress-wait-until/cypress/plugins/index' {
  declare module.exports: $Exports<'cypress-wait-until/cypress/plugins'>;
}
declare module 'cypress-wait-until/cypress/plugins/index.js' {
  declare module.exports: $Exports<'cypress-wait-until/cypress/plugins'>;
}
declare module 'cypress-wait-until/cypress/support/commands.js' {
  declare module.exports: $Exports<'cypress-wait-until/cypress/support/commands'>;
}
declare module 'cypress-wait-until/cypress/support/index' {
  declare module.exports: $Exports<'cypress-wait-until/cypress/support'>;
}
declare module 'cypress-wait-until/cypress/support/index.js' {
  declare module.exports: $Exports<'cypress-wait-until/cypress/support'>;
}
declare module 'cypress-wait-until/cypress/types/plugin.spec.js' {
  declare module.exports: $Exports<'cypress-wait-until/cypress/types/plugin.spec'>;
}
declare module 'cypress-wait-until/release.config.js' {
  declare module.exports: $Exports<'cypress-wait-until/release.config'>;
}
declare module 'cypress-wait-until/src/index' {
  declare module.exports: $Exports<'cypress-wait-until/src'>;
}
declare module 'cypress-wait-until/src/index.js' {
  declare module.exports: $Exports<'cypress-wait-until/src'>;
}
