// flow-typed signature: 65a1a9b865bb4788cf6806c16f828e81
// flow-typed version: <<STUB>>/cypress-vue-unit-test_v^3.5.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cypress-vue-unit-test'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cypress-vue-unit-test' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cypress-vue-unit-test/dist' {
  declare module.exports: any;
}

declare module 'cypress-vue-unit-test/dist/plugins/webpack' {
  declare module.exports: any;
}

declare module 'cypress-vue-unit-test/dist/preprocessor' {
  declare module.exports: any;
}

declare module 'cypress-vue-unit-test/dist/preprocessor/webpack' {
  declare module.exports: any;
}

declare module 'cypress-vue-unit-test/dist/support' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cypress-vue-unit-test/dist/index' {
  declare module.exports: $Exports<'cypress-vue-unit-test/dist'>;
}
declare module 'cypress-vue-unit-test/dist/index.js' {
  declare module.exports: $Exports<'cypress-vue-unit-test/dist'>;
}
declare module 'cypress-vue-unit-test/dist/plugins/webpack/index' {
  declare module.exports: $Exports<'cypress-vue-unit-test/dist/plugins/webpack'>;
}
declare module 'cypress-vue-unit-test/dist/plugins/webpack/index.js' {
  declare module.exports: $Exports<'cypress-vue-unit-test/dist/plugins/webpack'>;
}
declare module 'cypress-vue-unit-test/dist/preprocessor/index' {
  declare module.exports: $Exports<'cypress-vue-unit-test/dist/preprocessor'>;
}
declare module 'cypress-vue-unit-test/dist/preprocessor/index.js' {
  declare module.exports: $Exports<'cypress-vue-unit-test/dist/preprocessor'>;
}
declare module 'cypress-vue-unit-test/dist/preprocessor/webpack.js' {
  declare module.exports: $Exports<'cypress-vue-unit-test/dist/preprocessor/webpack'>;
}
declare module 'cypress-vue-unit-test/dist/support.js' {
  declare module.exports: $Exports<'cypress-vue-unit-test/dist/support'>;
}
