// flow-typed signature: 5f52ada071a22584db67035bc954871e
// flow-typed version: <<STUB>>/cypress-vue-unit-test_v^1.11.7/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cypress-vue-unit-test'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cypress-vue-unit-test' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cypress-vue-unit-test/preprocessor/webpack' {
  declare module.exports: any;
}

declare module 'cypress-vue-unit-test/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cypress-vue-unit-test/preprocessor/webpack.js' {
  declare module.exports: $Exports<'cypress-vue-unit-test/preprocessor/webpack'>;
}
declare module 'cypress-vue-unit-test/src/index' {
  declare module.exports: $Exports<'cypress-vue-unit-test/src'>;
}
declare module 'cypress-vue-unit-test/src/index.js' {
  declare module.exports: $Exports<'cypress-vue-unit-test/src'>;
}
