// flow-typed signature: f9494e24fb349bec1f123d5d9c6d4aa9
// flow-typed version: <<STUB>>/cypress-cy-select_v^0.2.2/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cypress-cy-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cypress-cy-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cypress-cy-select/dist/commands' {
  declare module.exports: any;
}

declare module 'cypress-cy-select/dist/commands.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cypress-cy-select/dist/commands.js' {
  declare module.exports: $Exports<'cypress-cy-select/dist/commands'>;
}
declare module 'cypress-cy-select/dist/commands.min.js' {
  declare module.exports: $Exports<'cypress-cy-select/dist/commands.min'>;
}
