// flow-typed signature: 71b76704f2d519fd482f932ba4a3b897
// flow-typed version: <<STUB>>/cypress-localstorage-commands_v^1.1.7/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cypress-localstorage-commands'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cypress-localstorage-commands' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cypress-localstorage-commands/src/LocalStorage' {
  declare module.exports: any;
}

declare module 'cypress-localstorage-commands/src/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cypress-localstorage-commands/index' {
  declare module.exports: $Exports<'cypress-localstorage-commands'>;
}
declare module 'cypress-localstorage-commands/index.js' {
  declare module.exports: $Exports<'cypress-localstorage-commands'>;
}
declare module 'cypress-localstorage-commands/src/LocalStorage.js' {
  declare module.exports: $Exports<'cypress-localstorage-commands/src/LocalStorage'>;
}
declare module 'cypress-localstorage-commands/src/register.js' {
  declare module.exports: $Exports<'cypress-localstorage-commands/src/register'>;
}
