// flow-typed signature: a78410957c8b3cf95c932a3a290f5020
// flow-typed version: <<STUB>>/d3-quadtree_v^1.0.7/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-quadtree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-quadtree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-quadtree/dist/d3-quadtree' {
  declare module.exports: any;
}

declare module 'd3-quadtree/dist/d3-quadtree.min' {
  declare module.exports: any;
}

declare module 'd3-quadtree/src/add' {
  declare module.exports: any;
}

declare module 'd3-quadtree/src/cover' {
  declare module.exports: any;
}

declare module 'd3-quadtree/src/data' {
  declare module.exports: any;
}

declare module 'd3-quadtree/src/extent' {
  declare module.exports: any;
}

declare module 'd3-quadtree/src/find' {
  declare module.exports: any;
}

declare module 'd3-quadtree/src' {
  declare module.exports: any;
}

declare module 'd3-quadtree/src/quad' {
  declare module.exports: any;
}

declare module 'd3-quadtree/src/quadtree' {
  declare module.exports: any;
}

declare module 'd3-quadtree/src/remove' {
  declare module.exports: any;
}

declare module 'd3-quadtree/src/root' {
  declare module.exports: any;
}

declare module 'd3-quadtree/src/size' {
  declare module.exports: any;
}

declare module 'd3-quadtree/src/visit' {
  declare module.exports: any;
}

declare module 'd3-quadtree/src/visitAfter' {
  declare module.exports: any;
}

declare module 'd3-quadtree/src/x' {
  declare module.exports: any;
}

declare module 'd3-quadtree/src/y' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-quadtree/dist/d3-quadtree.js' {
  declare module.exports: $Exports<'d3-quadtree/dist/d3-quadtree'>;
}
declare module 'd3-quadtree/dist/d3-quadtree.min.js' {
  declare module.exports: $Exports<'d3-quadtree/dist/d3-quadtree.min'>;
}
declare module 'd3-quadtree/src/add.js' {
  declare module.exports: $Exports<'d3-quadtree/src/add'>;
}
declare module 'd3-quadtree/src/cover.js' {
  declare module.exports: $Exports<'d3-quadtree/src/cover'>;
}
declare module 'd3-quadtree/src/data.js' {
  declare module.exports: $Exports<'d3-quadtree/src/data'>;
}
declare module 'd3-quadtree/src/extent.js' {
  declare module.exports: $Exports<'d3-quadtree/src/extent'>;
}
declare module 'd3-quadtree/src/find.js' {
  declare module.exports: $Exports<'d3-quadtree/src/find'>;
}
declare module 'd3-quadtree/src/index' {
  declare module.exports: $Exports<'d3-quadtree/src'>;
}
declare module 'd3-quadtree/src/index.js' {
  declare module.exports: $Exports<'d3-quadtree/src'>;
}
declare module 'd3-quadtree/src/quad.js' {
  declare module.exports: $Exports<'d3-quadtree/src/quad'>;
}
declare module 'd3-quadtree/src/quadtree.js' {
  declare module.exports: $Exports<'d3-quadtree/src/quadtree'>;
}
declare module 'd3-quadtree/src/remove.js' {
  declare module.exports: $Exports<'d3-quadtree/src/remove'>;
}
declare module 'd3-quadtree/src/root.js' {
  declare module.exports: $Exports<'d3-quadtree/src/root'>;
}
declare module 'd3-quadtree/src/size.js' {
  declare module.exports: $Exports<'d3-quadtree/src/size'>;
}
declare module 'd3-quadtree/src/visit.js' {
  declare module.exports: $Exports<'d3-quadtree/src/visit'>;
}
declare module 'd3-quadtree/src/visitAfter.js' {
  declare module.exports: $Exports<'d3-quadtree/src/visitAfter'>;
}
declare module 'd3-quadtree/src/x.js' {
  declare module.exports: $Exports<'d3-quadtree/src/x'>;
}
declare module 'd3-quadtree/src/y.js' {
  declare module.exports: $Exports<'d3-quadtree/src/y'>;
}
