// flow-typed signature: 86ea45444b6c1034bece1630c8b79bba
// flow-typed version: <<STUB>>/d3-scale_v^3.2.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-scale'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-scale' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-scale/dist/d3-scale' {
  declare module.exports: any;
}

declare module 'd3-scale/dist/d3-scale.min' {
  declare module.exports: any;
}

declare module 'd3-scale/src/band' {
  declare module.exports: any;
}

declare module 'd3-scale/src/colors' {
  declare module.exports: any;
}

declare module 'd3-scale/src/constant' {
  declare module.exports: any;
}

declare module 'd3-scale/src/continuous' {
  declare module.exports: any;
}

declare module 'd3-scale/src/diverging' {
  declare module.exports: any;
}

declare module 'd3-scale/src/identity' {
  declare module.exports: any;
}

declare module 'd3-scale/src' {
  declare module.exports: any;
}

declare module 'd3-scale/src/init' {
  declare module.exports: any;
}

declare module 'd3-scale/src/linear' {
  declare module.exports: any;
}

declare module 'd3-scale/src/log' {
  declare module.exports: any;
}

declare module 'd3-scale/src/nice' {
  declare module.exports: any;
}

declare module 'd3-scale/src/number' {
  declare module.exports: any;
}

declare module 'd3-scale/src/ordinal' {
  declare module.exports: any;
}

declare module 'd3-scale/src/pow' {
  declare module.exports: any;
}

declare module 'd3-scale/src/quantile' {
  declare module.exports: any;
}

declare module 'd3-scale/src/quantize' {
  declare module.exports: any;
}

declare module 'd3-scale/src/radial' {
  declare module.exports: any;
}

declare module 'd3-scale/src/sequential' {
  declare module.exports: any;
}

declare module 'd3-scale/src/sequentialQuantile' {
  declare module.exports: any;
}

declare module 'd3-scale/src/symlog' {
  declare module.exports: any;
}

declare module 'd3-scale/src/threshold' {
  declare module.exports: any;
}

declare module 'd3-scale/src/tickFormat' {
  declare module.exports: any;
}

declare module 'd3-scale/src/time' {
  declare module.exports: any;
}

declare module 'd3-scale/src/utcTime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-scale/dist/d3-scale.js' {
  declare module.exports: $Exports<'d3-scale/dist/d3-scale'>;
}
declare module 'd3-scale/dist/d3-scale.min.js' {
  declare module.exports: $Exports<'d3-scale/dist/d3-scale.min'>;
}
declare module 'd3-scale/src/band.js' {
  declare module.exports: $Exports<'d3-scale/src/band'>;
}
declare module 'd3-scale/src/colors.js' {
  declare module.exports: $Exports<'d3-scale/src/colors'>;
}
declare module 'd3-scale/src/constant.js' {
  declare module.exports: $Exports<'d3-scale/src/constant'>;
}
declare module 'd3-scale/src/continuous.js' {
  declare module.exports: $Exports<'d3-scale/src/continuous'>;
}
declare module 'd3-scale/src/diverging.js' {
  declare module.exports: $Exports<'d3-scale/src/diverging'>;
}
declare module 'd3-scale/src/identity.js' {
  declare module.exports: $Exports<'d3-scale/src/identity'>;
}
declare module 'd3-scale/src/index' {
  declare module.exports: $Exports<'d3-scale/src'>;
}
declare module 'd3-scale/src/index.js' {
  declare module.exports: $Exports<'d3-scale/src'>;
}
declare module 'd3-scale/src/init.js' {
  declare module.exports: $Exports<'d3-scale/src/init'>;
}
declare module 'd3-scale/src/linear.js' {
  declare module.exports: $Exports<'d3-scale/src/linear'>;
}
declare module 'd3-scale/src/log.js' {
  declare module.exports: $Exports<'d3-scale/src/log'>;
}
declare module 'd3-scale/src/nice.js' {
  declare module.exports: $Exports<'d3-scale/src/nice'>;
}
declare module 'd3-scale/src/number.js' {
  declare module.exports: $Exports<'d3-scale/src/number'>;
}
declare module 'd3-scale/src/ordinal.js' {
  declare module.exports: $Exports<'d3-scale/src/ordinal'>;
}
declare module 'd3-scale/src/pow.js' {
  declare module.exports: $Exports<'d3-scale/src/pow'>;
}
declare module 'd3-scale/src/quantile.js' {
  declare module.exports: $Exports<'d3-scale/src/quantile'>;
}
declare module 'd3-scale/src/quantize.js' {
  declare module.exports: $Exports<'d3-scale/src/quantize'>;
}
declare module 'd3-scale/src/radial.js' {
  declare module.exports: $Exports<'d3-scale/src/radial'>;
}
declare module 'd3-scale/src/sequential.js' {
  declare module.exports: $Exports<'d3-scale/src/sequential'>;
}
declare module 'd3-scale/src/sequentialQuantile.js' {
  declare module.exports: $Exports<'d3-scale/src/sequentialQuantile'>;
}
declare module 'd3-scale/src/symlog.js' {
  declare module.exports: $Exports<'d3-scale/src/symlog'>;
}
declare module 'd3-scale/src/threshold.js' {
  declare module.exports: $Exports<'d3-scale/src/threshold'>;
}
declare module 'd3-scale/src/tickFormat.js' {
  declare module.exports: $Exports<'d3-scale/src/tickFormat'>;
}
declare module 'd3-scale/src/time.js' {
  declare module.exports: $Exports<'d3-scale/src/time'>;
}
declare module 'd3-scale/src/utcTime.js' {
  declare module.exports: $Exports<'d3-scale/src/utcTime'>;
}
