// flow-typed signature: ae41f78efaed44bca8a3bcaf01c39c0c
// flow-typed version: <<STUB>>/detect-browser-language_v0.0.2/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'detect-browser-language'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'detect-browser-language' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'detect-browser-language/index' {
  declare module.exports: $Exports<'detect-browser-language'>;
}
declare module 'detect-browser-language/index.js' {
  declare module.exports: $Exports<'detect-browser-language'>;
}
