// flow-typed signature: 23d155ea9823a1a50e129e222f6af8de
// flow-typed version: <<STUB>>/detect-browser-language_v0.0.2/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'detect-browser-language'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'detect-browser-language' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'detect-browser-language/index' {
  declare module.exports: $Exports<'detect-browser-language'>;
}
declare module 'detect-browser-language/index.js' {
  declare module.exports: $Exports<'detect-browser-language'>;
}
