// flow-typed signature: 3e2e811439c69eac9e8b53762a516b92
// flow-typed version: <<STUB>>/eslint-plugin-vue-types_v^1.0.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-vue-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-vue-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-vue-types/lib/configs/strongly-recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue-types/lib' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue-types/lib/rules/require-default-prop' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-vue-types/lib/configs/strongly-recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-vue-types/lib/configs/strongly-recommended'>;
}
declare module 'eslint-plugin-vue-types/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-vue-types/lib'>;
}
declare module 'eslint-plugin-vue-types/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-vue-types/lib'>;
}
declare module 'eslint-plugin-vue-types/lib/rules/require-default-prop.js' {
  declare module.exports: $Exports<'eslint-plugin-vue-types/lib/rules/require-default-prop'>;
}
