// flow-typed signature: 4d8000e2d252c23642e16ee8019a81a8
// flow-typed version: <<STUB>>/jest-environment-jsdom-sixteen_v^1.0.3/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-environment-jsdom-sixteen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-environment-jsdom-sixteen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jest-environment-jsdom-sixteen/index' {
  declare module.exports: $Exports<'jest-environment-jsdom-sixteen'>;
}
declare module 'jest-environment-jsdom-sixteen/index.js' {
  declare module.exports: $Exports<'jest-environment-jsdom-sixteen'>;
}
