// flow-typed signature: 956a59ae8021f7edce315bb73b7380cf
// flow-typed version: <<STUB>>/jest-vue-preprocessor_v^1.7.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-vue-preprocessor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-vue-preprocessor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-vue-preprocessor/test/fixtures/srcImportComponent/srcImport' {
  declare module.exports: any;
}

declare module 'jest-vue-preprocessor/test/index.spec' {
  declare module.exports: any;
}

declare module 'jest-vue-preprocessor/transforms' {
  declare module.exports: any;
}

declare module 'jest-vue-preprocessor/transforms/transformBabel' {
  declare module.exports: any;
}

declare module 'jest-vue-preprocessor/transforms/transformTs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-vue-preprocessor/index' {
  declare module.exports: $Exports<'jest-vue-preprocessor'>;
}
declare module 'jest-vue-preprocessor/index.js' {
  declare module.exports: $Exports<'jest-vue-preprocessor'>;
}
declare module 'jest-vue-preprocessor/test/fixtures/srcImportComponent/srcImport.js' {
  declare module.exports: $Exports<'jest-vue-preprocessor/test/fixtures/srcImportComponent/srcImport'>;
}
declare module 'jest-vue-preprocessor/test/index.spec.js' {
  declare module.exports: $Exports<'jest-vue-preprocessor/test/index.spec'>;
}
declare module 'jest-vue-preprocessor/transforms/index' {
  declare module.exports: $Exports<'jest-vue-preprocessor/transforms'>;
}
declare module 'jest-vue-preprocessor/transforms/index.js' {
  declare module.exports: $Exports<'jest-vue-preprocessor/transforms'>;
}
declare module 'jest-vue-preprocessor/transforms/transformBabel.js' {
  declare module.exports: $Exports<'jest-vue-preprocessor/transforms/transformBabel'>;
}
declare module 'jest-vue-preprocessor/transforms/transformTs.js' {
  declare module.exports: $Exports<'jest-vue-preprocessor/transforms/transformTs'>;
}
