// flow-typed signature: aee05858a5b68627755aa30c430fdf65
// flow-typed version: <<STUB>>/leaflet-pixi-overlay_v^1.8.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-pixi-overlay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet-pixi-overlay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet-pixi-overlay/L.PixiOverlay' {
  declare module.exports: any;
}

declare module 'leaflet-pixi-overlay/L.PixiOverlay.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet-pixi-overlay/L.PixiOverlay.js' {
  declare module.exports: $Exports<'leaflet-pixi-overlay/L.PixiOverlay'>;
}
declare module 'leaflet-pixi-overlay/L.PixiOverlay.min.js' {
  declare module.exports: $Exports<'leaflet-pixi-overlay/L.PixiOverlay.min'>;
}
