// flow-typed signature: c23c0a90404c72fbc1f76e4919540340
// flow-typed version: <<STUB>>/leaflet-loading_v^0.1.24/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-loading'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet-loading' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet-loading/src/Control.Loading' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet-loading/src/Control.Loading.js' {
  declare module.exports: $Exports<'leaflet-loading/src/Control.Loading'>;
}
