// flow-typed signature: d9994b601e3675fad18dee06b62cac37
// flow-typed version: <<STUB>>/leaflet.heat_v^0.2.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet.heat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet.heat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet.heat/dist/leaflet-heat' {
  declare module.exports: any;
}

declare module 'leaflet.heat/src/HeatLayer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet.heat/dist/leaflet-heat.js' {
  declare module.exports: $Exports<'leaflet.heat/dist/leaflet-heat'>;
}
declare module 'leaflet.heat/src/HeatLayer.js' {
  declare module.exports: $Exports<'leaflet.heat/src/HeatLayer'>;
}
