// flow-typed signature: 1fd0044cd778b8c0cbe10b3df97aad5e
// flow-typed version: <<STUB>>/less-loader_v^6.2.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'less-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'less-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'less-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'less-loader/dist' {
  declare module.exports: any;
}

declare module 'less-loader/dist/LessError' {
  declare module.exports: any;
}

declare module 'less-loader/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'less-loader/dist/cjs.js' {
  declare module.exports: $Exports<'less-loader/dist/cjs'>;
}
declare module 'less-loader/dist/index' {
  declare module.exports: $Exports<'less-loader/dist'>;
}
declare module 'less-loader/dist/index.js' {
  declare module.exports: $Exports<'less-loader/dist'>;
}
declare module 'less-loader/dist/LessError.js' {
  declare module.exports: $Exports<'less-loader/dist/LessError'>;
}
declare module 'less-loader/dist/utils.js' {
  declare module.exports: $Exports<'less-loader/dist/utils'>;
}
