// flow-typed signature: 1c92b09b1fe6d2387af9dc87ad21efb6
// flow-typed version: <<STUB>>/libphonenumber-js_v^1.7.50/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libphonenumber-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'libphonenumber-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libphonenumber-js/babel.config' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/bin/update-metadata' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/AsYouType' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/AsYouType.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/constants' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/extension' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/isValidCandidate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/isValidPreCandidate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/Leniency' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/Leniency.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/LRUCache' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/parsePreCandidate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/RegExpCache' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/utf-8' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/util' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/util.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findPhoneNumbers_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findPhoneNumbers' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findPhoneNumbers.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findPhoneNumbersInText' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findPhoneNumbersInText.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/format_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/format' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/format.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/formatIncompletePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/formatIncompletePhoneNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/formatNumberForMobileDialing' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/formatNumberForMobileDialing.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/getCountries' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/getCountries.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/getCountryCallingCode' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/getCountryCallingCode.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/getExampleNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/getExampleNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/getNumberType_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/getNumberType' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/getNumberType.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/IDD' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/isPossibleNumber_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/isPossibleNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/isPossibleNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/isValidNumberForRegion_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/isValidNumberForRegion' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/isValidNumberForRegion.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/isViablePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/metadata' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/metadata.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parse_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parse' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parse.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parseDigits' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parseDigits.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/ParseError' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parseIncompletePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parseIncompletePhoneNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parsePhoneNumber_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parsePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parsePhoneNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parsePhoneNumberFromString_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parsePhoneNumberFromString' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parsePhoneNumberFromString.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/PhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/PhoneNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/PhoneNumberMatcher' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/PhoneNumberMatcher.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/RFC3966' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/RFC3966.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/searchNumbers' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/searchNumbers.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/searchPhoneNumbersInText' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/searchPhoneNumbersInText.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/tools/compress' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/tools/download' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/tools/generate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/tools/semver-compare' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/tools/semver-compare.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/util' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/util.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/validate_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/validate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/validate.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/bundle/libphonenumber-js.min' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/bundle/libphonenumber-max' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/bundle/libphonenumber-min' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/bundle/libphonenumber-mobile' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/core/index.commonjs' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/core' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/custom' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/AsYouType' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/AsYouType.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/constants' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/extension' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/isValidCandidate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/isValidPreCandidate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/Leniency' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/Leniency.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/LRUCache' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/parsePreCandidate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/RegExpCache' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/utf-8' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/util' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/util.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findPhoneNumbers_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findPhoneNumbers' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findPhoneNumbers.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findPhoneNumbersInText' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findPhoneNumbersInText.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/format_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/format' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/format.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/formatIncompletePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/formatIncompletePhoneNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/formatNumberForMobileDialing' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/formatNumberForMobileDialing.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/getCountries' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/getCountries.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/getCountryCallingCode' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/getCountryCallingCode.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/getExampleNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/getExampleNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/getNumberType_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/getNumberType' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/getNumberType.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/IDD' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/isPossibleNumber_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/isPossibleNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/isPossibleNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/isValidNumberForRegion_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/isValidNumberForRegion' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/isValidNumberForRegion.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/isViablePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/metadata' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/metadata.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parse_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parse' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parse.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parseDigits' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parseDigits.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/ParseError' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parseIncompletePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parseIncompletePhoneNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parsePhoneNumber_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parsePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parsePhoneNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parsePhoneNumberFromString_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parsePhoneNumberFromString' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parsePhoneNumberFromString.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/PhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/PhoneNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/PhoneNumberMatcher' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/PhoneNumberMatcher.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/RFC3966' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/RFC3966.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/searchNumbers' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/searchNumbers.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/searchPhoneNumbersInText' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/searchPhoneNumbersInText.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/tools/compress' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/tools/download' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/tools/generate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/tools/semver-compare' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/tools/semver-compare.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/util' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/util.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/validate_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/validate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/validate.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/examples.mobile.json' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/index.common' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/index.es6' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/max/index.commonjs' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/max' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/metadata.full.json' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/metadata.min.json' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/metadata.mobile.json' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/min/index.commonjs' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/min' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/mobile/index.commonjs' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/mobile' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/rollup.config' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/download' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/generate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/json-to-js' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/metadata-branch' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/metadata-update-and-push-and-pull-request' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/metadata-update-and-push' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/metadata-update-and-release' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/modules/commit' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/modules/exec' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/modules/update-metadata' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/AsYouType' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/AsYouType.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/constants' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/extension' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findNumbers_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findNumbers' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findNumbers.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findNumbers/isValidCandidate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findNumbers/isValidPreCandidate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findNumbers/Leniency' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findNumbers/Leniency.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findNumbers/LRUCache' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findNumbers/parsePreCandidate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findNumbers/RegExpCache' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findNumbers/utf-8' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findNumbers/util' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findNumbers/util.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findPhoneNumbers_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findPhoneNumbers' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findPhoneNumbers.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findPhoneNumbersInText' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/findPhoneNumbersInText.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/format_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/format' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/format.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/formatIncompletePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/formatIncompletePhoneNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/formatNumberForMobileDialing' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/formatNumberForMobileDialing.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/getCountries' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/getCountries.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/getCountryCallingCode' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/getCountryCallingCode.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/getExampleNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/getExampleNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/getNumberType_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/getNumberType' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/getNumberType.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/IDD' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/isPossibleNumber_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/isPossibleNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/isPossibleNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/isValidNumberForRegion_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/isValidNumberForRegion' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/isValidNumberForRegion.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/isViablePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/metadata' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/metadata.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/parse_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/parse' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/parse.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/parseDigits' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/parseDigits.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/ParseError' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/parseIncompletePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/parseIncompletePhoneNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/parsePhoneNumber_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/parsePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/parsePhoneNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/parsePhoneNumberFromString_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/parsePhoneNumberFromString' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/parsePhoneNumberFromString.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/PhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/PhoneNumber.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/PhoneNumberMatcher' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/PhoneNumberMatcher.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/RFC3966' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/RFC3966.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/searchNumbers' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/searchNumbers.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/searchPhoneNumbersInText' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/searchPhoneNumbersInText.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/tools/compress' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/tools/download' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/tools/generate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/tools/semver-compare' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/tools/semver-compare.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/util' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/util.test' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/validate_' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/validate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/source/validate.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'libphonenumber-js/babel.config.js' {
  declare module.exports: $Exports<'libphonenumber-js/babel.config'>;
}
declare module 'libphonenumber-js/bin/update-metadata.js' {
  declare module.exports: $Exports<'libphonenumber-js/bin/update-metadata'>;
}
declare module 'libphonenumber-js/build/AsYouType.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/AsYouType'>;
}
declare module 'libphonenumber-js/build/AsYouType.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/AsYouType.test'>;
}
declare module 'libphonenumber-js/build/constants.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/constants'>;
}
declare module 'libphonenumber-js/build/extension.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/extension'>;
}
declare module 'libphonenumber-js/build/findNumbers_.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers_'>;
}
declare module 'libphonenumber-js/build/findNumbers.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers'>;
}
declare module 'libphonenumber-js/build/findNumbers.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers.test'>;
}
declare module 'libphonenumber-js/build/findNumbers/isValidCandidate.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/isValidCandidate'>;
}
declare module 'libphonenumber-js/build/findNumbers/isValidPreCandidate.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/isValidPreCandidate'>;
}
declare module 'libphonenumber-js/build/findNumbers/Leniency.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/Leniency'>;
}
declare module 'libphonenumber-js/build/findNumbers/Leniency.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/Leniency.test'>;
}
declare module 'libphonenumber-js/build/findNumbers/LRUCache.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/LRUCache'>;
}
declare module 'libphonenumber-js/build/findNumbers/parsePreCandidate.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/parsePreCandidate'>;
}
declare module 'libphonenumber-js/build/findNumbers/RegExpCache.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/RegExpCache'>;
}
declare module 'libphonenumber-js/build/findNumbers/utf-8.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/utf-8'>;
}
declare module 'libphonenumber-js/build/findNumbers/util.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/util'>;
}
declare module 'libphonenumber-js/build/findNumbers/util.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/util.test'>;
}
declare module 'libphonenumber-js/build/findPhoneNumbers_.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findPhoneNumbers_'>;
}
declare module 'libphonenumber-js/build/findPhoneNumbers.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findPhoneNumbers'>;
}
declare module 'libphonenumber-js/build/findPhoneNumbers.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findPhoneNumbers.test'>;
}
declare module 'libphonenumber-js/build/findPhoneNumbersInText.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findPhoneNumbersInText'>;
}
declare module 'libphonenumber-js/build/findPhoneNumbersInText.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findPhoneNumbersInText.test'>;
}
declare module 'libphonenumber-js/build/format_.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/format_'>;
}
declare module 'libphonenumber-js/build/format.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/format'>;
}
declare module 'libphonenumber-js/build/format.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/format.test'>;
}
declare module 'libphonenumber-js/build/formatIncompletePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/formatIncompletePhoneNumber'>;
}
declare module 'libphonenumber-js/build/formatIncompletePhoneNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/formatIncompletePhoneNumber.test'>;
}
declare module 'libphonenumber-js/build/formatNumberForMobileDialing.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/formatNumberForMobileDialing'>;
}
declare module 'libphonenumber-js/build/formatNumberForMobileDialing.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/formatNumberForMobileDialing.test'>;
}
declare module 'libphonenumber-js/build/getCountries.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/getCountries'>;
}
declare module 'libphonenumber-js/build/getCountries.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/getCountries.test'>;
}
declare module 'libphonenumber-js/build/getCountryCallingCode.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/getCountryCallingCode'>;
}
declare module 'libphonenumber-js/build/getCountryCallingCode.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/getCountryCallingCode.test'>;
}
declare module 'libphonenumber-js/build/getExampleNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/getExampleNumber'>;
}
declare module 'libphonenumber-js/build/getExampleNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/getExampleNumber.test'>;
}
declare module 'libphonenumber-js/build/getNumberType_.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/getNumberType_'>;
}
declare module 'libphonenumber-js/build/getNumberType.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/getNumberType'>;
}
declare module 'libphonenumber-js/build/getNumberType.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/getNumberType.test'>;
}
declare module 'libphonenumber-js/build/IDD.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/IDD'>;
}
declare module 'libphonenumber-js/build/isPossibleNumber_.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/isPossibleNumber_'>;
}
declare module 'libphonenumber-js/build/isPossibleNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/isPossibleNumber'>;
}
declare module 'libphonenumber-js/build/isPossibleNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/isPossibleNumber.test'>;
}
declare module 'libphonenumber-js/build/isValidNumberForRegion_.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/isValidNumberForRegion_'>;
}
declare module 'libphonenumber-js/build/isValidNumberForRegion.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/isValidNumberForRegion'>;
}
declare module 'libphonenumber-js/build/isValidNumberForRegion.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/isValidNumberForRegion.test'>;
}
declare module 'libphonenumber-js/build/isViablePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/isViablePhoneNumber'>;
}
declare module 'libphonenumber-js/build/metadata.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/metadata'>;
}
declare module 'libphonenumber-js/build/metadata.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/metadata.test'>;
}
declare module 'libphonenumber-js/build/parse_.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parse_'>;
}
declare module 'libphonenumber-js/build/parse.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parse'>;
}
declare module 'libphonenumber-js/build/parse.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parse.test'>;
}
declare module 'libphonenumber-js/build/parseDigits.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parseDigits'>;
}
declare module 'libphonenumber-js/build/parseDigits.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parseDigits.test'>;
}
declare module 'libphonenumber-js/build/ParseError.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/ParseError'>;
}
declare module 'libphonenumber-js/build/parseIncompletePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parseIncompletePhoneNumber'>;
}
declare module 'libphonenumber-js/build/parseIncompletePhoneNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parseIncompletePhoneNumber.test'>;
}
declare module 'libphonenumber-js/build/parsePhoneNumber_.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parsePhoneNumber_'>;
}
declare module 'libphonenumber-js/build/parsePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parsePhoneNumber'>;
}
declare module 'libphonenumber-js/build/parsePhoneNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parsePhoneNumber.test'>;
}
declare module 'libphonenumber-js/build/parsePhoneNumberFromString_.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parsePhoneNumberFromString_'>;
}
declare module 'libphonenumber-js/build/parsePhoneNumberFromString.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parsePhoneNumberFromString'>;
}
declare module 'libphonenumber-js/build/parsePhoneNumberFromString.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parsePhoneNumberFromString.test'>;
}
declare module 'libphonenumber-js/build/PhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/PhoneNumber'>;
}
declare module 'libphonenumber-js/build/PhoneNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/PhoneNumber.test'>;
}
declare module 'libphonenumber-js/build/PhoneNumberMatcher.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/PhoneNumberMatcher'>;
}
declare module 'libphonenumber-js/build/PhoneNumberMatcher.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/PhoneNumberMatcher.test'>;
}
declare module 'libphonenumber-js/build/RFC3966.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/RFC3966'>;
}
declare module 'libphonenumber-js/build/RFC3966.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/RFC3966.test'>;
}
declare module 'libphonenumber-js/build/searchNumbers.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/searchNumbers'>;
}
declare module 'libphonenumber-js/build/searchNumbers.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/searchNumbers.test'>;
}
declare module 'libphonenumber-js/build/searchPhoneNumbersInText.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/searchPhoneNumbersInText'>;
}
declare module 'libphonenumber-js/build/searchPhoneNumbersInText.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/searchPhoneNumbersInText.test'>;
}
declare module 'libphonenumber-js/build/tools/compress.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/tools/compress'>;
}
declare module 'libphonenumber-js/build/tools/download.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/tools/download'>;
}
declare module 'libphonenumber-js/build/tools/generate.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/tools/generate'>;
}
declare module 'libphonenumber-js/build/tools/semver-compare.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/tools/semver-compare'>;
}
declare module 'libphonenumber-js/build/tools/semver-compare.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/tools/semver-compare.test'>;
}
declare module 'libphonenumber-js/build/util.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/util'>;
}
declare module 'libphonenumber-js/build/util.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/util.test'>;
}
declare module 'libphonenumber-js/build/validate_.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/validate_'>;
}
declare module 'libphonenumber-js/build/validate.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/validate'>;
}
declare module 'libphonenumber-js/build/validate.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/validate.test'>;
}
declare module 'libphonenumber-js/bundle/libphonenumber-js.min.js' {
  declare module.exports: $Exports<'libphonenumber-js/bundle/libphonenumber-js.min'>;
}
declare module 'libphonenumber-js/bundle/libphonenumber-max.js' {
  declare module.exports: $Exports<'libphonenumber-js/bundle/libphonenumber-max'>;
}
declare module 'libphonenumber-js/bundle/libphonenumber-min.js' {
  declare module.exports: $Exports<'libphonenumber-js/bundle/libphonenumber-min'>;
}
declare module 'libphonenumber-js/bundle/libphonenumber-mobile.js' {
  declare module.exports: $Exports<'libphonenumber-js/bundle/libphonenumber-mobile'>;
}
declare module 'libphonenumber-js/core/index.commonjs.js' {
  declare module.exports: $Exports<'libphonenumber-js/core/index.commonjs'>;
}
declare module 'libphonenumber-js/core/index' {
  declare module.exports: $Exports<'libphonenumber-js/core'>;
}
declare module 'libphonenumber-js/core/index.js' {
  declare module.exports: $Exports<'libphonenumber-js/core'>;
}
declare module 'libphonenumber-js/custom.js' {
  declare module.exports: $Exports<'libphonenumber-js/custom'>;
}
declare module 'libphonenumber-js/es6/AsYouType.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/AsYouType'>;
}
declare module 'libphonenumber-js/es6/AsYouType.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/AsYouType.test'>;
}
declare module 'libphonenumber-js/es6/constants.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/constants'>;
}
declare module 'libphonenumber-js/es6/extension.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/extension'>;
}
declare module 'libphonenumber-js/es6/findNumbers_.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers_'>;
}
declare module 'libphonenumber-js/es6/findNumbers.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers'>;
}
declare module 'libphonenumber-js/es6/findNumbers.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers.test'>;
}
declare module 'libphonenumber-js/es6/findNumbers/isValidCandidate.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/isValidCandidate'>;
}
declare module 'libphonenumber-js/es6/findNumbers/isValidPreCandidate.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/isValidPreCandidate'>;
}
declare module 'libphonenumber-js/es6/findNumbers/Leniency.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/Leniency'>;
}
declare module 'libphonenumber-js/es6/findNumbers/Leniency.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/Leniency.test'>;
}
declare module 'libphonenumber-js/es6/findNumbers/LRUCache.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/LRUCache'>;
}
declare module 'libphonenumber-js/es6/findNumbers/parsePreCandidate.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/parsePreCandidate'>;
}
declare module 'libphonenumber-js/es6/findNumbers/RegExpCache.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/RegExpCache'>;
}
declare module 'libphonenumber-js/es6/findNumbers/utf-8.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/utf-8'>;
}
declare module 'libphonenumber-js/es6/findNumbers/util.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/util'>;
}
declare module 'libphonenumber-js/es6/findNumbers/util.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/util.test'>;
}
declare module 'libphonenumber-js/es6/findPhoneNumbers_.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findPhoneNumbers_'>;
}
declare module 'libphonenumber-js/es6/findPhoneNumbers.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findPhoneNumbers'>;
}
declare module 'libphonenumber-js/es6/findPhoneNumbers.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findPhoneNumbers.test'>;
}
declare module 'libphonenumber-js/es6/findPhoneNumbersInText.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findPhoneNumbersInText'>;
}
declare module 'libphonenumber-js/es6/findPhoneNumbersInText.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findPhoneNumbersInText.test'>;
}
declare module 'libphonenumber-js/es6/format_.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/format_'>;
}
declare module 'libphonenumber-js/es6/format.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/format'>;
}
declare module 'libphonenumber-js/es6/format.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/format.test'>;
}
declare module 'libphonenumber-js/es6/formatIncompletePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/formatIncompletePhoneNumber'>;
}
declare module 'libphonenumber-js/es6/formatIncompletePhoneNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/formatIncompletePhoneNumber.test'>;
}
declare module 'libphonenumber-js/es6/formatNumberForMobileDialing.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/formatNumberForMobileDialing'>;
}
declare module 'libphonenumber-js/es6/formatNumberForMobileDialing.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/formatNumberForMobileDialing.test'>;
}
declare module 'libphonenumber-js/es6/getCountries.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/getCountries'>;
}
declare module 'libphonenumber-js/es6/getCountries.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/getCountries.test'>;
}
declare module 'libphonenumber-js/es6/getCountryCallingCode.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/getCountryCallingCode'>;
}
declare module 'libphonenumber-js/es6/getCountryCallingCode.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/getCountryCallingCode.test'>;
}
declare module 'libphonenumber-js/es6/getExampleNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/getExampleNumber'>;
}
declare module 'libphonenumber-js/es6/getExampleNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/getExampleNumber.test'>;
}
declare module 'libphonenumber-js/es6/getNumberType_.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/getNumberType_'>;
}
declare module 'libphonenumber-js/es6/getNumberType.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/getNumberType'>;
}
declare module 'libphonenumber-js/es6/getNumberType.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/getNumberType.test'>;
}
declare module 'libphonenumber-js/es6/IDD.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/IDD'>;
}
declare module 'libphonenumber-js/es6/isPossibleNumber_.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/isPossibleNumber_'>;
}
declare module 'libphonenumber-js/es6/isPossibleNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/isPossibleNumber'>;
}
declare module 'libphonenumber-js/es6/isPossibleNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/isPossibleNumber.test'>;
}
declare module 'libphonenumber-js/es6/isValidNumberForRegion_.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/isValidNumberForRegion_'>;
}
declare module 'libphonenumber-js/es6/isValidNumberForRegion.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/isValidNumberForRegion'>;
}
declare module 'libphonenumber-js/es6/isValidNumberForRegion.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/isValidNumberForRegion.test'>;
}
declare module 'libphonenumber-js/es6/isViablePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/isViablePhoneNumber'>;
}
declare module 'libphonenumber-js/es6/metadata.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/metadata'>;
}
declare module 'libphonenumber-js/es6/metadata.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/metadata.test'>;
}
declare module 'libphonenumber-js/es6/parse_.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parse_'>;
}
declare module 'libphonenumber-js/es6/parse.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parse'>;
}
declare module 'libphonenumber-js/es6/parse.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parse.test'>;
}
declare module 'libphonenumber-js/es6/parseDigits.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parseDigits'>;
}
declare module 'libphonenumber-js/es6/parseDigits.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parseDigits.test'>;
}
declare module 'libphonenumber-js/es6/ParseError.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/ParseError'>;
}
declare module 'libphonenumber-js/es6/parseIncompletePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parseIncompletePhoneNumber'>;
}
declare module 'libphonenumber-js/es6/parseIncompletePhoneNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parseIncompletePhoneNumber.test'>;
}
declare module 'libphonenumber-js/es6/parsePhoneNumber_.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parsePhoneNumber_'>;
}
declare module 'libphonenumber-js/es6/parsePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parsePhoneNumber'>;
}
declare module 'libphonenumber-js/es6/parsePhoneNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parsePhoneNumber.test'>;
}
declare module 'libphonenumber-js/es6/parsePhoneNumberFromString_.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parsePhoneNumberFromString_'>;
}
declare module 'libphonenumber-js/es6/parsePhoneNumberFromString.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parsePhoneNumberFromString'>;
}
declare module 'libphonenumber-js/es6/parsePhoneNumberFromString.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parsePhoneNumberFromString.test'>;
}
declare module 'libphonenumber-js/es6/PhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/PhoneNumber'>;
}
declare module 'libphonenumber-js/es6/PhoneNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/PhoneNumber.test'>;
}
declare module 'libphonenumber-js/es6/PhoneNumberMatcher.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/PhoneNumberMatcher'>;
}
declare module 'libphonenumber-js/es6/PhoneNumberMatcher.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/PhoneNumberMatcher.test'>;
}
declare module 'libphonenumber-js/es6/RFC3966.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/RFC3966'>;
}
declare module 'libphonenumber-js/es6/RFC3966.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/RFC3966.test'>;
}
declare module 'libphonenumber-js/es6/searchNumbers.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/searchNumbers'>;
}
declare module 'libphonenumber-js/es6/searchNumbers.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/searchNumbers.test'>;
}
declare module 'libphonenumber-js/es6/searchPhoneNumbersInText.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/searchPhoneNumbersInText'>;
}
declare module 'libphonenumber-js/es6/searchPhoneNumbersInText.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/searchPhoneNumbersInText.test'>;
}
declare module 'libphonenumber-js/es6/tools/compress.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/tools/compress'>;
}
declare module 'libphonenumber-js/es6/tools/download.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/tools/download'>;
}
declare module 'libphonenumber-js/es6/tools/generate.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/tools/generate'>;
}
declare module 'libphonenumber-js/es6/tools/semver-compare.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/tools/semver-compare'>;
}
declare module 'libphonenumber-js/es6/tools/semver-compare.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/tools/semver-compare.test'>;
}
declare module 'libphonenumber-js/es6/util.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/util'>;
}
declare module 'libphonenumber-js/es6/util.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/util.test'>;
}
declare module 'libphonenumber-js/es6/validate_.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/validate_'>;
}
declare module 'libphonenumber-js/es6/validate.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/validate'>;
}
declare module 'libphonenumber-js/es6/validate.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/validate.test'>;
}
declare module 'libphonenumber-js/examples.mobile.json.js' {
  declare module.exports: $Exports<'libphonenumber-js/examples.mobile.json'>;
}
declare module 'libphonenumber-js/index.common.js' {
  declare module.exports: $Exports<'libphonenumber-js/index.common'>;
}
declare module 'libphonenumber-js/index.es6.js' {
  declare module.exports: $Exports<'libphonenumber-js/index.es6'>;
}
declare module 'libphonenumber-js/max/index.commonjs.js' {
  declare module.exports: $Exports<'libphonenumber-js/max/index.commonjs'>;
}
declare module 'libphonenumber-js/max/index' {
  declare module.exports: $Exports<'libphonenumber-js/max'>;
}
declare module 'libphonenumber-js/max/index.js' {
  declare module.exports: $Exports<'libphonenumber-js/max'>;
}
declare module 'libphonenumber-js/metadata.full.json.js' {
  declare module.exports: $Exports<'libphonenumber-js/metadata.full.json'>;
}
declare module 'libphonenumber-js/metadata.min.json.js' {
  declare module.exports: $Exports<'libphonenumber-js/metadata.min.json'>;
}
declare module 'libphonenumber-js/metadata.mobile.json.js' {
  declare module.exports: $Exports<'libphonenumber-js/metadata.mobile.json'>;
}
declare module 'libphonenumber-js/min/index.commonjs.js' {
  declare module.exports: $Exports<'libphonenumber-js/min/index.commonjs'>;
}
declare module 'libphonenumber-js/min/index' {
  declare module.exports: $Exports<'libphonenumber-js/min'>;
}
declare module 'libphonenumber-js/min/index.js' {
  declare module.exports: $Exports<'libphonenumber-js/min'>;
}
declare module 'libphonenumber-js/mobile/index.commonjs.js' {
  declare module.exports: $Exports<'libphonenumber-js/mobile/index.commonjs'>;
}
declare module 'libphonenumber-js/mobile/index' {
  declare module.exports: $Exports<'libphonenumber-js/mobile'>;
}
declare module 'libphonenumber-js/mobile/index.js' {
  declare module.exports: $Exports<'libphonenumber-js/mobile'>;
}
declare module 'libphonenumber-js/rollup.config.js' {
  declare module.exports: $Exports<'libphonenumber-js/rollup.config'>;
}
declare module 'libphonenumber-js/runnable/download.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/download'>;
}
declare module 'libphonenumber-js/runnable/generate.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/generate'>;
}
declare module 'libphonenumber-js/runnable/json-to-js.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/json-to-js'>;
}
declare module 'libphonenumber-js/runnable/metadata-branch.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/metadata-branch'>;
}
declare module 'libphonenumber-js/runnable/metadata-update-and-push-and-pull-request.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/metadata-update-and-push-and-pull-request'>;
}
declare module 'libphonenumber-js/runnable/metadata-update-and-push.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/metadata-update-and-push'>;
}
declare module 'libphonenumber-js/runnable/metadata-update-and-release.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/metadata-update-and-release'>;
}
declare module 'libphonenumber-js/runnable/modules/commit.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/modules/commit'>;
}
declare module 'libphonenumber-js/runnable/modules/exec.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/modules/exec'>;
}
declare module 'libphonenumber-js/runnable/modules/update-metadata.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/modules/update-metadata'>;
}
declare module 'libphonenumber-js/source/AsYouType.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/AsYouType'>;
}
declare module 'libphonenumber-js/source/AsYouType.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/AsYouType.test'>;
}
declare module 'libphonenumber-js/source/constants.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/constants'>;
}
declare module 'libphonenumber-js/source/extension.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/extension'>;
}
declare module 'libphonenumber-js/source/findNumbers_.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findNumbers_'>;
}
declare module 'libphonenumber-js/source/findNumbers.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findNumbers'>;
}
declare module 'libphonenumber-js/source/findNumbers.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findNumbers.test'>;
}
declare module 'libphonenumber-js/source/findNumbers/isValidCandidate.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findNumbers/isValidCandidate'>;
}
declare module 'libphonenumber-js/source/findNumbers/isValidPreCandidate.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findNumbers/isValidPreCandidate'>;
}
declare module 'libphonenumber-js/source/findNumbers/Leniency.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findNumbers/Leniency'>;
}
declare module 'libphonenumber-js/source/findNumbers/Leniency.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findNumbers/Leniency.test'>;
}
declare module 'libphonenumber-js/source/findNumbers/LRUCache.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findNumbers/LRUCache'>;
}
declare module 'libphonenumber-js/source/findNumbers/parsePreCandidate.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findNumbers/parsePreCandidate'>;
}
declare module 'libphonenumber-js/source/findNumbers/RegExpCache.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findNumbers/RegExpCache'>;
}
declare module 'libphonenumber-js/source/findNumbers/utf-8.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findNumbers/utf-8'>;
}
declare module 'libphonenumber-js/source/findNumbers/util.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findNumbers/util'>;
}
declare module 'libphonenumber-js/source/findNumbers/util.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findNumbers/util.test'>;
}
declare module 'libphonenumber-js/source/findPhoneNumbers_.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findPhoneNumbers_'>;
}
declare module 'libphonenumber-js/source/findPhoneNumbers.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findPhoneNumbers'>;
}
declare module 'libphonenumber-js/source/findPhoneNumbers.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findPhoneNumbers.test'>;
}
declare module 'libphonenumber-js/source/findPhoneNumbersInText.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findPhoneNumbersInText'>;
}
declare module 'libphonenumber-js/source/findPhoneNumbersInText.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/findPhoneNumbersInText.test'>;
}
declare module 'libphonenumber-js/source/format_.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/format_'>;
}
declare module 'libphonenumber-js/source/format.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/format'>;
}
declare module 'libphonenumber-js/source/format.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/format.test'>;
}
declare module 'libphonenumber-js/source/formatIncompletePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/formatIncompletePhoneNumber'>;
}
declare module 'libphonenumber-js/source/formatIncompletePhoneNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/formatIncompletePhoneNumber.test'>;
}
declare module 'libphonenumber-js/source/formatNumberForMobileDialing.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/formatNumberForMobileDialing'>;
}
declare module 'libphonenumber-js/source/formatNumberForMobileDialing.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/formatNumberForMobileDialing.test'>;
}
declare module 'libphonenumber-js/source/getCountries.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/getCountries'>;
}
declare module 'libphonenumber-js/source/getCountries.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/getCountries.test'>;
}
declare module 'libphonenumber-js/source/getCountryCallingCode.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/getCountryCallingCode'>;
}
declare module 'libphonenumber-js/source/getCountryCallingCode.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/getCountryCallingCode.test'>;
}
declare module 'libphonenumber-js/source/getExampleNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/getExampleNumber'>;
}
declare module 'libphonenumber-js/source/getExampleNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/getExampleNumber.test'>;
}
declare module 'libphonenumber-js/source/getNumberType_.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/getNumberType_'>;
}
declare module 'libphonenumber-js/source/getNumberType.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/getNumberType'>;
}
declare module 'libphonenumber-js/source/getNumberType.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/getNumberType.test'>;
}
declare module 'libphonenumber-js/source/IDD.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/IDD'>;
}
declare module 'libphonenumber-js/source/isPossibleNumber_.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/isPossibleNumber_'>;
}
declare module 'libphonenumber-js/source/isPossibleNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/isPossibleNumber'>;
}
declare module 'libphonenumber-js/source/isPossibleNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/isPossibleNumber.test'>;
}
declare module 'libphonenumber-js/source/isValidNumberForRegion_.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/isValidNumberForRegion_'>;
}
declare module 'libphonenumber-js/source/isValidNumberForRegion.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/isValidNumberForRegion'>;
}
declare module 'libphonenumber-js/source/isValidNumberForRegion.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/isValidNumberForRegion.test'>;
}
declare module 'libphonenumber-js/source/isViablePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/isViablePhoneNumber'>;
}
declare module 'libphonenumber-js/source/metadata.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/metadata'>;
}
declare module 'libphonenumber-js/source/metadata.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/metadata.test'>;
}
declare module 'libphonenumber-js/source/parse_.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/parse_'>;
}
declare module 'libphonenumber-js/source/parse.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/parse'>;
}
declare module 'libphonenumber-js/source/parse.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/parse.test'>;
}
declare module 'libphonenumber-js/source/parseDigits.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/parseDigits'>;
}
declare module 'libphonenumber-js/source/parseDigits.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/parseDigits.test'>;
}
declare module 'libphonenumber-js/source/ParseError.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/ParseError'>;
}
declare module 'libphonenumber-js/source/parseIncompletePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/parseIncompletePhoneNumber'>;
}
declare module 'libphonenumber-js/source/parseIncompletePhoneNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/parseIncompletePhoneNumber.test'>;
}
declare module 'libphonenumber-js/source/parsePhoneNumber_.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/parsePhoneNumber_'>;
}
declare module 'libphonenumber-js/source/parsePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/parsePhoneNumber'>;
}
declare module 'libphonenumber-js/source/parsePhoneNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/parsePhoneNumber.test'>;
}
declare module 'libphonenumber-js/source/parsePhoneNumberFromString_.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/parsePhoneNumberFromString_'>;
}
declare module 'libphonenumber-js/source/parsePhoneNumberFromString.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/parsePhoneNumberFromString'>;
}
declare module 'libphonenumber-js/source/parsePhoneNumberFromString.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/parsePhoneNumberFromString.test'>;
}
declare module 'libphonenumber-js/source/PhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/PhoneNumber'>;
}
declare module 'libphonenumber-js/source/PhoneNumber.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/PhoneNumber.test'>;
}
declare module 'libphonenumber-js/source/PhoneNumberMatcher.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/PhoneNumberMatcher'>;
}
declare module 'libphonenumber-js/source/PhoneNumberMatcher.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/PhoneNumberMatcher.test'>;
}
declare module 'libphonenumber-js/source/RFC3966.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/RFC3966'>;
}
declare module 'libphonenumber-js/source/RFC3966.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/RFC3966.test'>;
}
declare module 'libphonenumber-js/source/searchNumbers.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/searchNumbers'>;
}
declare module 'libphonenumber-js/source/searchNumbers.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/searchNumbers.test'>;
}
declare module 'libphonenumber-js/source/searchPhoneNumbersInText.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/searchPhoneNumbersInText'>;
}
declare module 'libphonenumber-js/source/searchPhoneNumbersInText.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/searchPhoneNumbersInText.test'>;
}
declare module 'libphonenumber-js/source/tools/compress.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/tools/compress'>;
}
declare module 'libphonenumber-js/source/tools/download.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/tools/download'>;
}
declare module 'libphonenumber-js/source/tools/generate.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/tools/generate'>;
}
declare module 'libphonenumber-js/source/tools/semver-compare.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/tools/semver-compare'>;
}
declare module 'libphonenumber-js/source/tools/semver-compare.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/tools/semver-compare.test'>;
}
declare module 'libphonenumber-js/source/util.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/util'>;
}
declare module 'libphonenumber-js/source/util.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/util.test'>;
}
declare module 'libphonenumber-js/source/validate_.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/validate_'>;
}
declare module 'libphonenumber-js/source/validate.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/validate'>;
}
declare module 'libphonenumber-js/source/validate.test.js' {
  declare module.exports: $Exports<'libphonenumber-js/source/validate.test'>;
}
