// flow-typed signature: b6a3aba23acc75173b67b8e1521f79cd
// flow-typed version: <<STUB>>/lodash-webpack-plugin_v^0.11.5/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lodash-webpack-plugin/lib' {
  declare module.exports: any;
}

declare module 'lodash-webpack-plugin/lib/listing' {
  declare module.exports: any;
}

declare module 'lodash-webpack-plugin/lib/mapping' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lodash-webpack-plugin/lib/index' {
  declare module.exports: $Exports<'lodash-webpack-plugin/lib'>;
}
declare module 'lodash-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'lodash-webpack-plugin/lib'>;
}
declare module 'lodash-webpack-plugin/lib/listing.js' {
  declare module.exports: $Exports<'lodash-webpack-plugin/lib/listing'>;
}
declare module 'lodash-webpack-plugin/lib/mapping.js' {
  declare module.exports: $Exports<'lodash-webpack-plugin/lib/mapping'>;
}
