// flow-typed signature: 6e700cccb3dc74b502c59f5d098fa173
// flow-typed version: <<STUB>>/marker-clusterer-plus_v^2.1.4/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'marker-clusterer-plus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'marker-clusterer-plus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'marker-clusterer-plus/src/markerclusterer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'marker-clusterer-plus/src/markerclusterer.js' {
  declare module.exports: $Exports<'marker-clusterer-plus/src/markerclusterer'>;
}
