// flow-typed signature: 0154bc0faa2fdcdbd2277007e9447bbe
// flow-typed version: <<STUB>>/pixi-filters_v^3.1.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pixi-filters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pixi-filters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pixi-filters/dist/pixi-filters' {
  declare module.exports: any;
}

declare module 'pixi-filters/lib/pixi-filters.cjs' {
  declare module.exports: any;
}

declare module 'pixi-filters/lib/pixi-filters.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pixi-filters/dist/pixi-filters.js' {
  declare module.exports: $Exports<'pixi-filters/dist/pixi-filters'>;
}
declare module 'pixi-filters/lib/pixi-filters.cjs.js' {
  declare module.exports: $Exports<'pixi-filters/lib/pixi-filters.cjs'>;
}
declare module 'pixi-filters/lib/pixi-filters.esm.js' {
  declare module.exports: $Exports<'pixi-filters/lib/pixi-filters.esm'>;
}
