// flow-typed signature: bbb798d0907073c1a08794cf61dcfc2d
// flow-typed version: <<STUB>>/postcss-atroot_v^0.1.3/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-atroot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-atroot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-atroot/gulpfile' {
  declare module.exports: any;
}

declare module 'postcss-atroot/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-atroot/gulpfile.js' {
  declare module.exports: $Exports<'postcss-atroot/gulpfile'>;
}
declare module 'postcss-atroot/index' {
  declare module.exports: $Exports<'postcss-atroot'>;
}
declare module 'postcss-atroot/index.js' {
  declare module.exports: $Exports<'postcss-atroot'>;
}
declare module 'postcss-atroot/test/test.js' {
  declare module.exports: $Exports<'postcss-atroot/test/test'>;
}
