// flow-typed signature: bc55991c6d7f7a932de9db0e2d0e4d82
// flow-typed version: <<STUB>>/postcss-advanced-variables_v^3.0.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-advanced-variables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-advanced-variables' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-advanced-variables/index' {
  declare module.exports: $Exports<'postcss-advanced-variables'>;
}
declare module 'postcss-advanced-variables/index.js' {
  declare module.exports: $Exports<'postcss-advanced-variables'>;
}
