// flow-typed signature: 490ca024271f34363a1b04951baac1d3
// flow-typed version: <<STUB>>/postcss-property-lookup_v^2.0.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-property-lookup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-property-lookup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-property-lookup/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-property-lookup/build/index' {
  declare module.exports: $Exports<'postcss-property-lookup/build'>;
}
declare module 'postcss-property-lookup/build/index.js' {
  declare module.exports: $Exports<'postcss-property-lookup/build'>;
}
