// flow-typed signature: 1718089540306e3e2560fe23d418146e
// flow-typed version: <<STUB>>/postcss-will-change-transition_v^1.2.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-will-change-transition'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-will-change-transition' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-will-change-transition/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-will-change-transition/index' {
  declare module.exports: $Exports<'postcss-will-change-transition'>;
}
declare module 'postcss-will-change-transition/index.js' {
  declare module.exports: $Exports<'postcss-will-change-transition'>;
}
declare module 'postcss-will-change-transition/index.test.js' {
  declare module.exports: $Exports<'postcss-will-change-transition/index.test'>;
}
