// flow-typed signature: 8a0a749a9462c2fbc688cc7e11fb5e6f
// flow-typed version: <<STUB>>/postcss-responsive-type_v^1.0.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-responsive-type'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-responsive-type' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-responsive-type/index' {
  declare module.exports: $Exports<'postcss-responsive-type'>;
}
declare module 'postcss-responsive-type/index.js' {
  declare module.exports: $Exports<'postcss-responsive-type'>;
}
