// flow-typed signature: 7981b4765c2fdd359bfdcbc36e8dbbe6
// flow-typed version: <<STUB>>/postcss-will-change_v^3.0.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-will-change'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-will-change' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-will-change/index' {
  declare module.exports: $Exports<'postcss-will-change'>;
}
declare module 'postcss-will-change/index.js' {
  declare module.exports: $Exports<'postcss-will-change'>;
}
