// flow-typed signature: 4b7b5ac0716f035f5e97069f2c17635d
// flow-typed version: <<STUB>>/samlify_v^2.7.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'samlify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'samlify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'samlify/build' {
  declare module.exports: any;
}

declare module 'samlify/build/src/api' {
  declare module.exports: any;
}

declare module 'samlify/build/src/binding-post' {
  declare module.exports: any;
}

declare module 'samlify/build/src/binding-redirect' {
  declare module.exports: any;
}

declare module 'samlify/build/src/entity-idp' {
  declare module.exports: any;
}

declare module 'samlify/build/src/entity-sp' {
  declare module.exports: any;
}

declare module 'samlify/build/src/entity' {
  declare module.exports: any;
}

declare module 'samlify/build/src/extractor' {
  declare module.exports: any;
}

declare module 'samlify/build/src/flow' {
  declare module.exports: any;
}

declare module 'samlify/build/src/libsaml' {
  declare module.exports: any;
}

declare module 'samlify/build/src/metadata-idp' {
  declare module.exports: any;
}

declare module 'samlify/build/src/metadata-sp' {
  declare module.exports: any;
}

declare module 'samlify/build/src/metadata' {
  declare module.exports: any;
}

declare module 'samlify/build/src/types' {
  declare module.exports: any;
}

declare module 'samlify/build/src/urn' {
  declare module.exports: any;
}

declare module 'samlify/build/src/utility' {
  declare module.exports: any;
}

declare module 'samlify/build/src/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'samlify/build/index' {
  declare module.exports: $Exports<'samlify/build'>;
}
declare module 'samlify/build/index.js' {
  declare module.exports: $Exports<'samlify/build'>;
}
declare module 'samlify/build/src/api.js' {
  declare module.exports: $Exports<'samlify/build/src/api'>;
}
declare module 'samlify/build/src/binding-post.js' {
  declare module.exports: $Exports<'samlify/build/src/binding-post'>;
}
declare module 'samlify/build/src/binding-redirect.js' {
  declare module.exports: $Exports<'samlify/build/src/binding-redirect'>;
}
declare module 'samlify/build/src/entity-idp.js' {
  declare module.exports: $Exports<'samlify/build/src/entity-idp'>;
}
declare module 'samlify/build/src/entity-sp.js' {
  declare module.exports: $Exports<'samlify/build/src/entity-sp'>;
}
declare module 'samlify/build/src/entity.js' {
  declare module.exports: $Exports<'samlify/build/src/entity'>;
}
declare module 'samlify/build/src/extractor.js' {
  declare module.exports: $Exports<'samlify/build/src/extractor'>;
}
declare module 'samlify/build/src/flow.js' {
  declare module.exports: $Exports<'samlify/build/src/flow'>;
}
declare module 'samlify/build/src/libsaml.js' {
  declare module.exports: $Exports<'samlify/build/src/libsaml'>;
}
declare module 'samlify/build/src/metadata-idp.js' {
  declare module.exports: $Exports<'samlify/build/src/metadata-idp'>;
}
declare module 'samlify/build/src/metadata-sp.js' {
  declare module.exports: $Exports<'samlify/build/src/metadata-sp'>;
}
declare module 'samlify/build/src/metadata.js' {
  declare module.exports: $Exports<'samlify/build/src/metadata'>;
}
declare module 'samlify/build/src/types.js' {
  declare module.exports: $Exports<'samlify/build/src/types'>;
}
declare module 'samlify/build/src/urn.js' {
  declare module.exports: $Exports<'samlify/build/src/urn'>;
}
declare module 'samlify/build/src/utility.js' {
  declare module.exports: $Exports<'samlify/build/src/utility'>;
}
declare module 'samlify/build/src/validator.js' {
  declare module.exports: $Exports<'samlify/build/src/validator'>;
}
