// flow-typed signature: 6a59be41cb1ac9a253c7045cb8ec336b
// flow-typed version: <<STUB>>/shpjs_v^3.5.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shpjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shpjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shpjs/dist/shp' {
  declare module.exports: any;
}

declare module 'shpjs/dist/shp.min' {
  declare module.exports: any;
}

declare module 'shpjs/lib/binaryajax-browser' {
  declare module.exports: any;
}

declare module 'shpjs/lib/binaryajax-fetch' {
  declare module.exports: any;
}

declare module 'shpjs/lib/binaryajax' {
  declare module.exports: any;
}

declare module 'shpjs/lib' {
  declare module.exports: any;
}

declare module 'shpjs/lib/parseShp' {
  declare module.exports: any;
}

declare module 'shpjs/lib/unzip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shpjs/dist/shp.js' {
  declare module.exports: $Exports<'shpjs/dist/shp'>;
}
declare module 'shpjs/dist/shp.min.js' {
  declare module.exports: $Exports<'shpjs/dist/shp.min'>;
}
declare module 'shpjs/lib/binaryajax-browser.js' {
  declare module.exports: $Exports<'shpjs/lib/binaryajax-browser'>;
}
declare module 'shpjs/lib/binaryajax-fetch.js' {
  declare module.exports: $Exports<'shpjs/lib/binaryajax-fetch'>;
}
declare module 'shpjs/lib/binaryajax.js' {
  declare module.exports: $Exports<'shpjs/lib/binaryajax'>;
}
declare module 'shpjs/lib/index' {
  declare module.exports: $Exports<'shpjs/lib'>;
}
declare module 'shpjs/lib/index.js' {
  declare module.exports: $Exports<'shpjs/lib'>;
}
declare module 'shpjs/lib/parseShp.js' {
  declare module.exports: $Exports<'shpjs/lib/parseShp'>;
}
declare module 'shpjs/lib/unzip.js' {
  declare module.exports: $Exports<'shpjs/lib/unzip'>;
}
