// flow-typed signature: 58184606d9cc16f66b6b02affd263704
// flow-typed version: <<STUB>>/spin.js_v^4.1.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spin.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spin.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spin.js/spin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spin.js/spin.js' {
  declare module.exports: $Exports<'spin.js/spin'>;
}
