// flow-typed signature: 6e186d12ea4c72cae9b84534aef75209
// flow-typed version: <<STUB>>/start-server-and-test_v^1.10.11/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'start-server-and-test'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'start-server-and-test' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'start-server-and-test/src/bin/start' {
  declare module.exports: any;
}

declare module 'start-server-and-test/src' {
  declare module.exports: any;
}

declare module 'start-server-and-test/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'start-server-and-test/src/bin/start.js' {
  declare module.exports: $Exports<'start-server-and-test/src/bin/start'>;
}
declare module 'start-server-and-test/src/index' {
  declare module.exports: $Exports<'start-server-and-test/src'>;
}
declare module 'start-server-and-test/src/index.js' {
  declare module.exports: $Exports<'start-server-and-test/src'>;
}
declare module 'start-server-and-test/src/utils.js' {
  declare module.exports: $Exports<'start-server-and-test/src/utils'>;
}
