// flow-typed signature: a62e09d34ae8e5942ed51b32cacec6de
// flow-typed version: <<STUB>>/storybook-vue-router_v^1.0.7/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-vue-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-vue-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-vue-router/dist/vue' {
  declare module.exports: any;
}

declare module 'storybook-vue-router/vue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-vue-router/dist/vue.js' {
  declare module.exports: $Exports<'storybook-vue-router/dist/vue'>;
}
declare module 'storybook-vue-router/vue.js' {
  declare module.exports: $Exports<'storybook-vue-router/vue'>;
}
