// flow-typed signature: 7c4b2ab6c55064db5a0a685e8fbe057e
// flow-typed version: <<STUB>>/tailwindcss_v^1.5.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tailwindcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tailwindcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tailwindcss/defaultConfig' {
  declare module.exports: any;
}

declare module 'tailwindcss/defaultTheme' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/colors' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/commands/build' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/commands/help' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/commands' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/commands/init' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/compile' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/emoji' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/main' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/utils' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/constants' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/corePlugins' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/convertLayerAtRulesToControlComments' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/evaluateTailwindFunctions' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/formatCSS' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/getModuleDependencies' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/purgeUnusedStyles' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/registerConfigAsDependency' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/substituteClassApplyAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/substituteResponsiveAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/substituteScreenAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/substituteTailwindAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/substituteVariantsAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/accessibility' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/alignContent' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/alignItems' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/alignSelf' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/appearance' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backgroundAttachment' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backgroundColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backgroundOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backgroundPosition' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backgroundRepeat' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backgroundSize' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/borderCollapse' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/borderColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/borderOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/borderRadius' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/borderStyle' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/borderWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/boxShadow' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/boxSizing' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/clear' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/container' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/cursor' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/display' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/divideColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/divideOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/divideWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/fill' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/flex' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/flexDirection' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/flexGrow' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/flexShrink' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/flexWrap' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/float' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/fontFamily' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/fontSize' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/fontSmoothing' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/fontStyle' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/fontWeight' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gap' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridAutoFlow' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridColumn' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridColumnEnd' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridColumnStart' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridRow' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridRowEnd' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridRowStart' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridTemplateColumns' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridTemplateRows' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/height' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/inset' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/justifyContent' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/letterSpacing' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/lineHeight' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/listStylePosition' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/listStyleType' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/margin' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/maxHeight' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/maxWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/minHeight' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/minWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/objectFit' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/objectPosition' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/opacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/order' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/outline' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/overflow' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/padding' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/placeholderColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/placeholderOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/pointerEvents' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/position' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/preflight' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/resize' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/rotate' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/scale' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/skew' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/space' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/stroke' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/strokeWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/tableLayout' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/textAlign' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/textColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/textDecoration' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/textOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/textTransform' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/transform' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/transformOrigin' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/transitionDelay' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/transitionDuration' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/transitionProperty' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/transitionTimingFunction' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/translate' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/userSelect' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/verticalAlign' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/visibility' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/whitespace' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/width' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/wordBreak' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/zIndex' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/processTailwindFeatures' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/buildMediaQuery' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/buildSelectorVariant' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/cloneNodes' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/configurePlugins' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/createPlugin' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/createUtilityPlugin' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/escapeClassName' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/flattenColorPalette' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/generateVariantFunction' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/increaseSpecificity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/negateValue' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/parseObjectStyles' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/prefixNegativeModifiers' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/prefixSelector' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/processPlugins' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/resolveConfig' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/responsive' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/withAlphaVariable' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/wrapWithVariants' {
  declare module.exports: any;
}

declare module 'tailwindcss/plugin' {
  declare module.exports: any;
}

declare module 'tailwindcss/resolveConfig' {
  declare module.exports: any;
}

declare module 'tailwindcss/scripts/build' {
  declare module.exports: any;
}

declare module 'tailwindcss/scripts/rebuildFixtures' {
  declare module.exports: any;
}

declare module 'tailwindcss/stubs/defaultConfig.stub' {
  declare module.exports: any;
}

declare module 'tailwindcss/stubs/simpleConfig.stub' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tailwindcss/defaultConfig.js' {
  declare module.exports: $Exports<'tailwindcss/defaultConfig'>;
}
declare module 'tailwindcss/defaultTheme.js' {
  declare module.exports: $Exports<'tailwindcss/defaultTheme'>;
}
declare module 'tailwindcss/lib/cli.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli'>;
}
declare module 'tailwindcss/lib/cli/colors.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/colors'>;
}
declare module 'tailwindcss/lib/cli/commands/build.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/commands/build'>;
}
declare module 'tailwindcss/lib/cli/commands/help.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/commands/help'>;
}
declare module 'tailwindcss/lib/cli/commands/index' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/commands'>;
}
declare module 'tailwindcss/lib/cli/commands/index.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/commands'>;
}
declare module 'tailwindcss/lib/cli/commands/init.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/commands/init'>;
}
declare module 'tailwindcss/lib/cli/compile.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/compile'>;
}
declare module 'tailwindcss/lib/cli/emoji.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/emoji'>;
}
declare module 'tailwindcss/lib/cli/main.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/main'>;
}
declare module 'tailwindcss/lib/cli/utils.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/utils'>;
}
declare module 'tailwindcss/lib/constants.js' {
  declare module.exports: $Exports<'tailwindcss/lib/constants'>;
}
declare module 'tailwindcss/lib/corePlugins.js' {
  declare module.exports: $Exports<'tailwindcss/lib/corePlugins'>;
}
declare module 'tailwindcss/lib/index' {
  declare module.exports: $Exports<'tailwindcss/lib'>;
}
declare module 'tailwindcss/lib/index.js' {
  declare module.exports: $Exports<'tailwindcss/lib'>;
}
declare module 'tailwindcss/lib/lib/convertLayerAtRulesToControlComments.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/convertLayerAtRulesToControlComments'>;
}
declare module 'tailwindcss/lib/lib/evaluateTailwindFunctions.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/evaluateTailwindFunctions'>;
}
declare module 'tailwindcss/lib/lib/formatCSS.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/formatCSS'>;
}
declare module 'tailwindcss/lib/lib/getModuleDependencies.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/getModuleDependencies'>;
}
declare module 'tailwindcss/lib/lib/purgeUnusedStyles.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/purgeUnusedStyles'>;
}
declare module 'tailwindcss/lib/lib/registerConfigAsDependency.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/registerConfigAsDependency'>;
}
declare module 'tailwindcss/lib/lib/substituteClassApplyAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteClassApplyAtRules'>;
}
declare module 'tailwindcss/lib/lib/substituteResponsiveAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteResponsiveAtRules'>;
}
declare module 'tailwindcss/lib/lib/substituteScreenAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteScreenAtRules'>;
}
declare module 'tailwindcss/lib/lib/substituteTailwindAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteTailwindAtRules'>;
}
declare module 'tailwindcss/lib/lib/substituteVariantsAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteVariantsAtRules'>;
}
declare module 'tailwindcss/lib/plugins/accessibility.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/accessibility'>;
}
declare module 'tailwindcss/lib/plugins/alignContent.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/alignContent'>;
}
declare module 'tailwindcss/lib/plugins/alignItems.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/alignItems'>;
}
declare module 'tailwindcss/lib/plugins/alignSelf.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/alignSelf'>;
}
declare module 'tailwindcss/lib/plugins/appearance.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/appearance'>;
}
declare module 'tailwindcss/lib/plugins/backgroundAttachment.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backgroundAttachment'>;
}
declare module 'tailwindcss/lib/plugins/backgroundColor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backgroundColor'>;
}
declare module 'tailwindcss/lib/plugins/backgroundOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backgroundOpacity'>;
}
declare module 'tailwindcss/lib/plugins/backgroundPosition.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backgroundPosition'>;
}
declare module 'tailwindcss/lib/plugins/backgroundRepeat.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backgroundRepeat'>;
}
declare module 'tailwindcss/lib/plugins/backgroundSize.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backgroundSize'>;
}
declare module 'tailwindcss/lib/plugins/borderCollapse.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/borderCollapse'>;
}
declare module 'tailwindcss/lib/plugins/borderColor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/borderColor'>;
}
declare module 'tailwindcss/lib/plugins/borderOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/borderOpacity'>;
}
declare module 'tailwindcss/lib/plugins/borderRadius.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/borderRadius'>;
}
declare module 'tailwindcss/lib/plugins/borderStyle.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/borderStyle'>;
}
declare module 'tailwindcss/lib/plugins/borderWidth.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/borderWidth'>;
}
declare module 'tailwindcss/lib/plugins/boxShadow.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/boxShadow'>;
}
declare module 'tailwindcss/lib/plugins/boxSizing.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/boxSizing'>;
}
declare module 'tailwindcss/lib/plugins/clear.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/clear'>;
}
declare module 'tailwindcss/lib/plugins/container.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/container'>;
}
declare module 'tailwindcss/lib/plugins/cursor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/cursor'>;
}
declare module 'tailwindcss/lib/plugins/display.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/display'>;
}
declare module 'tailwindcss/lib/plugins/divideColor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/divideColor'>;
}
declare module 'tailwindcss/lib/plugins/divideOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/divideOpacity'>;
}
declare module 'tailwindcss/lib/plugins/divideWidth.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/divideWidth'>;
}
declare module 'tailwindcss/lib/plugins/fill.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/fill'>;
}
declare module 'tailwindcss/lib/plugins/flex.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/flex'>;
}
declare module 'tailwindcss/lib/plugins/flexDirection.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/flexDirection'>;
}
declare module 'tailwindcss/lib/plugins/flexGrow.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/flexGrow'>;
}
declare module 'tailwindcss/lib/plugins/flexShrink.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/flexShrink'>;
}
declare module 'tailwindcss/lib/plugins/flexWrap.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/flexWrap'>;
}
declare module 'tailwindcss/lib/plugins/float.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/float'>;
}
declare module 'tailwindcss/lib/plugins/fontFamily.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/fontFamily'>;
}
declare module 'tailwindcss/lib/plugins/fontSize.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/fontSize'>;
}
declare module 'tailwindcss/lib/plugins/fontSmoothing.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/fontSmoothing'>;
}
declare module 'tailwindcss/lib/plugins/fontStyle.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/fontStyle'>;
}
declare module 'tailwindcss/lib/plugins/fontWeight.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/fontWeight'>;
}
declare module 'tailwindcss/lib/plugins/gap.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gap'>;
}
declare module 'tailwindcss/lib/plugins/gridAutoFlow.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridAutoFlow'>;
}
declare module 'tailwindcss/lib/plugins/gridColumn.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridColumn'>;
}
declare module 'tailwindcss/lib/plugins/gridColumnEnd.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridColumnEnd'>;
}
declare module 'tailwindcss/lib/plugins/gridColumnStart.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridColumnStart'>;
}
declare module 'tailwindcss/lib/plugins/gridRow.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridRow'>;
}
declare module 'tailwindcss/lib/plugins/gridRowEnd.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridRowEnd'>;
}
declare module 'tailwindcss/lib/plugins/gridRowStart.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridRowStart'>;
}
declare module 'tailwindcss/lib/plugins/gridTemplateColumns.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridTemplateColumns'>;
}
declare module 'tailwindcss/lib/plugins/gridTemplateRows.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridTemplateRows'>;
}
declare module 'tailwindcss/lib/plugins/height.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/height'>;
}
declare module 'tailwindcss/lib/plugins/inset.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/inset'>;
}
declare module 'tailwindcss/lib/plugins/justifyContent.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/justifyContent'>;
}
declare module 'tailwindcss/lib/plugins/letterSpacing.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/letterSpacing'>;
}
declare module 'tailwindcss/lib/plugins/lineHeight.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/lineHeight'>;
}
declare module 'tailwindcss/lib/plugins/listStylePosition.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/listStylePosition'>;
}
declare module 'tailwindcss/lib/plugins/listStyleType.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/listStyleType'>;
}
declare module 'tailwindcss/lib/plugins/margin.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/margin'>;
}
declare module 'tailwindcss/lib/plugins/maxHeight.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/maxHeight'>;
}
declare module 'tailwindcss/lib/plugins/maxWidth.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/maxWidth'>;
}
declare module 'tailwindcss/lib/plugins/minHeight.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/minHeight'>;
}
declare module 'tailwindcss/lib/plugins/minWidth.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/minWidth'>;
}
declare module 'tailwindcss/lib/plugins/objectFit.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/objectFit'>;
}
declare module 'tailwindcss/lib/plugins/objectPosition.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/objectPosition'>;
}
declare module 'tailwindcss/lib/plugins/opacity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/opacity'>;
}
declare module 'tailwindcss/lib/plugins/order.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/order'>;
}
declare module 'tailwindcss/lib/plugins/outline.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/outline'>;
}
declare module 'tailwindcss/lib/plugins/overflow.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/overflow'>;
}
declare module 'tailwindcss/lib/plugins/padding.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/padding'>;
}
declare module 'tailwindcss/lib/plugins/placeholderColor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/placeholderColor'>;
}
declare module 'tailwindcss/lib/plugins/placeholderOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/placeholderOpacity'>;
}
declare module 'tailwindcss/lib/plugins/pointerEvents.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/pointerEvents'>;
}
declare module 'tailwindcss/lib/plugins/position.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/position'>;
}
declare module 'tailwindcss/lib/plugins/preflight.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/preflight'>;
}
declare module 'tailwindcss/lib/plugins/resize.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/resize'>;
}
declare module 'tailwindcss/lib/plugins/rotate.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/rotate'>;
}
declare module 'tailwindcss/lib/plugins/scale.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/scale'>;
}
declare module 'tailwindcss/lib/plugins/skew.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/skew'>;
}
declare module 'tailwindcss/lib/plugins/space.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/space'>;
}
declare module 'tailwindcss/lib/plugins/stroke.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/stroke'>;
}
declare module 'tailwindcss/lib/plugins/strokeWidth.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/strokeWidth'>;
}
declare module 'tailwindcss/lib/plugins/tableLayout.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/tableLayout'>;
}
declare module 'tailwindcss/lib/plugins/textAlign.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/textAlign'>;
}
declare module 'tailwindcss/lib/plugins/textColor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/textColor'>;
}
declare module 'tailwindcss/lib/plugins/textDecoration.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/textDecoration'>;
}
declare module 'tailwindcss/lib/plugins/textOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/textOpacity'>;
}
declare module 'tailwindcss/lib/plugins/textTransform.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/textTransform'>;
}
declare module 'tailwindcss/lib/plugins/transform.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/transform'>;
}
declare module 'tailwindcss/lib/plugins/transformOrigin.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/transformOrigin'>;
}
declare module 'tailwindcss/lib/plugins/transitionDelay.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/transitionDelay'>;
}
declare module 'tailwindcss/lib/plugins/transitionDuration.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/transitionDuration'>;
}
declare module 'tailwindcss/lib/plugins/transitionProperty.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/transitionProperty'>;
}
declare module 'tailwindcss/lib/plugins/transitionTimingFunction.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/transitionTimingFunction'>;
}
declare module 'tailwindcss/lib/plugins/translate.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/translate'>;
}
declare module 'tailwindcss/lib/plugins/userSelect.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/userSelect'>;
}
declare module 'tailwindcss/lib/plugins/verticalAlign.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/verticalAlign'>;
}
declare module 'tailwindcss/lib/plugins/visibility.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/visibility'>;
}
declare module 'tailwindcss/lib/plugins/whitespace.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/whitespace'>;
}
declare module 'tailwindcss/lib/plugins/width.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/width'>;
}
declare module 'tailwindcss/lib/plugins/wordBreak.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/wordBreak'>;
}
declare module 'tailwindcss/lib/plugins/zIndex.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/zIndex'>;
}
declare module 'tailwindcss/lib/processTailwindFeatures.js' {
  declare module.exports: $Exports<'tailwindcss/lib/processTailwindFeatures'>;
}
declare module 'tailwindcss/lib/util/buildMediaQuery.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/buildMediaQuery'>;
}
declare module 'tailwindcss/lib/util/buildSelectorVariant.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/buildSelectorVariant'>;
}
declare module 'tailwindcss/lib/util/cloneNodes.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/cloneNodes'>;
}
declare module 'tailwindcss/lib/util/configurePlugins.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/configurePlugins'>;
}
declare module 'tailwindcss/lib/util/createPlugin.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/createPlugin'>;
}
declare module 'tailwindcss/lib/util/createUtilityPlugin.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/createUtilityPlugin'>;
}
declare module 'tailwindcss/lib/util/escapeClassName.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/escapeClassName'>;
}
declare module 'tailwindcss/lib/util/flattenColorPalette.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/flattenColorPalette'>;
}
declare module 'tailwindcss/lib/util/generateVariantFunction.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/generateVariantFunction'>;
}
declare module 'tailwindcss/lib/util/increaseSpecificity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/increaseSpecificity'>;
}
declare module 'tailwindcss/lib/util/negateValue.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/negateValue'>;
}
declare module 'tailwindcss/lib/util/parseObjectStyles.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/parseObjectStyles'>;
}
declare module 'tailwindcss/lib/util/prefixNegativeModifiers.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/prefixNegativeModifiers'>;
}
declare module 'tailwindcss/lib/util/prefixSelector.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/prefixSelector'>;
}
declare module 'tailwindcss/lib/util/processPlugins.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/processPlugins'>;
}
declare module 'tailwindcss/lib/util/resolveConfig.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/resolveConfig'>;
}
declare module 'tailwindcss/lib/util/responsive.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/responsive'>;
}
declare module 'tailwindcss/lib/util/withAlphaVariable.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/withAlphaVariable'>;
}
declare module 'tailwindcss/lib/util/wrapWithVariants.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/wrapWithVariants'>;
}
declare module 'tailwindcss/plugin.js' {
  declare module.exports: $Exports<'tailwindcss/plugin'>;
}
declare module 'tailwindcss/resolveConfig.js' {
  declare module.exports: $Exports<'tailwindcss/resolveConfig'>;
}
declare module 'tailwindcss/scripts/build.js' {
  declare module.exports: $Exports<'tailwindcss/scripts/build'>;
}
declare module 'tailwindcss/scripts/rebuildFixtures.js' {
  declare module.exports: $Exports<'tailwindcss/scripts/rebuildFixtures'>;
}
declare module 'tailwindcss/stubs/defaultConfig.stub.js' {
  declare module.exports: $Exports<'tailwindcss/stubs/defaultConfig.stub'>;
}
declare module 'tailwindcss/stubs/simpleConfig.stub.js' {
  declare module.exports: $Exports<'tailwindcss/stubs/simpleConfig.stub'>;
}
