// flow-typed signature: ac5b13684348b37e78a976a396867012
// flow-typed version: <<STUB>>/typeface-nunito-sans_v^0.0.72/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-nunito-sans'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-nunito-sans' {
  declare module.exports: any;
}
