// flow-typed signature: fdf2eb0eb9ff559bcf39342cf12057ad
// flow-typed version: <<STUB>>/unique-names-generator_v^4.2.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unique-names-generator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unique-names-generator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unique-names-generator/dist' {
  declare module.exports: any;
}

declare module 'unique-names-generator/dist/index.m' {
  declare module.exports: any;
}

declare module 'unique-names-generator/dist/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unique-names-generator/dist/index' {
  declare module.exports: $Exports<'unique-names-generator/dist'>;
}
declare module 'unique-names-generator/dist/index.js' {
  declare module.exports: $Exports<'unique-names-generator/dist'>;
}
declare module 'unique-names-generator/dist/index.m.js' {
  declare module.exports: $Exports<'unique-names-generator/dist/index.m'>;
}
declare module 'unique-names-generator/dist/index.umd.js' {
  declare module.exports: $Exports<'unique-names-generator/dist/index.umd'>;
}
