// flow-typed signature: 41e3fc468da5bbccf010f3a2cf7f8ecd
// flow-typed version: <<STUB>>/vue-router-multi-view_v^0.1.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-router-multi-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-router-multi-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-router-multi-view/build/rollup.config.base' {
  declare module.exports: any;
}

declare module 'vue-router-multi-view/build/rollup.config.browser' {
  declare module.exports: any;
}

declare module 'vue-router-multi-view/build/rollup.config.es' {
  declare module.exports: any;
}

declare module 'vue-router-multi-view/build/rollup.config.umd' {
  declare module.exports: any;
}

declare module 'vue-router-multi-view/dist/vue-router-multi-view.esm' {
  declare module.exports: any;
}

declare module 'vue-router-multi-view/dist/vue-router-multi-view.min' {
  declare module.exports: any;
}

declare module 'vue-router-multi-view/dist/vue-router-multi-view.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-router-multi-view/build/rollup.config.base.js' {
  declare module.exports: $Exports<'vue-router-multi-view/build/rollup.config.base'>;
}
declare module 'vue-router-multi-view/build/rollup.config.browser.js' {
  declare module.exports: $Exports<'vue-router-multi-view/build/rollup.config.browser'>;
}
declare module 'vue-router-multi-view/build/rollup.config.es.js' {
  declare module.exports: $Exports<'vue-router-multi-view/build/rollup.config.es'>;
}
declare module 'vue-router-multi-view/build/rollup.config.umd.js' {
  declare module.exports: $Exports<'vue-router-multi-view/build/rollup.config.umd'>;
}
declare module 'vue-router-multi-view/dist/vue-router-multi-view.esm.js' {
  declare module.exports: $Exports<'vue-router-multi-view/dist/vue-router-multi-view.esm'>;
}
declare module 'vue-router-multi-view/dist/vue-router-multi-view.min.js' {
  declare module.exports: $Exports<'vue-router-multi-view/dist/vue-router-multi-view.min'>;
}
declare module 'vue-router-multi-view/dist/vue-router-multi-view.umd.js' {
  declare module.exports: $Exports<'vue-router-multi-view/dist/vue-router-multi-view.umd'>;
}
