// flow-typed signature: fab175653cf4100cc0e4c1823120afa2
// flow-typed version: <<STUB>>/vue-modal-dialogs_v^3.0.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-modal-dialogs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-modal-dialogs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-modal-dialogs/dist/vue-modal-dialogs.cjs' {
  declare module.exports: any;
}

declare module 'vue-modal-dialogs/dist/vue-modal-dialogs.esm' {
  declare module.exports: any;
}

declare module 'vue-modal-dialogs/src/create' {
  declare module.exports: any;
}

declare module 'vue-modal-dialogs/src' {
  declare module.exports: any;
}

declare module 'vue-modal-dialogs/src/utils' {
  declare module.exports: any;
}

declare module 'vue-modal-dialogs/src/wrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-modal-dialogs/dist/vue-modal-dialogs.cjs.js' {
  declare module.exports: $Exports<'vue-modal-dialogs/dist/vue-modal-dialogs.cjs'>;
}
declare module 'vue-modal-dialogs/dist/vue-modal-dialogs.esm.js' {
  declare module.exports: $Exports<'vue-modal-dialogs/dist/vue-modal-dialogs.esm'>;
}
declare module 'vue-modal-dialogs/src/create.js' {
  declare module.exports: $Exports<'vue-modal-dialogs/src/create'>;
}
declare module 'vue-modal-dialogs/src/index' {
  declare module.exports: $Exports<'vue-modal-dialogs/src'>;
}
declare module 'vue-modal-dialogs/src/index.js' {
  declare module.exports: $Exports<'vue-modal-dialogs/src'>;
}
declare module 'vue-modal-dialogs/src/utils.js' {
  declare module.exports: $Exports<'vue-modal-dialogs/src/utils'>;
}
declare module 'vue-modal-dialogs/src/wrapper.js' {
  declare module.exports: $Exports<'vue-modal-dialogs/src/wrapper'>;
}
