// flow-typed signature: 927946b4840f4ac8f1515863dc1426fc
// flow-typed version: <<STUB>>/vue-clipboard2_v^0.3.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-clipboard2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-clipboard2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-clipboard2/browserify-me' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/dist/vue-clipboard' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/dist/vue-clipboard.min' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/vue-clipboard' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-clipboard2/browserify-me.js' {
  declare module.exports: $Exports<'vue-clipboard2/browserify-me'>;
}
declare module 'vue-clipboard2/dist/vue-clipboard.js' {
  declare module.exports: $Exports<'vue-clipboard2/dist/vue-clipboard'>;
}
declare module 'vue-clipboard2/dist/vue-clipboard.min.js' {
  declare module.exports: $Exports<'vue-clipboard2/dist/vue-clipboard.min'>;
}
declare module 'vue-clipboard2/vue-clipboard.js' {
  declare module.exports: $Exports<'vue-clipboard2/vue-clipboard'>;
}
