// flow-typed signature: 14c215a86baf6607e002e589b7ef6164
// flow-typed version: <<STUB>>/vue-socket.io_v^3.0.9/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-socket.io'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-socket.io' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-socket.io/dist/vue-socketio' {
  declare module.exports: any;
}

declare module 'vue-socket.io/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-socket.io/dist/vue-socketio.js' {
  declare module.exports: $Exports<'vue-socket.io/dist/vue-socketio'>;
}
declare module 'vue-socket.io/webpack.config.js' {
  declare module.exports: $Exports<'vue-socket.io/webpack.config'>;
}
