// flow-typed signature: 516b4231d45b30d6e24e33ea3fb9a407
// flow-typed version: <<STUB>>/vue-cli-plugin-s3-deploy_v^4.0.0-rc3/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-cli-plugin-s3-deploy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-cli-plugin-s3-deploy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-cli-plugin-s3-deploy/bucket' {
  declare module.exports: any;
}

declare module 'vue-cli-plugin-s3-deploy/configuration' {
  declare module.exports: any;
}

declare module 'vue-cli-plugin-s3-deploy/deployer' {
  declare module.exports: any;
}

declare module 'vue-cli-plugin-s3-deploy/generator' {
  declare module.exports: any;
}

declare module 'vue-cli-plugin-s3-deploy/prompts' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-cli-plugin-s3-deploy/bucket.js' {
  declare module.exports: $Exports<'vue-cli-plugin-s3-deploy/bucket'>;
}
declare module 'vue-cli-plugin-s3-deploy/configuration.js' {
  declare module.exports: $Exports<'vue-cli-plugin-s3-deploy/configuration'>;
}
declare module 'vue-cli-plugin-s3-deploy/deployer.js' {
  declare module.exports: $Exports<'vue-cli-plugin-s3-deploy/deployer'>;
}
declare module 'vue-cli-plugin-s3-deploy/generator.js' {
  declare module.exports: $Exports<'vue-cli-plugin-s3-deploy/generator'>;
}
declare module 'vue-cli-plugin-s3-deploy/index' {
  declare module.exports: $Exports<'vue-cli-plugin-s3-deploy'>;
}
declare module 'vue-cli-plugin-s3-deploy/index.js' {
  declare module.exports: $Exports<'vue-cli-plugin-s3-deploy'>;
}
declare module 'vue-cli-plugin-s3-deploy/prompts.js' {
  declare module.exports: $Exports<'vue-cli-plugin-s3-deploy/prompts'>;
}
