// flow-typed signature: 7355cdf8688e96b03d8a21a29bafab2c
// flow-typed version: <<STUB>>/vue-burger-menu_v^2.0.5/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-burger-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-burger-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-burger-menu/dist/vue-burger-menu.common' {
  declare module.exports: any;
}

declare module 'vue-burger-menu/dist/vue-burger-menu.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-burger-menu/dist/vue-burger-menu.common.js' {
  declare module.exports: $Exports<'vue-burger-menu/dist/vue-burger-menu.common'>;
}
declare module 'vue-burger-menu/dist/vue-burger-menu.umd.js' {
  declare module.exports: $Exports<'vue-burger-menu/dist/vue-burger-menu.umd'>;
}
