// flow-typed signature: fd715b4c3a3b18842aeff310f56e7241
// flow-typed version: <<STUB>>/vue-docgen-loader_v^1.5.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-docgen-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-docgen-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-docgen-loader/lib' {
  declare module.exports: any;
}

declare module 'vue-docgen-loader/lib/inject' {
  declare module.exports: any;
}

declare module 'vue-docgen-loader/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-docgen-loader/lib/index' {
  declare module.exports: $Exports<'vue-docgen-loader/lib'>;
}
declare module 'vue-docgen-loader/lib/index.js' {
  declare module.exports: $Exports<'vue-docgen-loader/lib'>;
}
declare module 'vue-docgen-loader/lib/inject.js' {
  declare module.exports: $Exports<'vue-docgen-loader/lib/inject'>;
}
declare module 'vue-docgen-loader/lib/utils.js' {
  declare module.exports: $Exports<'vue-docgen-loader/lib/utils'>;
}
