// flow-typed signature: b669196c319a7303a2bcc2e66a329e74
// flow-typed version: <<STUB>>/vue-browser-acl_v^0.13.5/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-browser-acl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-browser-acl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-browser-acl/dist/vue-browser-acl.common' {
  declare module.exports: any;
}

declare module 'vue-browser-acl/dist/vue-browser-acl.esm' {
  declare module.exports: any;
}

declare module 'vue-browser-acl/dist/vue-browser-acl.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-browser-acl/dist/vue-browser-acl.common.js' {
  declare module.exports: $Exports<'vue-browser-acl/dist/vue-browser-acl.common'>;
}
declare module 'vue-browser-acl/dist/vue-browser-acl.esm.js' {
  declare module.exports: $Exports<'vue-browser-acl/dist/vue-browser-acl.esm'>;
}
declare module 'vue-browser-acl/dist/vue-browser-acl.umd.js' {
  declare module.exports: $Exports<'vue-browser-acl/dist/vue-browser-acl.umd'>;
}
