// flow-typed signature: ff80adb2627ba89708bb4eea6656ae22
// flow-typed version: <<STUB>>/vue-moment_v^4.1.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-moment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-moment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-moment/dist/vue-moment.cjs' {
  declare module.exports: any;
}

declare module 'vue-moment/dist/vue-moment.es' {
  declare module.exports: any;
}

declare module 'vue-moment/dist/vue-moment' {
  declare module.exports: any;
}

declare module 'vue-moment/dist/vue-moment.min' {
  declare module.exports: any;
}

declare module 'vue-moment/tests/vue-moment.spec' {
  declare module.exports: any;
}

declare module 'vue-moment/vue-moment' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-moment/dist/vue-moment.cjs.js' {
  declare module.exports: $Exports<'vue-moment/dist/vue-moment.cjs'>;
}
declare module 'vue-moment/dist/vue-moment.es.js' {
  declare module.exports: $Exports<'vue-moment/dist/vue-moment.es'>;
}
declare module 'vue-moment/dist/vue-moment.js' {
  declare module.exports: $Exports<'vue-moment/dist/vue-moment'>;
}
declare module 'vue-moment/dist/vue-moment.min.js' {
  declare module.exports: $Exports<'vue-moment/dist/vue-moment.min'>;
}
declare module 'vue-moment/tests/vue-moment.spec.js' {
  declare module.exports: $Exports<'vue-moment/tests/vue-moment.spec'>;
}
declare module 'vue-moment/vue-moment.js' {
  declare module.exports: $Exports<'vue-moment/vue-moment'>;
}
