// flow-typed signature: 9de1440bb2c4d65f90d6fcff18d0422d
// flow-typed version: <<STUB>>/vue-i18n_v^8.16.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-i18n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-i18n' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-i18n/decls/i18n' {
  declare module.exports: any;
}

declare module 'vue-i18n/decls/module' {
  declare module.exports: any;
}

declare module 'vue-i18n/dist/vue-i18n.common' {
  declare module.exports: any;
}

declare module 'vue-i18n/dist/vue-i18n.esm.browser' {
  declare module.exports: any;
}

declare module 'vue-i18n/dist/vue-i18n.esm.browser.min' {
  declare module.exports: any;
}

declare module 'vue-i18n/dist/vue-i18n.esm' {
  declare module.exports: any;
}

declare module 'vue-i18n/dist/vue-i18n' {
  declare module.exports: any;
}

declare module 'vue-i18n/dist/vue-i18n.min' {
  declare module.exports: any;
}

declare module 'vue-i18n/src/components/interpolation' {
  declare module.exports: any;
}

declare module 'vue-i18n/src/components/number' {
  declare module.exports: any;
}

declare module 'vue-i18n/src/directive' {
  declare module.exports: any;
}

declare module 'vue-i18n/src/extend' {
  declare module.exports: any;
}

declare module 'vue-i18n/src/format' {
  declare module.exports: any;
}

declare module 'vue-i18n/src' {
  declare module.exports: any;
}

declare module 'vue-i18n/src/install' {
  declare module.exports: any;
}

declare module 'vue-i18n/src/mixin' {
  declare module.exports: any;
}

declare module 'vue-i18n/src/path' {
  declare module.exports: any;
}

declare module 'vue-i18n/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-i18n/decls/i18n.js' {
  declare module.exports: $Exports<'vue-i18n/decls/i18n'>;
}
declare module 'vue-i18n/decls/module.js' {
  declare module.exports: $Exports<'vue-i18n/decls/module'>;
}
declare module 'vue-i18n/dist/vue-i18n.common.js' {
  declare module.exports: $Exports<'vue-i18n/dist/vue-i18n.common'>;
}
declare module 'vue-i18n/dist/vue-i18n.esm.browser.js' {
  declare module.exports: $Exports<'vue-i18n/dist/vue-i18n.esm.browser'>;
}
declare module 'vue-i18n/dist/vue-i18n.esm.browser.min.js' {
  declare module.exports: $Exports<'vue-i18n/dist/vue-i18n.esm.browser.min'>;
}
declare module 'vue-i18n/dist/vue-i18n.esm.js' {
  declare module.exports: $Exports<'vue-i18n/dist/vue-i18n.esm'>;
}
declare module 'vue-i18n/dist/vue-i18n.js' {
  declare module.exports: $Exports<'vue-i18n/dist/vue-i18n'>;
}
declare module 'vue-i18n/dist/vue-i18n.min.js' {
  declare module.exports: $Exports<'vue-i18n/dist/vue-i18n.min'>;
}
declare module 'vue-i18n/src/components/interpolation.js' {
  declare module.exports: $Exports<'vue-i18n/src/components/interpolation'>;
}
declare module 'vue-i18n/src/components/number.js' {
  declare module.exports: $Exports<'vue-i18n/src/components/number'>;
}
declare module 'vue-i18n/src/directive.js' {
  declare module.exports: $Exports<'vue-i18n/src/directive'>;
}
declare module 'vue-i18n/src/extend.js' {
  declare module.exports: $Exports<'vue-i18n/src/extend'>;
}
declare module 'vue-i18n/src/format.js' {
  declare module.exports: $Exports<'vue-i18n/src/format'>;
}
declare module 'vue-i18n/src/index' {
  declare module.exports: $Exports<'vue-i18n/src'>;
}
declare module 'vue-i18n/src/index.js' {
  declare module.exports: $Exports<'vue-i18n/src'>;
}
declare module 'vue-i18n/src/install.js' {
  declare module.exports: $Exports<'vue-i18n/src/install'>;
}
declare module 'vue-i18n/src/mixin.js' {
  declare module.exports: $Exports<'vue-i18n/src/mixin'>;
}
declare module 'vue-i18n/src/path.js' {
  declare module.exports: $Exports<'vue-i18n/src/path'>;
}
declare module 'vue-i18n/src/util.js' {
  declare module.exports: $Exports<'vue-i18n/src/util'>;
}
