// flow-typed signature: 5323679ff3feb5025a5ee2d22a235dbe
// flow-typed version: <<STUB>>/vue-cookies_v^1.7.2/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-cookies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-cookies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-cookies/vue-cookies' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-cookies/vue-cookies.js' {
  declare module.exports: $Exports<'vue-cookies/vue-cookies'>;
}
