// flow-typed signature: 92b3501b5e7f7a3780841a7c3789200f
// flow-typed version: <<STUB>>/vue-numeral-filter_v^1.1.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-numeral-filter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-numeral-filter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-numeral-filter/dist/vue-numeral-filter.es' {
  declare module.exports: any;
}

declare module 'vue-numeral-filter/dist/vue-numeral-filter.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-numeral-filter/dist/vue-numeral-filter.es.js' {
  declare module.exports: $Exports<'vue-numeral-filter/dist/vue-numeral-filter.es'>;
}
declare module 'vue-numeral-filter/dist/vue-numeral-filter.min.js' {
  declare module.exports: $Exports<'vue-numeral-filter/dist/vue-numeral-filter.min'>;
}
