// flow-typed signature: 44eebd10bc83f010bd3d2689b3d0ccca
// flow-typed version: <<STUB>>/vue-undo-redo-stack_v^1.0.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-undo-redo-stack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-undo-redo-stack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'vue-undo-redo-stack/index' {
  declare module.exports: $Exports<'vue-undo-redo-stack'>;
}
declare module 'vue-undo-redo-stack/index.js' {
  declare module.exports: $Exports<'vue-undo-redo-stack'>;
}
