// flow-typed signature: 4f2ecf6e71626480a6a0faf9000d9469
// flow-typed version: <<STUB>>/vue-timers_v^2.0.4/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-timers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-timers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-timers/dist/vue-timers.esm' {
  declare module.exports: any;
}

declare module 'vue-timers/dist/vue-timers.umd' {
  declare module.exports: any;
}

declare module 'vue-timers/index.min' {
  declare module.exports: any;
}

declare module 'vue-timers/mixin' {
  declare module.exports: any;
}

declare module 'vue-timers/rollup.config' {
  declare module.exports: any;
}

declare module 'vue-timers/test/index.spec' {
  declare module.exports: any;
}

declare module 'vue-timers/test/mixins.isSwitchTab.spec' {
  declare module.exports: any;
}

declare module 'vue-timers/test/mixins.spec' {
  declare module.exports: any;
}

declare module 'vue-timers/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-timers/dist/vue-timers.esm.js' {
  declare module.exports: $Exports<'vue-timers/dist/vue-timers.esm'>;
}
declare module 'vue-timers/dist/vue-timers.umd.js' {
  declare module.exports: $Exports<'vue-timers/dist/vue-timers.umd'>;
}
declare module 'vue-timers/index' {
  declare module.exports: $Exports<'vue-timers'>;
}
declare module 'vue-timers/index.js' {
  declare module.exports: $Exports<'vue-timers'>;
}
declare module 'vue-timers/index.min.js' {
  declare module.exports: $Exports<'vue-timers/index.min'>;
}
declare module 'vue-timers/mixin.js' {
  declare module.exports: $Exports<'vue-timers/mixin'>;
}
declare module 'vue-timers/rollup.config.js' {
  declare module.exports: $Exports<'vue-timers/rollup.config'>;
}
declare module 'vue-timers/test/index.spec.js' {
  declare module.exports: $Exports<'vue-timers/test/index.spec'>;
}
declare module 'vue-timers/test/mixins.isSwitchTab.spec.js' {
  declare module.exports: $Exports<'vue-timers/test/mixins.isSwitchTab.spec'>;
}
declare module 'vue-timers/test/mixins.spec.js' {
  declare module.exports: $Exports<'vue-timers/test/mixins.spec'>;
}
declare module 'vue-timers/utils.js' {
  declare module.exports: $Exports<'vue-timers/utils'>;
}
