// flow-typed signature: ebbd82783c3c5fd3c673a1d54bf33c06
// flow-typed version: <<STUB>>/vue-select_v^3.4.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-select/dist/vue-select' {
  declare module.exports: any;
}

declare module 'vue-select/src/components/childComponents' {
  declare module.exports: any;
}

declare module 'vue-select/src' {
  declare module.exports: any;
}

declare module 'vue-select/src/mixins/ajax' {
  declare module.exports: any;
}

declare module 'vue-select/src/mixins' {
  declare module.exports: any;
}

declare module 'vue-select/src/mixins/pointerScroll' {
  declare module.exports: any;
}

declare module 'vue-select/src/mixins/typeAheadPointer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-select/dist/vue-select.js' {
  declare module.exports: $Exports<'vue-select/dist/vue-select'>;
}
declare module 'vue-select/src/components/childComponents.js' {
  declare module.exports: $Exports<'vue-select/src/components/childComponents'>;
}
declare module 'vue-select/src/index' {
  declare module.exports: $Exports<'vue-select/src'>;
}
declare module 'vue-select/src/index.js' {
  declare module.exports: $Exports<'vue-select/src'>;
}
declare module 'vue-select/src/mixins/ajax.js' {
  declare module.exports: $Exports<'vue-select/src/mixins/ajax'>;
}
declare module 'vue-select/src/mixins/index' {
  declare module.exports: $Exports<'vue-select/src/mixins'>;
}
declare module 'vue-select/src/mixins/index.js' {
  declare module.exports: $Exports<'vue-select/src/mixins'>;
}
declare module 'vue-select/src/mixins/pointerScroll.js' {
  declare module.exports: $Exports<'vue-select/src/mixins/pointerScroll'>;
}
declare module 'vue-select/src/mixins/typeAheadPointer.js' {
  declare module.exports: $Exports<'vue-select/src/mixins/typeAheadPointer'>;
}
