// flow-typed signature: 9ca26243de87fe4417bc6dd009231643
// flow-typed version: <<STUB>>/vue-cli-plugin-cypress-experimental_v~1.1.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-cli-plugin-cypress-experimental'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-cli-plugin-cypress-experimental' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-cli-plugin-cypress-experimental/generator' {
  declare module.exports: any;
}

declare module 'vue-cli-plugin-cypress-experimental/generator/template/tests/_eslintrc' {
  declare module.exports: any;
}

declare module 'vue-cli-plugin-cypress-experimental/generator/template/tests/components/Greetings.spec' {
  declare module.exports: any;
}

declare module 'vue-cli-plugin-cypress-experimental/generator/template/tests/plugins' {
  declare module.exports: any;
}

declare module 'vue-cli-plugin-cypress-experimental/generator/template/tests/support/commands' {
  declare module.exports: any;
}

declare module 'vue-cli-plugin-cypress-experimental/generator/template/tests/support' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-cli-plugin-cypress-experimental/generator/index' {
  declare module.exports: $Exports<'vue-cli-plugin-cypress-experimental/generator'>;
}
declare module 'vue-cli-plugin-cypress-experimental/generator/index.js' {
  declare module.exports: $Exports<'vue-cli-plugin-cypress-experimental/generator'>;
}
declare module 'vue-cli-plugin-cypress-experimental/generator/template/tests/_eslintrc.js' {
  declare module.exports: $Exports<'vue-cli-plugin-cypress-experimental/generator/template/tests/_eslintrc'>;
}
declare module 'vue-cli-plugin-cypress-experimental/generator/template/tests/components/Greetings.spec.js' {
  declare module.exports: $Exports<'vue-cli-plugin-cypress-experimental/generator/template/tests/components/Greetings.spec'>;
}
declare module 'vue-cli-plugin-cypress-experimental/generator/template/tests/plugins/index' {
  declare module.exports: $Exports<'vue-cli-plugin-cypress-experimental/generator/template/tests/plugins'>;
}
declare module 'vue-cli-plugin-cypress-experimental/generator/template/tests/plugins/index.js' {
  declare module.exports: $Exports<'vue-cli-plugin-cypress-experimental/generator/template/tests/plugins'>;
}
declare module 'vue-cli-plugin-cypress-experimental/generator/template/tests/support/commands.js' {
  declare module.exports: $Exports<'vue-cli-plugin-cypress-experimental/generator/template/tests/support/commands'>;
}
declare module 'vue-cli-plugin-cypress-experimental/generator/template/tests/support/index' {
  declare module.exports: $Exports<'vue-cli-plugin-cypress-experimental/generator/template/tests/support'>;
}
declare module 'vue-cli-plugin-cypress-experimental/generator/template/tests/support/index.js' {
  declare module.exports: $Exports<'vue-cli-plugin-cypress-experimental/generator/template/tests/support'>;
}
declare module 'vue-cli-plugin-cypress-experimental/index' {
  declare module.exports: $Exports<'vue-cli-plugin-cypress-experimental'>;
}
declare module 'vue-cli-plugin-cypress-experimental/index.js' {
  declare module.exports: $Exports<'vue-cli-plugin-cypress-experimental'>;
}
