// flow-typed signature: 6dbaa4aec77124d8f056796184152327
// flow-typed version: <<STUB>>/vue-autosuggest_v^2.0.4/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-autosuggest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-autosuggest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-autosuggest/dist/vue-autosuggest.esm' {
  declare module.exports: any;
}

declare module 'vue-autosuggest/dist/vue-autosuggest' {
  declare module.exports: any;
}

declare module 'vue-autosuggest/src/parts/DefaultSection' {
  declare module.exports: any;
}

declare module 'vue-autosuggest/src/stories' {
  declare module.exports: any;
}

declare module 'vue-autosuggest/src/utils' {
  declare module.exports: any;
}

declare module 'vue-autosuggest/src/vue-autosuggest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-autosuggest/dist/vue-autosuggest.esm.js' {
  declare module.exports: $Exports<'vue-autosuggest/dist/vue-autosuggest.esm'>;
}
declare module 'vue-autosuggest/dist/vue-autosuggest.js' {
  declare module.exports: $Exports<'vue-autosuggest/dist/vue-autosuggest'>;
}
declare module 'vue-autosuggest/src/parts/DefaultSection.js' {
  declare module.exports: $Exports<'vue-autosuggest/src/parts/DefaultSection'>;
}
declare module 'vue-autosuggest/src/stories/index' {
  declare module.exports: $Exports<'vue-autosuggest/src/stories'>;
}
declare module 'vue-autosuggest/src/stories/index.js' {
  declare module.exports: $Exports<'vue-autosuggest/src/stories'>;
}
declare module 'vue-autosuggest/src/utils.js' {
  declare module.exports: $Exports<'vue-autosuggest/src/utils'>;
}
declare module 'vue-autosuggest/src/vue-autosuggest.js' {
  declare module.exports: $Exports<'vue-autosuggest/src/vue-autosuggest'>;
}
