// flow-typed signature: c69ebe4df667a215d879b194445b58d6
// flow-typed version: <<STUB>>/vue-js-popover_v^1.1.8/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-js-popover'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-js-popover' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-js-popover/dist' {
  declare module.exports: any;
}

declare module 'vue-js-popover/src/bus' {
  declare module.exports: any;
}

declare module 'vue-js-popover/src' {
  declare module.exports: any;
}

declare module 'vue-js-popover/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-js-popover/dist/index' {
  declare module.exports: $Exports<'vue-js-popover/dist'>;
}
declare module 'vue-js-popover/dist/index.js' {
  declare module.exports: $Exports<'vue-js-popover/dist'>;
}
declare module 'vue-js-popover/src/bus.js' {
  declare module.exports: $Exports<'vue-js-popover/src/bus'>;
}
declare module 'vue-js-popover/src/index' {
  declare module.exports: $Exports<'vue-js-popover/src'>;
}
declare module 'vue-js-popover/src/index.js' {
  declare module.exports: $Exports<'vue-js-popover/src'>;
}
declare module 'vue-js-popover/webpack.config.js' {
  declare module.exports: $Exports<'vue-js-popover/webpack.config'>;
}
