// flow-typed signature: fb426966bb88c4323cecc382baa132f4
// flow-typed version: <<STUB>>/vue-responsive_v^1.1.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-responsive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-responsive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-responsive/dist/Vue-Responsive' {
  declare module.exports: any;
}

declare module 'vue-responsive/dist/Vue-Responsive.min' {
  declare module.exports: any;
}

declare module 'vue-responsive/src' {
  declare module.exports: any;
}

declare module 'vue-responsive/src/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-responsive/dist/Vue-Responsive.js' {
  declare module.exports: $Exports<'vue-responsive/dist/Vue-Responsive'>;
}
declare module 'vue-responsive/dist/Vue-Responsive.min.js' {
  declare module.exports: $Exports<'vue-responsive/dist/Vue-Responsive.min'>;
}
declare module 'vue-responsive/src/index' {
  declare module.exports: $Exports<'vue-responsive/src'>;
}
declare module 'vue-responsive/src/index.js' {
  declare module.exports: $Exports<'vue-responsive/src'>;
}
declare module 'vue-responsive/src/main.js' {
  declare module.exports: $Exports<'vue-responsive/src/main'>;
}
