// flow-typed signature: 35ac17f56e9633d99a281523e4fdc36d
// flow-typed version: <<STUB>>/vue-cron-editor-buefy_v^0.1.15/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-cron-editor-buefy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-cron-editor-buefy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-cron-editor-buefy/dist/vue-cron-editor-buefy.common' {
  declare module.exports: any;
}

declare module 'vue-cron-editor-buefy/dist/vue-cron-editor-buefy.umd' {
  declare module.exports: any;
}

declare module 'vue-cron-editor-buefy/dist/vue-cron-editor-buefy.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-cron-editor-buefy/dist/vue-cron-editor-buefy.common.js' {
  declare module.exports: $Exports<'vue-cron-editor-buefy/dist/vue-cron-editor-buefy.common'>;
}
declare module 'vue-cron-editor-buefy/dist/vue-cron-editor-buefy.umd.js' {
  declare module.exports: $Exports<'vue-cron-editor-buefy/dist/vue-cron-editor-buefy.umd'>;
}
declare module 'vue-cron-editor-buefy/dist/vue-cron-editor-buefy.umd.min.js' {
  declare module.exports: $Exports<'vue-cron-editor-buefy/dist/vue-cron-editor-buefy.umd.min'>;
}
