// flow-typed signature: 97a0790ae66823ba6579c8a708b5abc6
// flow-typed version: <<STUB>>/vue-range-slider_v^0.6.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-range-slider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-range-slider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-range-slider/dist/vue-range-slider.cjs' {
  declare module.exports: any;
}

declare module 'vue-range-slider/dist/vue-range-slider' {
  declare module.exports: any;
}

declare module 'vue-range-slider/dist/vue-range-slider.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-range-slider/dist/vue-range-slider.cjs.js' {
  declare module.exports: $Exports<'vue-range-slider/dist/vue-range-slider.cjs'>;
}
declare module 'vue-range-slider/dist/vue-range-slider.js' {
  declare module.exports: $Exports<'vue-range-slider/dist/vue-range-slider'>;
}
declare module 'vue-range-slider/dist/vue-range-slider.min.js' {
  declare module.exports: $Exports<'vue-range-slider/dist/vue-range-slider.min'>;
}
