// flow-typed signature: 7ff3c3100a60a6df25bebbc63aa85995
// flow-typed version: <<STUB>>/vue-native-websocket_v^2.0.14/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-native-websocket'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-native-websocket' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-native-websocket/dist/build' {
  declare module.exports: any;
}

declare module 'vue-native-websocket/src/Emitter' {
  declare module.exports: any;
}

declare module 'vue-native-websocket/src/Main' {
  declare module.exports: any;
}

declare module 'vue-native-websocket/src/Observer' {
  declare module.exports: any;
}

declare module 'vue-native-websocket/test/unit' {
  declare module.exports: any;
}

declare module 'vue-native-websocket/test/unit/karma.conf' {
  declare module.exports: any;
}

declare module 'vue-native-websocket/test/unit/specs/Emitter.spec' {
  declare module.exports: any;
}

declare module 'vue-native-websocket/test/unit/specs/Main.spec' {
  declare module.exports: any;
}

declare module 'vue-native-websocket/test/unit/specs/Observer.spec' {
  declare module.exports: any;
}

declare module 'vue-native-websocket/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-native-websocket/dist/build.js' {
  declare module.exports: $Exports<'vue-native-websocket/dist/build'>;
}
declare module 'vue-native-websocket/src/Emitter.js' {
  declare module.exports: $Exports<'vue-native-websocket/src/Emitter'>;
}
declare module 'vue-native-websocket/src/Main.js' {
  declare module.exports: $Exports<'vue-native-websocket/src/Main'>;
}
declare module 'vue-native-websocket/src/Observer.js' {
  declare module.exports: $Exports<'vue-native-websocket/src/Observer'>;
}
declare module 'vue-native-websocket/test/unit/index' {
  declare module.exports: $Exports<'vue-native-websocket/test/unit'>;
}
declare module 'vue-native-websocket/test/unit/index.js' {
  declare module.exports: $Exports<'vue-native-websocket/test/unit'>;
}
declare module 'vue-native-websocket/test/unit/karma.conf.js' {
  declare module.exports: $Exports<'vue-native-websocket/test/unit/karma.conf'>;
}
declare module 'vue-native-websocket/test/unit/specs/Emitter.spec.js' {
  declare module.exports: $Exports<'vue-native-websocket/test/unit/specs/Emitter.spec'>;
}
declare module 'vue-native-websocket/test/unit/specs/Main.spec.js' {
  declare module.exports: $Exports<'vue-native-websocket/test/unit/specs/Main.spec'>;
}
declare module 'vue-native-websocket/test/unit/specs/Observer.spec.js' {
  declare module.exports: $Exports<'vue-native-websocket/test/unit/specs/Observer.spec'>;
}
declare module 'vue-native-websocket/webpack.config.js' {
  declare module.exports: $Exports<'vue-native-websocket/webpack.config'>;
}
