// flow-typed signature: d0573417b86ff3d243668f74c1d10754
// flow-typed version: <<STUB>>/vue-docgen-api_v^4.15.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-docgen-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-docgen-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-docgen-api/dist/babel-parser' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/Documentation' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/main' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/parse-script' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/parse-template' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/parse' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/parseSFC' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/script-handlers/classDisplayNameHandler' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/script-handlers/classEventHandler' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/script-handlers/classMethodHandler' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/script-handlers/classPropHandler' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/script-handlers/componentHandler' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/script-handlers/displayNameHandler' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/script-handlers/eventHandler' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/script-handlers/extendsHandler' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/script-handlers' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/script-handlers/methodHandler' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/script-handlers/mixinsHandler' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/script-handlers/propHandler' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/script-handlers/slotHandler' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/template-handlers/eventHandler' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/template-handlers' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/template-handlers/propHandler' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/template-handlers/slotHandler' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/blockTags' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/cacher' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/cleanName' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/documentRequiredComponents' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/extractLeadingComment' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/getArgFromDecorator' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/getDefaultExample' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/getDocblock' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/getDoclets' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/getPropsFilter' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/getTemplateExpressionAST' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/getTypeFromAnnotation' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/isExportedAssignment' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/makePathResolver' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/matchRecursiveRegexp' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/recursiveResolveIEV' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/resolveAliases' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/resolveExportDeclaration' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/resolveExportedComponent' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/resolveIdentifier' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/resolveImmediatelyExported' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/resolvePathFrom' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/resolveRequired' {
  declare module.exports: any;
}

declare module 'vue-docgen-api/dist/utils/transformTagsIntoObject' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-docgen-api/dist/babel-parser.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/babel-parser'>;
}
declare module 'vue-docgen-api/dist/Documentation.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/Documentation'>;
}
declare module 'vue-docgen-api/dist/main.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/main'>;
}
declare module 'vue-docgen-api/dist/parse-script.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/parse-script'>;
}
declare module 'vue-docgen-api/dist/parse-template.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/parse-template'>;
}
declare module 'vue-docgen-api/dist/parse.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/parse'>;
}
declare module 'vue-docgen-api/dist/parseSFC.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/parseSFC'>;
}
declare module 'vue-docgen-api/dist/script-handlers/classDisplayNameHandler.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/script-handlers/classDisplayNameHandler'>;
}
declare module 'vue-docgen-api/dist/script-handlers/classEventHandler.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/script-handlers/classEventHandler'>;
}
declare module 'vue-docgen-api/dist/script-handlers/classMethodHandler.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/script-handlers/classMethodHandler'>;
}
declare module 'vue-docgen-api/dist/script-handlers/classPropHandler.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/script-handlers/classPropHandler'>;
}
declare module 'vue-docgen-api/dist/script-handlers/componentHandler.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/script-handlers/componentHandler'>;
}
declare module 'vue-docgen-api/dist/script-handlers/displayNameHandler.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/script-handlers/displayNameHandler'>;
}
declare module 'vue-docgen-api/dist/script-handlers/eventHandler.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/script-handlers/eventHandler'>;
}
declare module 'vue-docgen-api/dist/script-handlers/extendsHandler.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/script-handlers/extendsHandler'>;
}
declare module 'vue-docgen-api/dist/script-handlers/index' {
  declare module.exports: $Exports<'vue-docgen-api/dist/script-handlers'>;
}
declare module 'vue-docgen-api/dist/script-handlers/index.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/script-handlers'>;
}
declare module 'vue-docgen-api/dist/script-handlers/methodHandler.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/script-handlers/methodHandler'>;
}
declare module 'vue-docgen-api/dist/script-handlers/mixinsHandler.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/script-handlers/mixinsHandler'>;
}
declare module 'vue-docgen-api/dist/script-handlers/propHandler.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/script-handlers/propHandler'>;
}
declare module 'vue-docgen-api/dist/script-handlers/slotHandler.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/script-handlers/slotHandler'>;
}
declare module 'vue-docgen-api/dist/template-handlers/eventHandler.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/template-handlers/eventHandler'>;
}
declare module 'vue-docgen-api/dist/template-handlers/index' {
  declare module.exports: $Exports<'vue-docgen-api/dist/template-handlers'>;
}
declare module 'vue-docgen-api/dist/template-handlers/index.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/template-handlers'>;
}
declare module 'vue-docgen-api/dist/template-handlers/propHandler.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/template-handlers/propHandler'>;
}
declare module 'vue-docgen-api/dist/template-handlers/slotHandler.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/template-handlers/slotHandler'>;
}
declare module 'vue-docgen-api/dist/utils/blockTags.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/blockTags'>;
}
declare module 'vue-docgen-api/dist/utils/cacher.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/cacher'>;
}
declare module 'vue-docgen-api/dist/utils/cleanName.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/cleanName'>;
}
declare module 'vue-docgen-api/dist/utils/documentRequiredComponents.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/documentRequiredComponents'>;
}
declare module 'vue-docgen-api/dist/utils/extractLeadingComment.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/extractLeadingComment'>;
}
declare module 'vue-docgen-api/dist/utils/getArgFromDecorator.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/getArgFromDecorator'>;
}
declare module 'vue-docgen-api/dist/utils/getDefaultExample.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/getDefaultExample'>;
}
declare module 'vue-docgen-api/dist/utils/getDocblock.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/getDocblock'>;
}
declare module 'vue-docgen-api/dist/utils/getDoclets.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/getDoclets'>;
}
declare module 'vue-docgen-api/dist/utils/getPropsFilter.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/getPropsFilter'>;
}
declare module 'vue-docgen-api/dist/utils/getTemplateExpressionAST.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/getTemplateExpressionAST'>;
}
declare module 'vue-docgen-api/dist/utils/getTypeFromAnnotation.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/getTypeFromAnnotation'>;
}
declare module 'vue-docgen-api/dist/utils/isExportedAssignment.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/isExportedAssignment'>;
}
declare module 'vue-docgen-api/dist/utils/makePathResolver.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/makePathResolver'>;
}
declare module 'vue-docgen-api/dist/utils/matchRecursiveRegexp.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/matchRecursiveRegexp'>;
}
declare module 'vue-docgen-api/dist/utils/recursiveResolveIEV.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/recursiveResolveIEV'>;
}
declare module 'vue-docgen-api/dist/utils/resolveAliases.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/resolveAliases'>;
}
declare module 'vue-docgen-api/dist/utils/resolveExportDeclaration.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/resolveExportDeclaration'>;
}
declare module 'vue-docgen-api/dist/utils/resolveExportedComponent.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/resolveExportedComponent'>;
}
declare module 'vue-docgen-api/dist/utils/resolveIdentifier.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/resolveIdentifier'>;
}
declare module 'vue-docgen-api/dist/utils/resolveImmediatelyExported.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/resolveImmediatelyExported'>;
}
declare module 'vue-docgen-api/dist/utils/resolvePathFrom.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/resolvePathFrom'>;
}
declare module 'vue-docgen-api/dist/utils/resolveRequired.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/resolveRequired'>;
}
declare module 'vue-docgen-api/dist/utils/transformTagsIntoObject.js' {
  declare module.exports: $Exports<'vue-docgen-api/dist/utils/transformTagsIntoObject'>;
}
