// flow-typed signature: 8caf9a6a7b3625203e9890d8c2e8bd56
// flow-typed version: <<STUB>>/vue-mq_v^1.0.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-mq'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-mq' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-mq/dist/vue-mq.cjs' {
  declare module.exports: any;
}

declare module 'vue-mq/dist/vue-mq.es' {
  declare module.exports: any;
}

declare module 'vue-mq/dist/vue-mq' {
  declare module.exports: any;
}

declare module 'vue-mq/dist/vue-mq.min' {
  declare module.exports: any;
}

declare module 'vue-mq/examples/dist/main.b5301e32' {
  declare module.exports: any;
}

declare module 'vue-mq/examples/dist/vendors~main.7494fd97' {
  declare module.exports: any;
}

declare module 'vue-mq/examples' {
  declare module.exports: any;
}

declare module 'vue-mq/src/component' {
  declare module.exports: any;
}

declare module 'vue-mq/src/helpers' {
  declare module.exports: any;
}

declare module 'vue-mq/src' {
  declare module.exports: any;
}

declare module 'vue-mq/src/utils' {
  declare module.exports: any;
}

declare module 'vue-mq/test/setup' {
  declare module.exports: any;
}

declare module 'vue-mq/test/specs/helpers.bak' {
  declare module.exports: any;
}

declare module 'vue-mq/test/specs/helpers.spec' {
  declare module.exports: any;
}

declare module 'vue-mq/test/specs/index.bak' {
  declare module.exports: any;
}

declare module 'vue-mq/test/specs/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-mq/dist/vue-mq.cjs.js' {
  declare module.exports: $Exports<'vue-mq/dist/vue-mq.cjs'>;
}
declare module 'vue-mq/dist/vue-mq.es.js' {
  declare module.exports: $Exports<'vue-mq/dist/vue-mq.es'>;
}
declare module 'vue-mq/dist/vue-mq.js' {
  declare module.exports: $Exports<'vue-mq/dist/vue-mq'>;
}
declare module 'vue-mq/dist/vue-mq.min.js' {
  declare module.exports: $Exports<'vue-mq/dist/vue-mq.min'>;
}
declare module 'vue-mq/examples/dist/main.b5301e32.js' {
  declare module.exports: $Exports<'vue-mq/examples/dist/main.b5301e32'>;
}
declare module 'vue-mq/examples/dist/vendors~main.7494fd97.js' {
  declare module.exports: $Exports<'vue-mq/examples/dist/vendors~main.7494fd97'>;
}
declare module 'vue-mq/examples/index' {
  declare module.exports: $Exports<'vue-mq/examples'>;
}
declare module 'vue-mq/examples/index.js' {
  declare module.exports: $Exports<'vue-mq/examples'>;
}
declare module 'vue-mq/src/component.js' {
  declare module.exports: $Exports<'vue-mq/src/component'>;
}
declare module 'vue-mq/src/helpers.js' {
  declare module.exports: $Exports<'vue-mq/src/helpers'>;
}
declare module 'vue-mq/src/index' {
  declare module.exports: $Exports<'vue-mq/src'>;
}
declare module 'vue-mq/src/index.js' {
  declare module.exports: $Exports<'vue-mq/src'>;
}
declare module 'vue-mq/src/utils.js' {
  declare module.exports: $Exports<'vue-mq/src/utils'>;
}
declare module 'vue-mq/test/setup.js' {
  declare module.exports: $Exports<'vue-mq/test/setup'>;
}
declare module 'vue-mq/test/specs/helpers.bak.js' {
  declare module.exports: $Exports<'vue-mq/test/specs/helpers.bak'>;
}
declare module 'vue-mq/test/specs/helpers.spec.js' {
  declare module.exports: $Exports<'vue-mq/test/specs/helpers.spec'>;
}
declare module 'vue-mq/test/specs/index.bak.js' {
  declare module.exports: $Exports<'vue-mq/test/specs/index.bak'>;
}
declare module 'vue-mq/test/specs/index.spec.js' {
  declare module.exports: $Exports<'vue-mq/test/specs/index.spec'>;
}
