// flow-typed signature: 38b79e1420a855f80df0583cb65e5a49
// flow-typed version: <<STUB>>/vue-hotjar_v^1.1.2/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-hotjar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-hotjar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-hotjar/dist/vue-hotjar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-hotjar/dist/vue-hotjar.js' {
  declare module.exports: $Exports<'vue-hotjar/dist/vue-hotjar'>;
}
