// flow-typed signature: ae62f49cb54129c9a8703039db56dc38
// flow-typed version: <<STUB>>/vue-gtag_v^1.6.2/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-gtag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-gtag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-gtag/dist/vue-gtag.esm' {
  declare module.exports: any;
}

declare module 'vue-gtag/dist/vue-gtag' {
  declare module.exports: any;
}

declare module 'vue-gtag/dist/vue-gtag.umd' {
  declare module.exports: any;
}

declare module 'vue-gtag/dist/vue-gtag.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-gtag/dist/vue-gtag.esm.js' {
  declare module.exports: $Exports<'vue-gtag/dist/vue-gtag.esm'>;
}
declare module 'vue-gtag/dist/vue-gtag.js' {
  declare module.exports: $Exports<'vue-gtag/dist/vue-gtag'>;
}
declare module 'vue-gtag/dist/vue-gtag.umd.js' {
  declare module.exports: $Exports<'vue-gtag/dist/vue-gtag.umd'>;
}
declare module 'vue-gtag/dist/vue-gtag.umd.min.js' {
  declare module.exports: $Exports<'vue-gtag/dist/vue-gtag.umd.min'>;
}
