// flow-typed signature: 1b1e635d23f61a9d85e5e6b51f9b1fe3
// flow-typed version: <<STUB>>/vue-carousel_v^0.18.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-carousel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-carousel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-carousel/dist/vue-carousel.min' {
  declare module.exports: any;
}

declare module 'vue-carousel/docs/public/js/common' {
  declare module.exports: any;
}

declare module 'vue-carousel/docs/public/js/smooth-scroll.min' {
  declare module.exports: any;
}

declare module 'vue-carousel/docs/public/js/vue-carousel.min' {
  declare module.exports: any;
}

declare module 'vue-carousel/docs/public/js/vue' {
  declare module.exports: any;
}

declare module 'vue-carousel/docs/public/js/vue.min' {
  declare module.exports: any;
}

declare module 'vue-carousel/docs/themes/vue/source/js/common' {
  declare module.exports: any;
}

declare module 'vue-carousel/docs/themes/vue/source/js/smooth-scroll.min' {
  declare module.exports: any;
}

declare module 'vue-carousel/docs/themes/vue/source/js/vue-carousel.min' {
  declare module.exports: any;
}

declare module 'vue-carousel/docs/themes/vue/source/js/vue' {
  declare module.exports: any;
}

declare module 'vue-carousel/docs/themes/vue/source/js/vue.min' {
  declare module.exports: any;
}

declare module 'vue-carousel/play' {
  declare module.exports: any;
}

declare module 'vue-carousel/postcss.config' {
  declare module.exports: any;
}

declare module 'vue-carousel/src' {
  declare module.exports: any;
}

declare module 'vue-carousel/src/mixins/autoplay' {
  declare module.exports: any;
}

declare module 'vue-carousel/src/utils/debounce' {
  declare module.exports: any;
}

declare module 'vue-carousel/tests/client/components/carousel.spec' {
  declare module.exports: any;
}

declare module 'vue-carousel/tests/client/components/navigation.spec' {
  declare module.exports: any;
}

declare module 'vue-carousel/tests/client/components/pagination.spec' {
  declare module.exports: any;
}

declare module 'vue-carousel/tests/client/components/slide.spec' {
  declare module.exports: any;
}

declare module 'vue-carousel/tests/preprocessor' {
  declare module.exports: any;
}

declare module 'vue-carousel/webpack.common' {
  declare module.exports: any;
}

declare module 'vue-carousel/webpack.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-carousel/dist/vue-carousel.min.js' {
  declare module.exports: $Exports<'vue-carousel/dist/vue-carousel.min'>;
}
declare module 'vue-carousel/docs/public/js/common.js' {
  declare module.exports: $Exports<'vue-carousel/docs/public/js/common'>;
}
declare module 'vue-carousel/docs/public/js/smooth-scroll.min.js' {
  declare module.exports: $Exports<'vue-carousel/docs/public/js/smooth-scroll.min'>;
}
declare module 'vue-carousel/docs/public/js/vue-carousel.min.js' {
  declare module.exports: $Exports<'vue-carousel/docs/public/js/vue-carousel.min'>;
}
declare module 'vue-carousel/docs/public/js/vue.js' {
  declare module.exports: $Exports<'vue-carousel/docs/public/js/vue'>;
}
declare module 'vue-carousel/docs/public/js/vue.min.js' {
  declare module.exports: $Exports<'vue-carousel/docs/public/js/vue.min'>;
}
declare module 'vue-carousel/docs/themes/vue/source/js/common.js' {
  declare module.exports: $Exports<'vue-carousel/docs/themes/vue/source/js/common'>;
}
declare module 'vue-carousel/docs/themes/vue/source/js/smooth-scroll.min.js' {
  declare module.exports: $Exports<'vue-carousel/docs/themes/vue/source/js/smooth-scroll.min'>;
}
declare module 'vue-carousel/docs/themes/vue/source/js/vue-carousel.min.js' {
  declare module.exports: $Exports<'vue-carousel/docs/themes/vue/source/js/vue-carousel.min'>;
}
declare module 'vue-carousel/docs/themes/vue/source/js/vue.js' {
  declare module.exports: $Exports<'vue-carousel/docs/themes/vue/source/js/vue'>;
}
declare module 'vue-carousel/docs/themes/vue/source/js/vue.min.js' {
  declare module.exports: $Exports<'vue-carousel/docs/themes/vue/source/js/vue.min'>;
}
declare module 'vue-carousel/play/index' {
  declare module.exports: $Exports<'vue-carousel/play'>;
}
declare module 'vue-carousel/play/index.js' {
  declare module.exports: $Exports<'vue-carousel/play'>;
}
declare module 'vue-carousel/postcss.config.js' {
  declare module.exports: $Exports<'vue-carousel/postcss.config'>;
}
declare module 'vue-carousel/src/index' {
  declare module.exports: $Exports<'vue-carousel/src'>;
}
declare module 'vue-carousel/src/index.js' {
  declare module.exports: $Exports<'vue-carousel/src'>;
}
declare module 'vue-carousel/src/mixins/autoplay.js' {
  declare module.exports: $Exports<'vue-carousel/src/mixins/autoplay'>;
}
declare module 'vue-carousel/src/utils/debounce.js' {
  declare module.exports: $Exports<'vue-carousel/src/utils/debounce'>;
}
declare module 'vue-carousel/tests/client/components/carousel.spec.js' {
  declare module.exports: $Exports<'vue-carousel/tests/client/components/carousel.spec'>;
}
declare module 'vue-carousel/tests/client/components/navigation.spec.js' {
  declare module.exports: $Exports<'vue-carousel/tests/client/components/navigation.spec'>;
}
declare module 'vue-carousel/tests/client/components/pagination.spec.js' {
  declare module.exports: $Exports<'vue-carousel/tests/client/components/pagination.spec'>;
}
declare module 'vue-carousel/tests/client/components/slide.spec.js' {
  declare module.exports: $Exports<'vue-carousel/tests/client/components/slide.spec'>;
}
declare module 'vue-carousel/tests/preprocessor.js' {
  declare module.exports: $Exports<'vue-carousel/tests/preprocessor'>;
}
declare module 'vue-carousel/webpack.common.js' {
  declare module.exports: $Exports<'vue-carousel/webpack.common'>;
}
declare module 'vue-carousel/webpack.prod.js' {
  declare module.exports: $Exports<'vue-carousel/webpack.prod'>;
}
