// flow-typed signature: ccc4446a76ee68c65591b196d66a3327
// flow-typed version: <<STUB>>/vue-toasted_v^1.1.28/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-toasted'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-toasted' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-toasted/dist/toasted' {
  declare module.exports: any;
}

declare module 'vue-toasted/dist/toasted.min' {
  declare module.exports: any;
}

declare module 'vue-toasted/dist/vue-toasted' {
  declare module.exports: any;
}

declare module 'vue-toasted/dist/vue-toasted.min' {
  declare module.exports: any;
}

declare module 'vue-toasted/karma.conf' {
  declare module.exports: any;
}

declare module 'vue-toasted/postcss.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-toasted/dist/toasted.js' {
  declare module.exports: $Exports<'vue-toasted/dist/toasted'>;
}
declare module 'vue-toasted/dist/toasted.min.js' {
  declare module.exports: $Exports<'vue-toasted/dist/toasted.min'>;
}
declare module 'vue-toasted/dist/vue-toasted.js' {
  declare module.exports: $Exports<'vue-toasted/dist/vue-toasted'>;
}
declare module 'vue-toasted/dist/vue-toasted.min.js' {
  declare module.exports: $Exports<'vue-toasted/dist/vue-toasted.min'>;
}
declare module 'vue-toasted/karma.conf.js' {
  declare module.exports: $Exports<'vue-toasted/karma.conf'>;
}
declare module 'vue-toasted/postcss.config.js' {
  declare module.exports: $Exports<'vue-toasted/postcss.config'>;
}
