// flow-typed signature: 78e59cc90fe6b33ae0579b9c86333fa6
// flow-typed version: <<STUB>>/vue2-google-maps_v^0.10.7/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue2-google-maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue2-google-maps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue2-google-maps/build-copy' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/components/autocompleteImpl' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/components/circle' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/components/cluster' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/components/infoWindowImpl' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/components/mapElementFactory' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/components/mapElementMixin' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/components/mapImpl' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/components/marker' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/components/placeInputImpl' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/components/polygon' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/components/polyline' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/components/rectangle' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/components/streetViewPanoramaImpl' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/main' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/manager' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/utils/bindEvents' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/utils/bindProps' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/utils/lazyValue' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/utils/mountableMixin' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/utils/simulateArrowDown' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/utils/TwoWayBindingWrapper' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/utils/WatchPrimitiveProperties' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/dist/vue-google-maps' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/examples/src/autoapi' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/examples/src/ExamplesMain' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/examples/src/main' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/examples/webpack.config' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/components/autocompleteImpl' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/components/circle' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/components/cluster' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/components/infoWindowImpl' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/components/mapElementFactory' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/components/mapElementMixin' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/components/mapImpl' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/components/marker' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/components/placeInputImpl' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/components/polygon' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/components/polyline' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/components/rectangle' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/components/streetViewPanoramaImpl' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/main' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/manager' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/utils/bindEvents' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/utils/bindProps' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/utils/lazyValue' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/utils/mountableMixin' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/utils/simulateArrowDown' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/utils/TwoWayBindingWrapper' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/src/utils/WatchPrimitiveProperties' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/test/basic' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/test/gmapApi-guard' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/test/maps-not-loaded' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/test/marker-with-infowindow' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/test/test-all-examples' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/test/test-setup/babel-transform' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/test/test-setup/compile-standalone' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/test/test-setup/test-common' {
  declare module.exports: any;
}

declare module 'vue2-google-maps/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue2-google-maps/build-copy.js' {
  declare module.exports: $Exports<'vue2-google-maps/build-copy'>;
}
declare module 'vue2-google-maps/dist/components/autocompleteImpl.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/components/autocompleteImpl'>;
}
declare module 'vue2-google-maps/dist/components/circle.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/components/circle'>;
}
declare module 'vue2-google-maps/dist/components/cluster.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/components/cluster'>;
}
declare module 'vue2-google-maps/dist/components/infoWindowImpl.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/components/infoWindowImpl'>;
}
declare module 'vue2-google-maps/dist/components/mapElementFactory.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/components/mapElementFactory'>;
}
declare module 'vue2-google-maps/dist/components/mapElementMixin.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/components/mapElementMixin'>;
}
declare module 'vue2-google-maps/dist/components/mapImpl.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/components/mapImpl'>;
}
declare module 'vue2-google-maps/dist/components/marker.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/components/marker'>;
}
declare module 'vue2-google-maps/dist/components/placeInputImpl.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/components/placeInputImpl'>;
}
declare module 'vue2-google-maps/dist/components/polygon.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/components/polygon'>;
}
declare module 'vue2-google-maps/dist/components/polyline.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/components/polyline'>;
}
declare module 'vue2-google-maps/dist/components/rectangle.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/components/rectangle'>;
}
declare module 'vue2-google-maps/dist/components/streetViewPanoramaImpl.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/components/streetViewPanoramaImpl'>;
}
declare module 'vue2-google-maps/dist/main.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/main'>;
}
declare module 'vue2-google-maps/dist/manager.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/manager'>;
}
declare module 'vue2-google-maps/dist/utils/bindEvents.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/utils/bindEvents'>;
}
declare module 'vue2-google-maps/dist/utils/bindProps.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/utils/bindProps'>;
}
declare module 'vue2-google-maps/dist/utils/lazyValue.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/utils/lazyValue'>;
}
declare module 'vue2-google-maps/dist/utils/mountableMixin.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/utils/mountableMixin'>;
}
declare module 'vue2-google-maps/dist/utils/simulateArrowDown.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/utils/simulateArrowDown'>;
}
declare module 'vue2-google-maps/dist/utils/TwoWayBindingWrapper.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/utils/TwoWayBindingWrapper'>;
}
declare module 'vue2-google-maps/dist/utils/WatchPrimitiveProperties.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/utils/WatchPrimitiveProperties'>;
}
declare module 'vue2-google-maps/dist/vue-google-maps.js' {
  declare module.exports: $Exports<'vue2-google-maps/dist/vue-google-maps'>;
}
declare module 'vue2-google-maps/examples/src/autoapi.js' {
  declare module.exports: $Exports<'vue2-google-maps/examples/src/autoapi'>;
}
declare module 'vue2-google-maps/examples/src/ExamplesMain.js' {
  declare module.exports: $Exports<'vue2-google-maps/examples/src/ExamplesMain'>;
}
declare module 'vue2-google-maps/examples/src/main.js' {
  declare module.exports: $Exports<'vue2-google-maps/examples/src/main'>;
}
declare module 'vue2-google-maps/examples/webpack.config.js' {
  declare module.exports: $Exports<'vue2-google-maps/examples/webpack.config'>;
}
declare module 'vue2-google-maps/src/components/autocompleteImpl.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/components/autocompleteImpl'>;
}
declare module 'vue2-google-maps/src/components/circle.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/components/circle'>;
}
declare module 'vue2-google-maps/src/components/cluster.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/components/cluster'>;
}
declare module 'vue2-google-maps/src/components/infoWindowImpl.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/components/infoWindowImpl'>;
}
declare module 'vue2-google-maps/src/components/mapElementFactory.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/components/mapElementFactory'>;
}
declare module 'vue2-google-maps/src/components/mapElementMixin.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/components/mapElementMixin'>;
}
declare module 'vue2-google-maps/src/components/mapImpl.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/components/mapImpl'>;
}
declare module 'vue2-google-maps/src/components/marker.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/components/marker'>;
}
declare module 'vue2-google-maps/src/components/placeInputImpl.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/components/placeInputImpl'>;
}
declare module 'vue2-google-maps/src/components/polygon.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/components/polygon'>;
}
declare module 'vue2-google-maps/src/components/polyline.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/components/polyline'>;
}
declare module 'vue2-google-maps/src/components/rectangle.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/components/rectangle'>;
}
declare module 'vue2-google-maps/src/components/streetViewPanoramaImpl.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/components/streetViewPanoramaImpl'>;
}
declare module 'vue2-google-maps/src/main.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/main'>;
}
declare module 'vue2-google-maps/src/manager.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/manager'>;
}
declare module 'vue2-google-maps/src/utils/bindEvents.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/utils/bindEvents'>;
}
declare module 'vue2-google-maps/src/utils/bindProps.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/utils/bindProps'>;
}
declare module 'vue2-google-maps/src/utils/lazyValue.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/utils/lazyValue'>;
}
declare module 'vue2-google-maps/src/utils/mountableMixin.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/utils/mountableMixin'>;
}
declare module 'vue2-google-maps/src/utils/simulateArrowDown.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/utils/simulateArrowDown'>;
}
declare module 'vue2-google-maps/src/utils/TwoWayBindingWrapper.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/utils/TwoWayBindingWrapper'>;
}
declare module 'vue2-google-maps/src/utils/WatchPrimitiveProperties.js' {
  declare module.exports: $Exports<'vue2-google-maps/src/utils/WatchPrimitiveProperties'>;
}
declare module 'vue2-google-maps/test/basic.js' {
  declare module.exports: $Exports<'vue2-google-maps/test/basic'>;
}
declare module 'vue2-google-maps/test/gmapApi-guard.js' {
  declare module.exports: $Exports<'vue2-google-maps/test/gmapApi-guard'>;
}
declare module 'vue2-google-maps/test/maps-not-loaded.js' {
  declare module.exports: $Exports<'vue2-google-maps/test/maps-not-loaded'>;
}
declare module 'vue2-google-maps/test/marker-with-infowindow.js' {
  declare module.exports: $Exports<'vue2-google-maps/test/marker-with-infowindow'>;
}
declare module 'vue2-google-maps/test/test-all-examples.js' {
  declare module.exports: $Exports<'vue2-google-maps/test/test-all-examples'>;
}
declare module 'vue2-google-maps/test/test-setup/babel-transform.js' {
  declare module.exports: $Exports<'vue2-google-maps/test/test-setup/babel-transform'>;
}
declare module 'vue2-google-maps/test/test-setup/compile-standalone.js' {
  declare module.exports: $Exports<'vue2-google-maps/test/test-setup/compile-standalone'>;
}
declare module 'vue2-google-maps/test/test-setup/test-common.js' {
  declare module.exports: $Exports<'vue2-google-maps/test/test-setup/test-common'>;
}
declare module 'vue2-google-maps/webpack.config.js' {
  declare module.exports: $Exports<'vue2-google-maps/webpack.config'>;
}
