// flow-typed signature: aeeab663f8dad363a61767fb63dcb43f
// flow-typed version: <<STUB>>/vue2-gmap-custom-marker_v^5.5.10/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue2-gmap-custom-marker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue2-gmap-custom-marker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'vue2-gmap-custom-marker/index' {
  declare module.exports: $Exports<'vue2-gmap-custom-marker'>;
}
declare module 'vue2-gmap-custom-marker/index.js' {
  declare module.exports: $Exports<'vue2-gmap-custom-marker'>;
}
