// flow-typed signature: 8c669c5bdefe5ff816c5beb775cba429
// flow-typed version: <<STUB>>/vuedraggable_v^2.23.2/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuedraggable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuedraggable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuedraggable/dist/vuedraggable.common' {
  declare module.exports: any;
}

declare module 'vuedraggable/dist/vuedraggable.umd' {
  declare module.exports: any;
}

declare module 'vuedraggable/dist/vuedraggable.umd.min' {
  declare module.exports: any;
}

declare module 'vuedraggable/src/util/helper' {
  declare module.exports: any;
}

declare module 'vuedraggable/src/vuedraggable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuedraggable/dist/vuedraggable.common.js' {
  declare module.exports: $Exports<'vuedraggable/dist/vuedraggable.common'>;
}
declare module 'vuedraggable/dist/vuedraggable.umd.js' {
  declare module.exports: $Exports<'vuedraggable/dist/vuedraggable.umd'>;
}
declare module 'vuedraggable/dist/vuedraggable.umd.min.js' {
  declare module.exports: $Exports<'vuedraggable/dist/vuedraggable.umd.min'>;
}
declare module 'vuedraggable/src/util/helper.js' {
  declare module.exports: $Exports<'vuedraggable/src/util/helper'>;
}
declare module 'vuedraggable/src/vuedraggable.js' {
  declare module.exports: $Exports<'vuedraggable/src/vuedraggable'>;
}
