// flow-typed signature: 304d737b0fe82e95c133497dcb59b338
// flow-typed version: <<STUB>>/vuejs-datepicker_v^1.6.2/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuejs-datepicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuejs-datepicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuejs-datepicker/dist/locale' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/af' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/ar' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/bg' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/bs' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/ca' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/cs' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/da' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/de' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/ee' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/el' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/en' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/es' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/fa' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/fi' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/fo' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/fr' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/ge' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/gl' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/he' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/hr' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/hu' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/id' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/is' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/it' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/ja' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/kk' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/ko' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/lb' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/lt' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/lv' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/mk' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/mn' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/nb-NO' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/nl' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/pl' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/pt-BR' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/ro' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/ru' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/sk' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/sl-SI' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/sr-CYRL' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/sr' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/sv' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/th' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/tr' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/uk' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/ur' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/vi' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/zh-HK' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/locale/translations/zh' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/vuejs-datepicker.common' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/vuejs-datepicker.esm' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/vuejs-datepicker' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/vuejs-datepicker.min' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/Language' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/af' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/ar' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/bg' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/bs' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/ca' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/cs' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/da' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/de' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/ee' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/el' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/en' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/es' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/fa' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/fi' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/fo' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/fr' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/ge' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/gl' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/he' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/hr' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/hu' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/id' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/is' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/it' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/ja' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/kk' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/ko' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/lb' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/lt' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/lv' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/mk' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/mn' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/nb-NO' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/nl' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/pl' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/pt-BR' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/ro' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/ru' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/sk' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/sl-SI' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/sr-CYRL' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/sr' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/sv' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/th' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/tr' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/uk' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/ur' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/vi' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/zh-HK' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/locale/translations/zh' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/utils/DateUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuejs-datepicker/dist/locale/index' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale'>;
}
declare module 'vuejs-datepicker/dist/locale/index.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/af.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/af'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/ar.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/ar'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/bg.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/bg'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/bs.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/bs'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/ca.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/ca'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/cs.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/cs'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/da.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/da'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/de.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/de'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/ee.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/ee'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/el.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/el'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/en.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/en'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/es.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/es'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/fa.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/fa'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/fi.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/fi'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/fo.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/fo'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/fr.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/fr'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/ge.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/ge'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/gl.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/gl'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/he.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/he'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/hr.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/hr'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/hu.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/hu'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/id.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/id'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/is.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/is'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/it.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/it'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/ja.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/ja'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/kk.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/kk'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/ko.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/ko'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/lb.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/lb'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/lt.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/lt'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/lv.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/lv'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/mk.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/mk'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/mn.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/mn'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/nb-NO.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/nb-NO'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/nl.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/nl'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/pl.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/pl'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/pt-BR.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/pt-BR'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/ro.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/ro'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/ru.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/ru'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/sk.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/sk'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/sl-SI.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/sl-SI'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/sr-CYRL.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/sr-CYRL'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/sr.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/sr'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/sv.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/sv'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/th.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/th'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/tr.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/tr'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/uk.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/uk'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/ur.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/ur'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/vi.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/vi'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/zh-HK.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/zh-HK'>;
}
declare module 'vuejs-datepicker/dist/locale/translations/zh.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/locale/translations/zh'>;
}
declare module 'vuejs-datepicker/dist/vuejs-datepicker.common.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/vuejs-datepicker.common'>;
}
declare module 'vuejs-datepicker/dist/vuejs-datepicker.esm.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/vuejs-datepicker.esm'>;
}
declare module 'vuejs-datepicker/dist/vuejs-datepicker.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/vuejs-datepicker'>;
}
declare module 'vuejs-datepicker/dist/vuejs-datepicker.min.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/vuejs-datepicker.min'>;
}
declare module 'vuejs-datepicker/src/locale/index' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale'>;
}
declare module 'vuejs-datepicker/src/locale/index.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale'>;
}
declare module 'vuejs-datepicker/src/locale/Language.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/Language'>;
}
declare module 'vuejs-datepicker/src/locale/translations/af.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/af'>;
}
declare module 'vuejs-datepicker/src/locale/translations/ar.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/ar'>;
}
declare module 'vuejs-datepicker/src/locale/translations/bg.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/bg'>;
}
declare module 'vuejs-datepicker/src/locale/translations/bs.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/bs'>;
}
declare module 'vuejs-datepicker/src/locale/translations/ca.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/ca'>;
}
declare module 'vuejs-datepicker/src/locale/translations/cs.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/cs'>;
}
declare module 'vuejs-datepicker/src/locale/translations/da.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/da'>;
}
declare module 'vuejs-datepicker/src/locale/translations/de.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/de'>;
}
declare module 'vuejs-datepicker/src/locale/translations/ee.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/ee'>;
}
declare module 'vuejs-datepicker/src/locale/translations/el.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/el'>;
}
declare module 'vuejs-datepicker/src/locale/translations/en.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/en'>;
}
declare module 'vuejs-datepicker/src/locale/translations/es.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/es'>;
}
declare module 'vuejs-datepicker/src/locale/translations/fa.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/fa'>;
}
declare module 'vuejs-datepicker/src/locale/translations/fi.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/fi'>;
}
declare module 'vuejs-datepicker/src/locale/translations/fo.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/fo'>;
}
declare module 'vuejs-datepicker/src/locale/translations/fr.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/fr'>;
}
declare module 'vuejs-datepicker/src/locale/translations/ge.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/ge'>;
}
declare module 'vuejs-datepicker/src/locale/translations/gl.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/gl'>;
}
declare module 'vuejs-datepicker/src/locale/translations/he.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/he'>;
}
declare module 'vuejs-datepicker/src/locale/translations/hr.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/hr'>;
}
declare module 'vuejs-datepicker/src/locale/translations/hu.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/hu'>;
}
declare module 'vuejs-datepicker/src/locale/translations/id.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/id'>;
}
declare module 'vuejs-datepicker/src/locale/translations/is.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/is'>;
}
declare module 'vuejs-datepicker/src/locale/translations/it.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/it'>;
}
declare module 'vuejs-datepicker/src/locale/translations/ja.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/ja'>;
}
declare module 'vuejs-datepicker/src/locale/translations/kk.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/kk'>;
}
declare module 'vuejs-datepicker/src/locale/translations/ko.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/ko'>;
}
declare module 'vuejs-datepicker/src/locale/translations/lb.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/lb'>;
}
declare module 'vuejs-datepicker/src/locale/translations/lt.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/lt'>;
}
declare module 'vuejs-datepicker/src/locale/translations/lv.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/lv'>;
}
declare module 'vuejs-datepicker/src/locale/translations/mk.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/mk'>;
}
declare module 'vuejs-datepicker/src/locale/translations/mn.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/mn'>;
}
declare module 'vuejs-datepicker/src/locale/translations/nb-NO.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/nb-NO'>;
}
declare module 'vuejs-datepicker/src/locale/translations/nl.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/nl'>;
}
declare module 'vuejs-datepicker/src/locale/translations/pl.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/pl'>;
}
declare module 'vuejs-datepicker/src/locale/translations/pt-BR.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/pt-BR'>;
}
declare module 'vuejs-datepicker/src/locale/translations/ro.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/ro'>;
}
declare module 'vuejs-datepicker/src/locale/translations/ru.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/ru'>;
}
declare module 'vuejs-datepicker/src/locale/translations/sk.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/sk'>;
}
declare module 'vuejs-datepicker/src/locale/translations/sl-SI.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/sl-SI'>;
}
declare module 'vuejs-datepicker/src/locale/translations/sr-CYRL.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/sr-CYRL'>;
}
declare module 'vuejs-datepicker/src/locale/translations/sr.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/sr'>;
}
declare module 'vuejs-datepicker/src/locale/translations/sv.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/sv'>;
}
declare module 'vuejs-datepicker/src/locale/translations/th.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/th'>;
}
declare module 'vuejs-datepicker/src/locale/translations/tr.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/tr'>;
}
declare module 'vuejs-datepicker/src/locale/translations/uk.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/uk'>;
}
declare module 'vuejs-datepicker/src/locale/translations/ur.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/ur'>;
}
declare module 'vuejs-datepicker/src/locale/translations/vi.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/vi'>;
}
declare module 'vuejs-datepicker/src/locale/translations/zh-HK.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/zh-HK'>;
}
declare module 'vuejs-datepicker/src/locale/translations/zh.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/locale/translations/zh'>;
}
declare module 'vuejs-datepicker/src/utils/DateUtils.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/utils/DateUtils'>;
}
