// flow-typed signature: 912e8c1840e8d16b20a7a6462913f7a1
// flow-typed version: <<STUB>>/vuex_v^3.5.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuex/dist/logger' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.cjs' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.common' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.esm-browser' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.esm-browser.prod' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.esm-bundler' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.esm.browser' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.esm.browser.min' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.esm' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.global' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.global.prod' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuex/dist/logger.js' {
  declare module.exports: $Exports<'vuex/dist/logger'>;
}
declare module 'vuex/dist/vuex.cjs.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.cjs'>;
}
declare module 'vuex/dist/vuex.common.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.common'>;
}
declare module 'vuex/dist/vuex.esm-browser.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.esm-browser'>;
}
declare module 'vuex/dist/vuex.esm-browser.prod.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.esm-browser.prod'>;
}
declare module 'vuex/dist/vuex.esm-bundler.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.esm-bundler'>;
}
declare module 'vuex/dist/vuex.esm.browser.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.esm.browser'>;
}
declare module 'vuex/dist/vuex.esm.browser.min.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.esm.browser.min'>;
}
declare module 'vuex/dist/vuex.esm.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.esm'>;
}
declare module 'vuex/dist/vuex.global.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.global'>;
}
declare module 'vuex/dist/vuex.global.prod.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.global.prod'>;
}
declare module 'vuex/dist/vuex.js' {
  declare module.exports: $Exports<'vuex/dist/vuex'>;
}
declare module 'vuex/dist/vuex.min.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.min'>;
}
