// flow-typed signature: f336c99c63e3a609e320128e8dea6c05
// flow-typed version: <<STUB>>/vuex-persist_v^2.2.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuex-persist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuex-persist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuex-persist/dist/cjs' {
  declare module.exports: any;
}

declare module 'vuex-persist/dist/esm' {
  declare module.exports: any;
}

declare module 'vuex-persist/dist/umd' {
  declare module.exports: any;
}

declare module 'vuex-persist/dist/umd/index.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuex-persist/dist/cjs/index' {
  declare module.exports: $Exports<'vuex-persist/dist/cjs'>;
}
declare module 'vuex-persist/dist/cjs/index.js' {
  declare module.exports: $Exports<'vuex-persist/dist/cjs'>;
}
declare module 'vuex-persist/dist/esm/index' {
  declare module.exports: $Exports<'vuex-persist/dist/esm'>;
}
declare module 'vuex-persist/dist/esm/index.js' {
  declare module.exports: $Exports<'vuex-persist/dist/esm'>;
}
declare module 'vuex-persist/dist/umd/index' {
  declare module.exports: $Exports<'vuex-persist/dist/umd'>;
}
declare module 'vuex-persist/dist/umd/index.js' {
  declare module.exports: $Exports<'vuex-persist/dist/umd'>;
}
declare module 'vuex-persist/dist/umd/index.min.js' {
  declare module.exports: $Exports<'vuex-persist/dist/umd/index.min'>;
}
