// flow-typed signature: 0fe87764d96a49db9882a0d9d4275677
// flow-typed version: <<STUB>>/vuex-module-decorators_v^0.17.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuex-module-decorators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuex-module-decorators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuex-module-decorators/dist/cjs' {
  declare module.exports: any;
}

declare module 'vuex-module-decorators/dist/esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuex-module-decorators/dist/cjs/index' {
  declare module.exports: $Exports<'vuex-module-decorators/dist/cjs'>;
}
declare module 'vuex-module-decorators/dist/cjs/index.js' {
  declare module.exports: $Exports<'vuex-module-decorators/dist/cjs'>;
}
declare module 'vuex-module-decorators/dist/esm/index' {
  declare module.exports: $Exports<'vuex-module-decorators/dist/esm'>;
}
declare module 'vuex-module-decorators/dist/esm/index.js' {
  declare module.exports: $Exports<'vuex-module-decorators/dist/esm'>;
}
