// flow-typed signature: 9e5d400e1d9cbb0688271e3f259013f3
// flow-typed version: <<STUB>>/vuex-mock-store_v0.0.8/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuex-mock-store'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuex-mock-store' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuex-mock-store/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuex-mock-store/src/index' {
  declare module.exports: $Exports<'vuex-mock-store/src'>;
}
declare module 'vuex-mock-store/src/index.js' {
  declare module.exports: $Exports<'vuex-mock-store/src'>;
}
