// flow-typed signature: e19bdbb809ff58def6d8aacc57816305
// flow-typed version: <<STUB>>/@ringcentral/sdk_v^4.3.2/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ringcentral/sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ringcentral/sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ringcentral/sdk/dist/ringcentral' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/dist/ringcentral.min' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/es6/core/Cache-spec' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/es6/core/Cache' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/es6/core/Constants' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/es6/core/Externals' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/es6/http/Client-spec' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/es6/http/Client' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/es6' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/es6/platform/Auth' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/es6/platform/Platform-spec' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/es6/platform/Platform' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/es6/SDK-spec' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/es6/SDK' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/es6/test/test' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/lib/core/Cache-spec' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/lib/core/Cache' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/lib/core/Constants' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/lib/core/Externals' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/lib/http/Client-spec' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/lib/http/Client' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/lib' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/lib/platform/Auth' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/lib/platform/Platform-spec' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/lib/platform/Platform' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/lib/SDK-spec' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/lib/SDK' {
  declare module.exports: any;
}

declare module '@ringcentral/sdk/lib/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ringcentral/sdk/dist/ringcentral.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/dist/ringcentral'>;
}
declare module '@ringcentral/sdk/dist/ringcentral.min.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/dist/ringcentral.min'>;
}
declare module '@ringcentral/sdk/es6/core/Cache-spec.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/es6/core/Cache-spec'>;
}
declare module '@ringcentral/sdk/es6/core/Cache.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/es6/core/Cache'>;
}
declare module '@ringcentral/sdk/es6/core/Constants.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/es6/core/Constants'>;
}
declare module '@ringcentral/sdk/es6/core/Externals.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/es6/core/Externals'>;
}
declare module '@ringcentral/sdk/es6/http/Client-spec.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/es6/http/Client-spec'>;
}
declare module '@ringcentral/sdk/es6/http/Client.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/es6/http/Client'>;
}
declare module '@ringcentral/sdk/es6/index' {
  declare module.exports: $Exports<'@ringcentral/sdk/es6'>;
}
declare module '@ringcentral/sdk/es6/index.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/es6'>;
}
declare module '@ringcentral/sdk/es6/platform/Auth.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/es6/platform/Auth'>;
}
declare module '@ringcentral/sdk/es6/platform/Platform-spec.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/es6/platform/Platform-spec'>;
}
declare module '@ringcentral/sdk/es6/platform/Platform.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/es6/platform/Platform'>;
}
declare module '@ringcentral/sdk/es6/SDK-spec.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/es6/SDK-spec'>;
}
declare module '@ringcentral/sdk/es6/SDK.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/es6/SDK'>;
}
declare module '@ringcentral/sdk/es6/test/test.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/es6/test/test'>;
}
declare module '@ringcentral/sdk/lib/core/Cache-spec.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/lib/core/Cache-spec'>;
}
declare module '@ringcentral/sdk/lib/core/Cache.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/lib/core/Cache'>;
}
declare module '@ringcentral/sdk/lib/core/Constants.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/lib/core/Constants'>;
}
declare module '@ringcentral/sdk/lib/core/Externals.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/lib/core/Externals'>;
}
declare module '@ringcentral/sdk/lib/http/Client-spec.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/lib/http/Client-spec'>;
}
declare module '@ringcentral/sdk/lib/http/Client.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/lib/http/Client'>;
}
declare module '@ringcentral/sdk/lib/index' {
  declare module.exports: $Exports<'@ringcentral/sdk/lib'>;
}
declare module '@ringcentral/sdk/lib/index.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/lib'>;
}
declare module '@ringcentral/sdk/lib/platform/Auth.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/lib/platform/Auth'>;
}
declare module '@ringcentral/sdk/lib/platform/Platform-spec.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/lib/platform/Platform-spec'>;
}
declare module '@ringcentral/sdk/lib/platform/Platform.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/lib/platform/Platform'>;
}
declare module '@ringcentral/sdk/lib/SDK-spec.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/lib/SDK-spec'>;
}
declare module '@ringcentral/sdk/lib/SDK.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/lib/SDK'>;
}
declare module '@ringcentral/sdk/lib/test/test.js' {
  declare module.exports: $Exports<'@ringcentral/sdk/lib/test/test'>;
}
