// flow-typed signature: 708e2d4b561b17b9eb6578918f4c3c7e
// flow-typed version: <<STUB>>/@dreipol/vue-log_v0.0.8/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dreipol/vue-log'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dreipol/vue-log' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dreipol/vue-log/dist' {
  declare module.exports: any;
}

declare module '@dreipol/vue-log/src' {
  declare module.exports: any;
}

declare module '@dreipol/vue-log/src/middlewares' {
  declare module.exports: any;
}

declare module '@dreipol/vue-log/src/presets' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dreipol/vue-log/dist/index' {
  declare module.exports: $Exports<'@dreipol/vue-log/dist'>;
}
declare module '@dreipol/vue-log/dist/index.js' {
  declare module.exports: $Exports<'@dreipol/vue-log/dist'>;
}
declare module '@dreipol/vue-log/src/index' {
  declare module.exports: $Exports<'@dreipol/vue-log/src'>;
}
declare module '@dreipol/vue-log/src/index.js' {
  declare module.exports: $Exports<'@dreipol/vue-log/src'>;
}
declare module '@dreipol/vue-log/src/middlewares.js' {
  declare module.exports: $Exports<'@dreipol/vue-log/src/middlewares'>;
}
declare module '@dreipol/vue-log/src/presets.js' {
  declare module.exports: $Exports<'@dreipol/vue-log/src/presets'>;
}
