// flow-typed signature: 6008f1e6783b86f8c7d82d21717859d8
// flow-typed version: <<STUB>>/@authenio/samlify-xsd-schema-validator_v^1.0.3/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@authenio/samlify-xsd-schema-validator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@authenio/samlify-xsd-schema-validator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@authenio/samlify-xsd-schema-validator/build' {
  declare module.exports: any;
}

// Filename aliases
declare module '@authenio/samlify-xsd-schema-validator/build/index' {
  declare module.exports: $Exports<'@authenio/samlify-xsd-schema-validator/build'>;
}
declare module '@authenio/samlify-xsd-schema-validator/build/index.js' {
  declare module.exports: $Exports<'@authenio/samlify-xsd-schema-validator/build'>;
}
