// flow-typed signature: 3ccf959b3c55196eddf8e865c1bb838a
// flow-typed version: <<STUB>>/@vue/composition-api_v1.0.0-beta.8/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vue/composition-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vue/composition-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vue/composition-api/dist/vue-composition-api.common' {
  declare module.exports: any;
}

declare module '@vue/composition-api/dist/vue-composition-api.common.prod' {
  declare module.exports: any;
}

declare module '@vue/composition-api/dist/vue-composition-api.esm' {
  declare module.exports: any;
}

declare module '@vue/composition-api/dist/vue-composition-api' {
  declare module.exports: any;
}

declare module '@vue/composition-api/dist/vue-composition-api.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vue/composition-api/dist/vue-composition-api.common.js' {
  declare module.exports: $Exports<'@vue/composition-api/dist/vue-composition-api.common'>;
}
declare module '@vue/composition-api/dist/vue-composition-api.common.prod.js' {
  declare module.exports: $Exports<'@vue/composition-api/dist/vue-composition-api.common.prod'>;
}
declare module '@vue/composition-api/dist/vue-composition-api.esm.js' {
  declare module.exports: $Exports<'@vue/composition-api/dist/vue-composition-api.esm'>;
}
declare module '@vue/composition-api/dist/vue-composition-api.js' {
  declare module.exports: $Exports<'@vue/composition-api/dist/vue-composition-api'>;
}
declare module '@vue/composition-api/dist/vue-composition-api.prod.js' {
  declare module.exports: $Exports<'@vue/composition-api/dist/vue-composition-api.prod'>;
}
declare module '@vue/composition-api/index' {
  declare module.exports: $Exports<'@vue/composition-api'>;
}
declare module '@vue/composition-api/index.js' {
  declare module.exports: $Exports<'@vue/composition-api'>;
}
