// flow-typed signature: dde171de09847749aeefdf7d6126d720
// flow-typed version: <<STUB>>/@vue/test-utils_v^1.0.0-beta.32/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vue/test-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vue/test-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vue/test-utils/dist/vue-test-utils.iife' {
  declare module.exports: any;
}

declare module '@vue/test-utils/dist/vue-test-utils' {
  declare module.exports: any;
}

declare module '@vue/test-utils/dist/vue-test-utils.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vue/test-utils/dist/vue-test-utils.iife.js' {
  declare module.exports: $Exports<'@vue/test-utils/dist/vue-test-utils.iife'>;
}
declare module '@vue/test-utils/dist/vue-test-utils.js' {
  declare module.exports: $Exports<'@vue/test-utils/dist/vue-test-utils'>;
}
declare module '@vue/test-utils/dist/vue-test-utils.umd.js' {
  declare module.exports: $Exports<'@vue/test-utils/dist/vue-test-utils.umd'>;
}
