<template>
  <div class="flex flex-col items-center justify-center">
    <font-awesome-icon :size="size" icon="spinner" spin />
    <div v-if="showQuote" class="my-3">{{ $t(randomQuote) }}</div>
  </div>
</template>

<script lang="ts">
import { sample } from 'lodash';

const RANDOM_QUOTES = [
  'spinner.loading_perpetual_motion',
  'spinner.loading_break_from_reality',
  'spinner.loading_quantum_physics',
  'spinner.loading_time_illusion',
  'spinner.loading_universe_spinning',
  'spinner.loading_patience_virtue',
  'spinner.loading_olympic_games',
  'spinner.loading_sit_back_relax',
  'spinner.loading_circles_captivating',
  'spinner.loading_warning_circus',
  'spinner.loading_spinner_mission',
  'spinner.loading_getting_sleepy',
  'spinner.loading_grasshopper_zen_mode',
  'spinner.loading_think_i_can',
  'spinner.loading_spinner_nobody_sees',
  'spinner.loading_twist_twirl_almost_there',
  'spinner.loading_watch_learn_dance',
  'spinner.loading_magic_in_progress',
  'spinner.loading_ufo',
  'spinner.loading_spin_me_right_round',
  'spinner.loading_politician',
  'spinner.loading_tick_tock',
  'spinner.loading_patience_padawan',
  'spinner.loading_revving_engines',
  'spinner.loading_stay_calm_spin_on',
  'spinner.loading_sprinkle_magic',
  'spinner.loading_pirouettes',
  'spinner.loading_dj_remix',
  'spinner.loading_invisible_hamster',
  'spinner.loading_pixelated_snail',
  'spinner.loading_invisible_ninjas',
  'spinner.loading_magic_clown',
  'spinner.loading_caffeinated_squirrel',
  'spinner.loading_mad_scientist',
  'spinner.loading_trained_penguins',
  'spinner.loading_intergalactic_turtle',
  'spinner.loading_tap_dancing_kangaroo',
  'spinner.loading_cheetah_intern',
  'spinner.loading_synchronized_swimmers',
  'spinner.loading_superhero_squirrel',
  'spinner.loading_ants_circle',
  'spinner.loading_tornado_octopus',
  'spinner.loading_wizard_spells',
  'spinner.loading_conjuring_magician',
  'spinner.loading_turbo_turtle',
  'spinner.loading_dj_sloth',
  'spinner.loading_synchronized_skydivers',
  'spinner.loading_spin_style',
  'spinner.loading_hamster_moon_walk',
  'spinner.loading_coding_sensei',
  'spinner.loading_friendly_ghost',
  'spinner.loading_website_yawn',
  'spinner.loading_spinner_miles',
  'spinner.loading_cyborg_hedgehog',
  'spinner.loading_data_bunnies',
  'spinner.loading_snacks_menu',
  'spinner.loading_roses_are_red',
  'spinner.loading_patience_halo',
  'spinner.loading_sloth_marathon',
  'spinner.loading_streaming_aging',
  'spinner.loading_time_machine',
  'spinner.loading_spinner_mocking',
  'spinner.loading_sloth_conservation',
  'spinner.loading_mona_lisa',
  'spinner.loading_mindfulness_meditation',
  'spinner.loading_world_record',
  'spinner.loading_enter_matrix',
  'spinner.loading_steam_engines',
  'spinner.loading_never_ending_load',
  'spinner.loading_waiting_rooms',
  'spinner.loading_slo_mo',
  'spinner.loading_time_is_money',
  'spinner.loading_delorean_gigawatt',
  'spinner.loading_disco_ball',
  'spinner.loading_toilet_flush',
  'spinner.loading_sonic_boom',
  'spinner.loading_fairy_breadcrumbs',
  'spinner.loading_11_kids',
  'spinner.loading_pixel_dragons',
  'spinner.website_doctor_bugs',
  'spinner.website_break_up_internet',
  'spinner.website_ladder_search_results',
  'spinner.keyboard_trouble_copying',
  'spinner.website_cold_pages_freezing',
  'spinner.website_diet_cookies',
  'spinner.website_party_network',
  'spinner.website_meditating_inner_webpage',
  'spinner.loading_invisible_artist_painting',
  'spinner.loading_boldly_go',
  'spinner.loading_clown_unicycle',
  'spinner.loading_row_boat_stream',
  'spinner.loading_sly_spinner_poem',
  'spinner.loading_zzzzzzz',
  'spinner.loading_spinner_twirl_poem',
  'spinner.loading_pixel_rodeo',
  'spinner.loading_practicing_lasso',
  'spinner.loading_where_stop_nobody_knows',
  'spinner.loading_synchronized_dolphins',
  'spinner.loading_circle_of_circles',
  'spinner.loading_wheels_on_the_bus',
  'spinner.loading_circle_of_life',
  'spinner.loading_circles_all_the_way_down',
  'spinner.loading_circleception',
  'spinner.loading_where_is_spinner_going',
  'spinner.loading_pixel_lemmings',
  'spinner.loading_surprised_how_many_phrases',
  'spinner.loading_wish_go_somewhere',
  'spinner.loading_mastered_moonwalk',
  'spinner.loading_why_cross_road',
  'spinner.loading_this_is_not_a_spinner',
  'spinner.loading_louvre_when_done',
  'spinner.loading_worse_than_sisyphus',
  'spinner.loading_conveyor_of_happiness',
  'spinner.loading_double_click_icon_surprise',
  'spinner.loading_rollin_swollen_rawhide',
  'spinner.loading_wheel_on_the_screen_turning',
  'spinner.loading_for_everything_season',
  'spinner.loading_twinkle_twinkle',
  'spinner.loading_itsy_bitsy_pixel_spider',
  'spinner.loading_hokey_pokey_turn',
  'spinner.loading_summoning_superpowers',
  'spinner.loading_like_no_tomorrow',
  'spinner.loading_patience_virtue_virtuoso',
  'spinner.loading_how_many_popcorn_count',
  'spinner.loading_not_lost_scenic route',
  'spinner.loading_ninja_conquering_loading',
  'spinner.loading_digital_world_go_round',
  'spinner.loading_secrets_of_universe',
  'spinner.loading_enjoy_the_suspense',
  'spinner.loading_drive_parkways_park_driveways',
  'spinner.loading_stretching_loading_muscles',
  'spinner.loading_snail_break_sound_barrier',
  'spinner.loading_enjoy_the_show_main_attraction',
  'spinner.loading_digital_barista_mixing',
  'spinner.loading_might_start_breakdancing',
  'spinner.loading_bits_bytes_conga_line',
  'spinner.loading_loading_adventure_this_page',
  'spinner.loading_are_we_there_yet',
  'spinner.loading_virtual_chef_mayo_white_bread',
  'spinner.loading_hamster_caffeine',
  'spinner.loading_loading_bars_overrated',
  'spinner.loading_dance_nobodys_watching',
  'spinner.loading_imagine_no_loading_beautiful',
  'spinner.loading_as_amazing_as_you',
  'spinner.loading_spinning_groove_join_dance',
  'spinner.loading_spinning_prowess',
  'spinner.loading_great_things_wait_for_me',
  'spinner.loading_americas_got_spin',
  'spinner.loading_art_spinning_picasso',
  'spinner.loading_pixelated_stardust_screen',
  'spinner.loading_realm_of_loading',
  'spinner.loading_meaning_of_life_101010',
  'spinner.loading_meaning_of_life_42_137',
  'spinner.loading_spinner_backflip',
  'spinner.loading_rome_built_loading_screen',
  'spinner.loading_bird_plane_super_spinner',
  'spinner.loading_not_moon_pixel_space_station',
  'spinner.loading_digital_turntable_party',
  'spinner.loading_won_fastest_spinner_competition',
  'spinner.loading_hold_applause',
  'spinner.loading_shooting_star_grant_wishes',
  'spinner.loading_wheel_of_fortune',
  'spinner.loading_spinning_into_your_heart',
  'spinner.loading_cheetah_on_roller_skates',
  'spinner.loading_virtual_popcorn',
  'spinner.loading_take_me_with_you',
];

export default defineComponent({
  name: 'Spinner',
  props: {
    size: {
      type: String,
      default: 'xl',
    },
    showQuote: {
      type: Boolean,
    },
  },
  setup() {
    const randomQuote = ref<string>(sample(RANDOM_QUOTES));
    return {
      randomQuote,
    };
  },
});
</script>
