// flow-typed signature: ab8f1c47449809e7b2a98e33466c0884
// flow-typed version: <<STUB>>/@vuex-orm/plugin-axios_v^0.9.3/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vuex-orm/plugin-axios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vuex-orm/plugin-axios' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs' {
  declare module.exports: any;
}

declare module '@vuex-orm/plugin-axios/dist/vuex-orm-axios.esm-browser' {
  declare module.exports: any;
}

declare module '@vuex-orm/plugin-axios/dist/vuex-orm-axios.esm-browser.prod' {
  declare module.exports: any;
}

declare module '@vuex-orm/plugin-axios/dist/vuex-orm-axios.esm-bundler' {
  declare module.exports: any;
}

declare module '@vuex-orm/plugin-axios/dist/vuex-orm-axios.global' {
  declare module.exports: any;
}

declare module '@vuex-orm/plugin-axios/dist/vuex-orm-axios.global.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js' {
  declare module.exports: $Exports<'@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs'>;
}
declare module '@vuex-orm/plugin-axios/dist/vuex-orm-axios.esm-browser.js' {
  declare module.exports: $Exports<'@vuex-orm/plugin-axios/dist/vuex-orm-axios.esm-browser'>;
}
declare module '@vuex-orm/plugin-axios/dist/vuex-orm-axios.esm-browser.prod.js' {
  declare module.exports: $Exports<'@vuex-orm/plugin-axios/dist/vuex-orm-axios.esm-browser.prod'>;
}
declare module '@vuex-orm/plugin-axios/dist/vuex-orm-axios.esm-bundler.js' {
  declare module.exports: $Exports<'@vuex-orm/plugin-axios/dist/vuex-orm-axios.esm-bundler'>;
}
declare module '@vuex-orm/plugin-axios/dist/vuex-orm-axios.global.js' {
  declare module.exports: $Exports<'@vuex-orm/plugin-axios/dist/vuex-orm-axios.global'>;
}
declare module '@vuex-orm/plugin-axios/dist/vuex-orm-axios.global.prod.js' {
  declare module.exports: $Exports<'@vuex-orm/plugin-axios/dist/vuex-orm-axios.global.prod'>;
}
