// flow-typed signature: a6a4abc8cd00fb0cb31b83ce5810e589
// flow-typed version: <<STUB>>/@vuex-orm/plugin-change-flags_v^1.2.3/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vuex-orm/plugin-change-flags'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vuex-orm/plugin-change-flags' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vuex-orm/plugin-change-flags/dist' {
  declare module.exports: any;
}

declare module '@vuex-orm/plugin-change-flags/src' {
  declare module.exports: any;
}

declare module '@vuex-orm/plugin-change-flags/test/dev/common/models/Role' {
  declare module.exports: any;
}

declare module '@vuex-orm/plugin-change-flags/test/dev/common/models/User' {
  declare module.exports: any;
}

declare module '@vuex-orm/plugin-change-flags/test/dev' {
  declare module.exports: any;
}

declare module '@vuex-orm/plugin-change-flags/test/unit/test-all' {
  declare module.exports: any;
}

declare module '@vuex-orm/plugin-change-flags/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vuex-orm/plugin-change-flags/dist/index' {
  declare module.exports: $Exports<'@vuex-orm/plugin-change-flags/dist'>;
}
declare module '@vuex-orm/plugin-change-flags/dist/index.js' {
  declare module.exports: $Exports<'@vuex-orm/plugin-change-flags/dist'>;
}
declare module '@vuex-orm/plugin-change-flags/src/index' {
  declare module.exports: $Exports<'@vuex-orm/plugin-change-flags/src'>;
}
declare module '@vuex-orm/plugin-change-flags/src/index.js' {
  declare module.exports: $Exports<'@vuex-orm/plugin-change-flags/src'>;
}
declare module '@vuex-orm/plugin-change-flags/test/dev/common/models/Role.js' {
  declare module.exports: $Exports<'@vuex-orm/plugin-change-flags/test/dev/common/models/Role'>;
}
declare module '@vuex-orm/plugin-change-flags/test/dev/common/models/User.js' {
  declare module.exports: $Exports<'@vuex-orm/plugin-change-flags/test/dev/common/models/User'>;
}
declare module '@vuex-orm/plugin-change-flags/test/dev/index' {
  declare module.exports: $Exports<'@vuex-orm/plugin-change-flags/test/dev'>;
}
declare module '@vuex-orm/plugin-change-flags/test/dev/index.js' {
  declare module.exports: $Exports<'@vuex-orm/plugin-change-flags/test/dev'>;
}
declare module '@vuex-orm/plugin-change-flags/test/unit/test-all.js' {
  declare module.exports: $Exports<'@vuex-orm/plugin-change-flags/test/unit/test-all'>;
}
declare module '@vuex-orm/plugin-change-flags/webpack.config.js' {
  declare module.exports: $Exports<'@vuex-orm/plugin-change-flags/webpack.config'>;
}
