// flow-typed signature: 89e1f49cd6cb6dbb064b5f6f900f3ebc
// flow-typed version: <<STUB>>/@percy/cypress_v^2.3.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@percy/cypress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@percy/cypress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@percy/cypress/dist/environment' {
  declare module.exports: any;
}

declare module '@percy/cypress/dist' {
  declare module.exports: any;
}

declare module '@percy/cypress/run-tests' {
  declare module.exports: any;
}

declare module '@percy/cypress/task' {
  declare module.exports: any;
}

// Filename aliases
declare module '@percy/cypress/dist/environment.js' {
  declare module.exports: $Exports<'@percy/cypress/dist/environment'>;
}
declare module '@percy/cypress/dist/index' {
  declare module.exports: $Exports<'@percy/cypress/dist'>;
}
declare module '@percy/cypress/dist/index.js' {
  declare module.exports: $Exports<'@percy/cypress/dist'>;
}
declare module '@percy/cypress/run-tests.js' {
  declare module.exports: $Exports<'@percy/cypress/run-tests'>;
}
declare module '@percy/cypress/task.js' {
  declare module.exports: $Exports<'@percy/cypress/task'>;
}
