// flow-typed signature: 11d89c502b9b18b56a0e16dcd2bef9fb
// flow-typed version: <<STUB>>/@johmun/vue-tags-input_v^2.1.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@johmun/vue-tags-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@johmun/vue-tags-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@johmun/vue-tags-input/build/docs.config' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/build/lib.config' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/dist/vue-tags-input' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/docs/docs-formatter' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/docs/docs-loader' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/docs/main' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/docs/pages/api' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/docs/pages/examples/hooks/example1.demo' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/docs/pages/examples/hooks/example2.demo' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/docs/pages/examples' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/docs/pages/examples/styling/example1.demo' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/docs/pages/examples/templates/example1.demo' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/docs/pages/examples/templates/example2.demo' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/docs/pages/examples/templates/example4.demo' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/docs/pages/examples/validation/example1.demo' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/docs/router' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/docs/slots-data' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/e2e/add-save-on-key.test' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/e2e/autocomplete.test' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/e2e/check-navigation.test' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/e2e/edit-tag.test' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/e2e/getting-started.test' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/e2e/hooks.test' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/e2e/suite' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/e2e/validation.test' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/vue-tags-input/create-tags' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/vue-tags-input/publish' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/vue-tags-input/vue-tags-input' {
  declare module.exports: any;
}

declare module '@johmun/vue-tags-input/vue-tags-input/vue-tags-input.props' {
  declare module.exports: any;
}

// Filename aliases
declare module '@johmun/vue-tags-input/build/docs.config.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/build/docs.config'>;
}
declare module '@johmun/vue-tags-input/build/lib.config.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/build/lib.config'>;
}
declare module '@johmun/vue-tags-input/dist/vue-tags-input.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/dist/vue-tags-input'>;
}
declare module '@johmun/vue-tags-input/docs/docs-formatter.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/docs-formatter'>;
}
declare module '@johmun/vue-tags-input/docs/docs-loader.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/docs-loader'>;
}
declare module '@johmun/vue-tags-input/docs/main.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/main'>;
}
declare module '@johmun/vue-tags-input/docs/pages/api/index' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/pages/api'>;
}
declare module '@johmun/vue-tags-input/docs/pages/api/index.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/pages/api'>;
}
declare module '@johmun/vue-tags-input/docs/pages/examples/hooks/example1.demo.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/pages/examples/hooks/example1.demo'>;
}
declare module '@johmun/vue-tags-input/docs/pages/examples/hooks/example2.demo.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/pages/examples/hooks/example2.demo'>;
}
declare module '@johmun/vue-tags-input/docs/pages/examples/index' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/pages/examples'>;
}
declare module '@johmun/vue-tags-input/docs/pages/examples/index.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/pages/examples'>;
}
declare module '@johmun/vue-tags-input/docs/pages/examples/styling/example1.demo.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/pages/examples/styling/example1.demo'>;
}
declare module '@johmun/vue-tags-input/docs/pages/examples/templates/example1.demo.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/pages/examples/templates/example1.demo'>;
}
declare module '@johmun/vue-tags-input/docs/pages/examples/templates/example2.demo.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/pages/examples/templates/example2.demo'>;
}
declare module '@johmun/vue-tags-input/docs/pages/examples/templates/example4.demo.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/pages/examples/templates/example4.demo'>;
}
declare module '@johmun/vue-tags-input/docs/pages/examples/validation/example1.demo.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/pages/examples/validation/example1.demo'>;
}
declare module '@johmun/vue-tags-input/docs/router.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/router'>;
}
declare module '@johmun/vue-tags-input/docs/slots-data.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/docs/slots-data'>;
}
declare module '@johmun/vue-tags-input/e2e/add-save-on-key.test.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/e2e/add-save-on-key.test'>;
}
declare module '@johmun/vue-tags-input/e2e/autocomplete.test.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/e2e/autocomplete.test'>;
}
declare module '@johmun/vue-tags-input/e2e/check-navigation.test.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/e2e/check-navigation.test'>;
}
declare module '@johmun/vue-tags-input/e2e/edit-tag.test.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/e2e/edit-tag.test'>;
}
declare module '@johmun/vue-tags-input/e2e/getting-started.test.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/e2e/getting-started.test'>;
}
declare module '@johmun/vue-tags-input/e2e/hooks.test.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/e2e/hooks.test'>;
}
declare module '@johmun/vue-tags-input/e2e/suite/index' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/e2e/suite'>;
}
declare module '@johmun/vue-tags-input/e2e/suite/index.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/e2e/suite'>;
}
declare module '@johmun/vue-tags-input/e2e/validation.test.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/e2e/validation.test'>;
}
declare module '@johmun/vue-tags-input/vue-tags-input/create-tags.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/vue-tags-input/create-tags'>;
}
declare module '@johmun/vue-tags-input/vue-tags-input/publish.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/vue-tags-input/publish'>;
}
declare module '@johmun/vue-tags-input/vue-tags-input/vue-tags-input.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/vue-tags-input/vue-tags-input'>;
}
declare module '@johmun/vue-tags-input/vue-tags-input/vue-tags-input.props.js' {
  declare module.exports: $Exports<'@johmun/vue-tags-input/vue-tags-input/vue-tags-input.props'>;
}
