// flow-typed signature: 9cefe986f775e2ec894955c179fdf79c
// flow-typed version: <<STUB>>/@storybook/addon-centered_v^5.3.19/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-centered'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-centered' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-centered/angular' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/angular' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/ember' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/helpers/json2CSS' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/html' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/mithril' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/parameters' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/preact' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/rax' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/styles' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/svelte' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/vue' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/ember' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/html' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/mithril' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/preact' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/rax' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/svelte' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/vue' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-centered/angular.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/angular'>;
}
declare module '@storybook/addon-centered/dist/angular.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/angular'>;
}
declare module '@storybook/addon-centered/dist/ember.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/ember'>;
}
declare module '@storybook/addon-centered/dist/helpers/json2CSS.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/helpers/json2CSS'>;
}
declare module '@storybook/addon-centered/dist/html.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/html'>;
}
declare module '@storybook/addon-centered/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist'>;
}
declare module '@storybook/addon-centered/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist'>;
}
declare module '@storybook/addon-centered/dist/mithril.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/mithril'>;
}
declare module '@storybook/addon-centered/dist/parameters.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/parameters'>;
}
declare module '@storybook/addon-centered/dist/preact.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/preact'>;
}
declare module '@storybook/addon-centered/dist/rax.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/rax'>;
}
declare module '@storybook/addon-centered/dist/react.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/react'>;
}
declare module '@storybook/addon-centered/dist/styles.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/styles'>;
}
declare module '@storybook/addon-centered/dist/svelte.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/svelte'>;
}
declare module '@storybook/addon-centered/dist/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/typings.d'>;
}
declare module '@storybook/addon-centered/dist/vue.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/vue'>;
}
declare module '@storybook/addon-centered/ember.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/ember'>;
}
declare module '@storybook/addon-centered/html.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/html'>;
}
declare module '@storybook/addon-centered/mithril.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/mithril'>;
}
declare module '@storybook/addon-centered/preact.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/preact'>;
}
declare module '@storybook/addon-centered/rax.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/rax'>;
}
declare module '@storybook/addon-centered/react.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/react'>;
}
declare module '@storybook/addon-centered/svelte.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/svelte'>;
}
declare module '@storybook/addon-centered/vue.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/vue'>;
}
