// flow-typed signature: 43e93a7e3cc9ca813cb3a7a526ee7f3e
// flow-typed version: <<STUB>>/@storybook/addon-a11y_v^5.3.19/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-a11y'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-a11y' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-a11y/dist/components/A11YPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/ColorBlindness' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/Report/Elements' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/Report/HighlightToggle' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/Report' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/Report/Info' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/Report/Item' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/Report/Rules' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/Report/Tags' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/components/Tabs' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/redux-config' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/dist/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-a11y/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-a11y/dist/components/A11YPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/A11YPanel'>;
}
declare module '@storybook/addon-a11y/dist/components/ColorBlindness.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/ColorBlindness'>;
}
declare module '@storybook/addon-a11y/dist/components/Report/Elements.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Report/Elements'>;
}
declare module '@storybook/addon-a11y/dist/components/Report/HighlightToggle.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Report/HighlightToggle'>;
}
declare module '@storybook/addon-a11y/dist/components/Report/index' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Report'>;
}
declare module '@storybook/addon-a11y/dist/components/Report/index.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Report'>;
}
declare module '@storybook/addon-a11y/dist/components/Report/Info.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Report/Info'>;
}
declare module '@storybook/addon-a11y/dist/components/Report/Item.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Report/Item'>;
}
declare module '@storybook/addon-a11y/dist/components/Report/Rules.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Report/Rules'>;
}
declare module '@storybook/addon-a11y/dist/components/Report/Tags.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Report/Tags'>;
}
declare module '@storybook/addon-a11y/dist/components/Tabs.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/components/Tabs'>;
}
declare module '@storybook/addon-a11y/dist/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/constants'>;
}
declare module '@storybook/addon-a11y/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist'>;
}
declare module '@storybook/addon-a11y/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist'>;
}
declare module '@storybook/addon-a11y/dist/redux-config.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/redux-config'>;
}
declare module '@storybook/addon-a11y/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/register'>;
}
declare module '@storybook/addon-a11y/dist/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/dist/typings.d'>;
}
declare module '@storybook/addon-a11y/register.js' {
  declare module.exports: $Exports<'@storybook/addon-a11y/register'>;
}
