// flow-typed signature: ce8ddc4ed535e8a13c0a31968bab0ed0
// flow-typed version: <<STUB>>/@storybook/addon-backgrounds_v^5.3.19/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-backgrounds'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-backgrounds' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-backgrounds/dist/components/ColorIcon' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/containers/BackgroundSelector' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/containers/GridSelector' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-backgrounds/dist/components/ColorIcon.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/components/ColorIcon'>;
}
declare module '@storybook/addon-backgrounds/dist/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/constants'>;
}
declare module '@storybook/addon-backgrounds/dist/containers/BackgroundSelector.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/containers/BackgroundSelector'>;
}
declare module '@storybook/addon-backgrounds/dist/containers/GridSelector.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/containers/GridSelector'>;
}
declare module '@storybook/addon-backgrounds/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist'>;
}
declare module '@storybook/addon-backgrounds/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist'>;
}
declare module '@storybook/addon-backgrounds/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/register'>;
}
declare module '@storybook/addon-backgrounds/register.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/register'>;
}
