// flow-typed signature: 06a02624b88af094253b857b6862457f
// flow-typed version: <<STUB>>/@storybook/addon-docs_v^5.3.19/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-docs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-docs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-docs/angular' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/angular/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/blocks' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/common' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/common/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/Anchor' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/Description' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/DocsContainer' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/DocsContext' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/DocsPage' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/DocsStory' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/Heading' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/mdx' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/Meta' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/Preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/Primary' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/Props' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/shared' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/Source' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/Stories' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/Story' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/Subheading' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/Subtitle' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/Title' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/utils' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/blocks/Wrapper' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/angular/compodoc' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/angular/config' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/angular' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/angular/types' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/common/config' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/common/makePreset' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/common/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/ember/config' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/ember' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/ember/jsondoc' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/config' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/extractProps' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/lib/captions' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/createDefaultValue' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/createFromRawDefaultProp' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/generateArray' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/generateObject' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/lib/defaultValues' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/prettyIdentifier' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/lib/generateCode' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/lib' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/lib/inspection/acornParser' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/lib/inspection' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/lib/inspection/inspectValue' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/lib/inspection/types' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/lib/isHtmlTag' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/propTypes/createType' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/propTypes/generateFuncSignature' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/propTypes/handleProp' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/propTypes/rawDefaultPropResolvers' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/propTypes/sortProps' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/react/typeScript/handleProp' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/vue/config' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/vue/extractProps' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/vue/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/frameworks/web-components/config' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/docgen/createPropDef' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/docgen/extractDocgenProps' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/docgen/flow/createDefaultValue' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/docgen/flow/createPropDef' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/docgen/flow/createType' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/docgen' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/docgen/types' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/docgen/typeScript/createDefaultValue' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/docgen/typeScript/createPropDef' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/docgen/typeScript/createType' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/docgen/utils/defaultValue' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/docgen/utils/docgenInfo' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/docgen/utils' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/docgen/utils/string' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/jsdocParser' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/lib/utils' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/mdx/mdx-compiler-plugin' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/mdx/title-generators' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/public_api' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/shared' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/dist/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/ember' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/html' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/html/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/jest-transform-mdx' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/mdx-compiler-plugin' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/postinstall/presets' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/react/config' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/react/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/vue' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/vue/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/web-components' {
  declare module.exports: any;
}

declare module '@storybook/addon-docs/web-components/preset' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-docs/angular/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/angular'>;
}
declare module '@storybook/addon-docs/angular/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/angular'>;
}
declare module '@storybook/addon-docs/angular/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/angular/preset'>;
}
declare module '@storybook/addon-docs/blocks.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/blocks'>;
}
declare module '@storybook/addon-docs/common/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/common'>;
}
declare module '@storybook/addon-docs/common/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/common'>;
}
declare module '@storybook/addon-docs/common/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/common/preset'>;
}
declare module '@storybook/addon-docs/dist/blocks/Anchor.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/Anchor'>;
}
declare module '@storybook/addon-docs/dist/blocks/Description.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/Description'>;
}
declare module '@storybook/addon-docs/dist/blocks/DocsContainer.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/DocsContainer'>;
}
declare module '@storybook/addon-docs/dist/blocks/DocsContext.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/DocsContext'>;
}
declare module '@storybook/addon-docs/dist/blocks/DocsPage.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/DocsPage'>;
}
declare module '@storybook/addon-docs/dist/blocks/DocsStory.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/DocsStory'>;
}
declare module '@storybook/addon-docs/dist/blocks/Heading.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/Heading'>;
}
declare module '@storybook/addon-docs/dist/blocks/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks'>;
}
declare module '@storybook/addon-docs/dist/blocks/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks'>;
}
declare module '@storybook/addon-docs/dist/blocks/mdx.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/mdx'>;
}
declare module '@storybook/addon-docs/dist/blocks/Meta.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/Meta'>;
}
declare module '@storybook/addon-docs/dist/blocks/Preview.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/Preview'>;
}
declare module '@storybook/addon-docs/dist/blocks/Primary.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/Primary'>;
}
declare module '@storybook/addon-docs/dist/blocks/Props.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/Props'>;
}
declare module '@storybook/addon-docs/dist/blocks/shared.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/shared'>;
}
declare module '@storybook/addon-docs/dist/blocks/Source.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/Source'>;
}
declare module '@storybook/addon-docs/dist/blocks/Stories.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/Stories'>;
}
declare module '@storybook/addon-docs/dist/blocks/Story.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/Story'>;
}
declare module '@storybook/addon-docs/dist/blocks/Subheading.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/Subheading'>;
}
declare module '@storybook/addon-docs/dist/blocks/Subtitle.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/Subtitle'>;
}
declare module '@storybook/addon-docs/dist/blocks/Title.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/Title'>;
}
declare module '@storybook/addon-docs/dist/blocks/utils.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/utils'>;
}
declare module '@storybook/addon-docs/dist/blocks/Wrapper.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/blocks/Wrapper'>;
}
declare module '@storybook/addon-docs/dist/frameworks/angular/compodoc.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/angular/compodoc'>;
}
declare module '@storybook/addon-docs/dist/frameworks/angular/config.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/angular/config'>;
}
declare module '@storybook/addon-docs/dist/frameworks/angular/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/angular'>;
}
declare module '@storybook/addon-docs/dist/frameworks/angular/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/angular'>;
}
declare module '@storybook/addon-docs/dist/frameworks/angular/types.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/angular/types'>;
}
declare module '@storybook/addon-docs/dist/frameworks/common/config.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/common/config'>;
}
declare module '@storybook/addon-docs/dist/frameworks/common/makePreset.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/common/makePreset'>;
}
declare module '@storybook/addon-docs/dist/frameworks/common/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/common/preset'>;
}
declare module '@storybook/addon-docs/dist/frameworks/ember/config.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/ember/config'>;
}
declare module '@storybook/addon-docs/dist/frameworks/ember/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/ember'>;
}
declare module '@storybook/addon-docs/dist/frameworks/ember/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/ember'>;
}
declare module '@storybook/addon-docs/dist/frameworks/ember/jsondoc.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/ember/jsondoc'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/config.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/config'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/extractProps.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/extractProps'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/captions.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib/captions'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/createDefaultValue.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/createDefaultValue'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/createFromRawDefaultProp.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/createFromRawDefaultProp'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/generateArray.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/generateArray'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/generateObject.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/generateObject'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib/defaultValues'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib/defaultValues'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/prettyIdentifier.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib/defaultValues/prettyIdentifier'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/generateCode.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib/generateCode'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/inspection/acornParser.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib/inspection/acornParser'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/inspection/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib/inspection'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/inspection/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib/inspection'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/inspection/inspectValue.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib/inspection/inspectValue'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/inspection/types.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib/inspection/types'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/lib/isHtmlTag.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/lib/isHtmlTag'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/propTypes/createType.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/propTypes/createType'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/propTypes/generateFuncSignature.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/propTypes/generateFuncSignature'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/propTypes/handleProp.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/propTypes/handleProp'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/propTypes/rawDefaultPropResolvers.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/propTypes/rawDefaultPropResolvers'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/propTypes/sortProps.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/propTypes/sortProps'>;
}
declare module '@storybook/addon-docs/dist/frameworks/react/typeScript/handleProp.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/react/typeScript/handleProp'>;
}
declare module '@storybook/addon-docs/dist/frameworks/vue/config.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/vue/config'>;
}
declare module '@storybook/addon-docs/dist/frameworks/vue/extractProps.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/vue/extractProps'>;
}
declare module '@storybook/addon-docs/dist/frameworks/vue/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/vue/preset'>;
}
declare module '@storybook/addon-docs/dist/frameworks/web-components/config.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/frameworks/web-components/config'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/createPropDef.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen/createPropDef'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/extractDocgenProps.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen/extractDocgenProps'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/flow/createDefaultValue.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen/flow/createDefaultValue'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/flow/createPropDef.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen/flow/createPropDef'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/flow/createType.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen/flow/createType'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/types.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen/types'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/typeScript/createDefaultValue.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen/typeScript/createDefaultValue'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/typeScript/createPropDef.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen/typeScript/createPropDef'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/typeScript/createType.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen/typeScript/createType'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/utils/defaultValue.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen/utils/defaultValue'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/utils/docgenInfo.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen/utils/docgenInfo'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/utils/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen/utils'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/utils/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen/utils'>;
}
declare module '@storybook/addon-docs/dist/lib/docgen/utils/string.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/docgen/utils/string'>;
}
declare module '@storybook/addon-docs/dist/lib/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib'>;
}
declare module '@storybook/addon-docs/dist/lib/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib'>;
}
declare module '@storybook/addon-docs/dist/lib/jsdocParser.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/jsdocParser'>;
}
declare module '@storybook/addon-docs/dist/lib/utils.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/lib/utils'>;
}
declare module '@storybook/addon-docs/dist/mdx/mdx-compiler-plugin.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/mdx/mdx-compiler-plugin'>;
}
declare module '@storybook/addon-docs/dist/mdx/title-generators.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/mdx/title-generators'>;
}
declare module '@storybook/addon-docs/dist/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/preset'>;
}
declare module '@storybook/addon-docs/dist/public_api.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/public_api'>;
}
declare module '@storybook/addon-docs/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/register'>;
}
declare module '@storybook/addon-docs/dist/shared.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/shared'>;
}
declare module '@storybook/addon-docs/dist/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/dist/typings.d'>;
}
declare module '@storybook/addon-docs/ember/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/ember'>;
}
declare module '@storybook/addon-docs/ember/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/ember'>;
}
declare module '@storybook/addon-docs/html/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/html'>;
}
declare module '@storybook/addon-docs/html/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/html'>;
}
declare module '@storybook/addon-docs/html/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/html/preset'>;
}
declare module '@storybook/addon-docs/jest-transform-mdx.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/jest-transform-mdx'>;
}
declare module '@storybook/addon-docs/mdx-compiler-plugin.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/mdx-compiler-plugin'>;
}
declare module '@storybook/addon-docs/postinstall/presets.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/postinstall/presets'>;
}
declare module '@storybook/addon-docs/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/preset'>;
}
declare module '@storybook/addon-docs/react/config.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/react/config'>;
}
declare module '@storybook/addon-docs/react/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/react'>;
}
declare module '@storybook/addon-docs/react/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/react'>;
}
declare module '@storybook/addon-docs/react/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/react/preset'>;
}
declare module '@storybook/addon-docs/register.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/register'>;
}
declare module '@storybook/addon-docs/vue/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/vue'>;
}
declare module '@storybook/addon-docs/vue/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/vue'>;
}
declare module '@storybook/addon-docs/vue/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/vue/preset'>;
}
declare module '@storybook/addon-docs/web-components/index' {
  declare module.exports: $Exports<'@storybook/addon-docs/web-components'>;
}
declare module '@storybook/addon-docs/web-components/index.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/web-components'>;
}
declare module '@storybook/addon-docs/web-components/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-docs/web-components/preset'>;
}
