// flow-typed signature: 07c4e1d13017d0a5af8c6a5567962c45
// flow-typed version: <<STUB>>/@storybook/addon-storysource_v^5.3.19/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-storysource'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-storysource' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-storysource/dist/events' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/StoryPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-storysource/dist/events.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/events'>;
}
declare module '@storybook/addon-storysource/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist'>;
}
declare module '@storybook/addon-storysource/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist'>;
}
declare module '@storybook/addon-storysource/dist/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/manager'>;
}
declare module '@storybook/addon-storysource/dist/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/preset'>;
}
declare module '@storybook/addon-storysource/dist/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/preview'>;
}
declare module '@storybook/addon-storysource/dist/StoryPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/StoryPanel'>;
}
declare module '@storybook/addon-storysource/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/loader'>;
}
declare module '@storybook/addon-storysource/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/preset'>;
}
declare module '@storybook/addon-storysource/register.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/register'>;
}
