// flow-typed signature: 7b717c9dfa17ed6df93d8652d041278a
// flow-typed version: <<STUB>>/@storybook/vue_v^5.3.19/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/vue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/vue/bin/build' {
  declare module.exports: any;
}

declare module '@storybook/vue/bin' {
  declare module.exports: any;
}

declare module '@storybook/vue/dist/client' {
  declare module.exports: any;
}

declare module '@storybook/vue/dist/client/preview/globals' {
  declare module.exports: any;
}

declare module '@storybook/vue/dist/client/preview' {
  declare module.exports: any;
}

declare module '@storybook/vue/dist/client/preview/render' {
  declare module.exports: any;
}

declare module '@storybook/vue/dist/client/preview/types' {
  declare module.exports: any;
}

declare module '@storybook/vue/dist/client/preview/util' {
  declare module.exports: any;
}

declare module '@storybook/vue/dist/server/build' {
  declare module.exports: any;
}

declare module '@storybook/vue/dist/server/framework-preset-vue' {
  declare module.exports: any;
}

declare module '@storybook/vue/dist/server' {
  declare module.exports: any;
}

declare module '@storybook/vue/dist/server/options' {
  declare module.exports: any;
}

declare module '@storybook/vue/dist/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/vue/standalone' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/vue/bin/build.js' {
  declare module.exports: $Exports<'@storybook/vue/bin/build'>;
}
declare module '@storybook/vue/bin/index' {
  declare module.exports: $Exports<'@storybook/vue/bin'>;
}
declare module '@storybook/vue/bin/index.js' {
  declare module.exports: $Exports<'@storybook/vue/bin'>;
}
declare module '@storybook/vue/dist/client/index' {
  declare module.exports: $Exports<'@storybook/vue/dist/client'>;
}
declare module '@storybook/vue/dist/client/index.js' {
  declare module.exports: $Exports<'@storybook/vue/dist/client'>;
}
declare module '@storybook/vue/dist/client/preview/globals.js' {
  declare module.exports: $Exports<'@storybook/vue/dist/client/preview/globals'>;
}
declare module '@storybook/vue/dist/client/preview/index' {
  declare module.exports: $Exports<'@storybook/vue/dist/client/preview'>;
}
declare module '@storybook/vue/dist/client/preview/index.js' {
  declare module.exports: $Exports<'@storybook/vue/dist/client/preview'>;
}
declare module '@storybook/vue/dist/client/preview/render.js' {
  declare module.exports: $Exports<'@storybook/vue/dist/client/preview/render'>;
}
declare module '@storybook/vue/dist/client/preview/types.js' {
  declare module.exports: $Exports<'@storybook/vue/dist/client/preview/types'>;
}
declare module '@storybook/vue/dist/client/preview/util.js' {
  declare module.exports: $Exports<'@storybook/vue/dist/client/preview/util'>;
}
declare module '@storybook/vue/dist/server/build.js' {
  declare module.exports: $Exports<'@storybook/vue/dist/server/build'>;
}
declare module '@storybook/vue/dist/server/framework-preset-vue.js' {
  declare module.exports: $Exports<'@storybook/vue/dist/server/framework-preset-vue'>;
}
declare module '@storybook/vue/dist/server/index' {
  declare module.exports: $Exports<'@storybook/vue/dist/server'>;
}
declare module '@storybook/vue/dist/server/index.js' {
  declare module.exports: $Exports<'@storybook/vue/dist/server'>;
}
declare module '@storybook/vue/dist/server/options.js' {
  declare module.exports: $Exports<'@storybook/vue/dist/server/options'>;
}
declare module '@storybook/vue/dist/typings.d.js' {
  declare module.exports: $Exports<'@storybook/vue/dist/typings.d'>;
}
declare module '@storybook/vue/standalone.js' {
  declare module.exports: $Exports<'@storybook/vue/standalone'>;
}
