name: Deploy

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'App stage to deploy (development|staging|production).'
        required: true
        default: 'development'

jobs:
  deploy:
    name: Deploy Site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Notify Deploy
        if: "github.event.inputs.stage == 'staging' || github.event.inputs.stage == 'production'"
        uses: rtCamp/action-slack-notify@v2.0.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 'core'
          SLACK_USERNAME: 'CrisisCleanup Bot'
          SLACK_ICON: ${{ secrets.SLACK_ICON }}
          SLACK_COLOR: '#fece09'
          SLACK_TITLE: 'New Release'
          SLACK_MESSAGE: "Heads up, I'm currently releasing to ${{ github.event.inputs.stage }}! You can watch my progress at the url above."

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup Common Env
        run: |
          echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          echo "GIT_REF=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)" >> $GITHUB_ENV
          echo "BUILD_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          echo "IMAGE=${{ steps.login-ecr.outputs.registry }}/crisiscleanup-web" >> $GITHUB_ENV

      - name: Setup Development Env
        if: github.event.inputs.stage == 'development'
        run: |
          echo "VUE_APP_API_BASE_URL=https://api.dev.crisiscleanup.io" >> $GITHUB_ENV
          echo "VUE_APP_BASE_URL=https://app.dev.crisiscleanup.io" >> $GITHUB_ENV
          echo "VUE_APP_WS_URL=wss://socket.dev.crisiscleanup.io" >> $GITHUB_ENV
          echo "VUE_APP_AWS_CCP_URL=https://ccudev.awsapps.com/connect/ccp-v2/" >> $GITHUB_ENV
          echo "VUE_APP_CCP_INSTANCE=87fbcad4-9f58-4153-84e8-d5b7202693e8" >> $GITHUB_ENV
          echo "VUE_APP_STAGE=development" >> $GITHUB_ENV
          echo "VUE_APP_PORTAL_KEY=crisiscleanup_demo" >> $GITHUB_ENV
          echo "NODE_ENV=development" >> $GITHUB_ENV

      - name: Setup Staging Env
        if: github.event.inputs.stage == 'staging'
        run: |
          echo "VUE_APP_API_BASE_URL=https://api.staging.crisiscleanup.io" >> $GITHUB_ENV
          echo "VUE_APP_BASE_URL=https://app.staging.crisiscleanup.io" >> $GITHUB_ENV
          echo "VUE_APP_WS_URL=wss://socket.staging.crisiscleanup.io" >> $GITHUB_ENV
          echo "VUE_APP_STAGE=staging" >> $GITHUB_ENV
          echo "VUE_APP_AWS_CCP_URL=https://ccustaging.awsapps.com/connect/ccp-v2/" >> $GITHUB_ENV
          echo "VUE_APP_PORTAL_KEY=crisiscleanup_staging" >> $GITHUB_ENV
          echo "VUE_APP_CCP_INSTANCE=414df788-cd99-4580-ad07-f8af22246ce5" >> $GITHUB_ENV
          echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Setup Production Env
        if: github.event.inputs.stage == 'production'
        run: |
          echo "VUE_APP_API_BASE_URL=https://api.crisiscleanup.org" >> $GITHUB_ENV
          echo "VUE_APP_BASE_URL=https://crisiscleanup.org" >> $GITHUB_ENV
          echo "VUE_APP_WS_URL=wss://socket.crisiscleanup.org" >> $GITHUB_ENV
          echo "VUE_APP_STAGE=production" >> $GITHUB_ENV
          echo "VUE_APP_AWS_CCP_URL=https://cculive.awsapps.com/connect/ccp-v2/" >> $GITHUB_ENV
          echo "VUE_APP_CCP_INSTANCE=cd54a377-8223-4c43-8524-a21d2837b7c5" >> $GITHUB_ENV
          echo "VUE_APP_PORTAL_KEY=crisiscleanup_us" >> $GITHUB_ENV
          echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Create Sentry Release
        uses: tclindner/sentry-releases-action@v1.2.0
        continue-on-error: true
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_PROPERTIES: sentry.properties
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        with:
          tagName: ${{ github.ref }}
          environment: ${{ github.event.inputs.stage }}
          releaseNamePrefix: crisiscleanup-3-web@

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            VUE_APP_API_BASE_URL=${{ env.VUE_APP_API_BASE_URL }}
            VUE_APP_BASE_URL=${{ env.VUE_APP_BASE_URL }}
            VUE_APP_WS_URL=${{ env.VUE_APP_WS_URL }}
            VUE_APP_STAGE=${{ env.VUE_APP_STAGE }}
            VUE_APP_AWS_CCP_URL=${{ env.VUE_APP_AWS_CCP_URL }}
            VUE_APP_CCP_INSTANCE=${{ env.VUE_APP_CCP_INSTANCE }}
            VUE_APP_PORTAL_KEY=${{ env.VUE_APP_PORTAL_KEY }}
            NODE_ENV=${{ env.NODE_ENV }}
            VUE_APP_WHAT_3_WORDS_API_KEY=${{ secrets.VUE_APP_WHAT_3_WORDS_API_KEY }}
            VUE_APP_GOOGLE_MAPS_API_KEY=${{ secrets.VUE_APP_GOOGLE_MAPS_API_KEY }}
            VUE_APP_PITNEYBOWES_API_KEY=${{ secrets.VUE_APP_PITNEYBOWES_API_KEY }}
            VUE_APP_PITNEYBOWES_BASIC_AUTH_TOKEN=${{ secrets.VUE_APP_PITNEYBOWES_BASIC_AUTH_TOKEN }}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_PROPERTIES="sentry.properties"
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.event.inputs.stage }}
            ${{ env.IMAGE }}:${{ env.GIT_REF }}
          push: true

      - name: Invoke Web Rollout
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Rollout Deployments
          token: ${{ secrets.GHCR_PAT }}
          repo: CrisisCleanup/crisiscleanup-3-api
          ref: master
          inputs: '{ "stage": "${{ github.event.inputs.stage }}", "targets": "crisiscleanup-web-frontend" }'

      - name: Post Notify Deploy
        if: "github.event.inputs.stage == 'staging' || github.event.inputs.stage == 'production'"
        uses: rtCamp/action-slack-notify@v2.0.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 'core'
          SLACK_USERNAME: 'CrisisCleanup Bot'
          SLACK_ICON: ${{ secrets.SLACK_ICON }}
          SLACK_COLOR: '#fece09'
          SLACK_TITLE: 'Live Release'
          SLACK_MESSAGE: ':rocket: ${{ github.event.inputs.stage }} is live! Check it out at: https://crisiscleanup.org'

      - name: Notify Failed
        if: "(github.event.inputs.stage == 'staging' || github.event.inputs.stage == 'production') && failure()"
        uses: rtCamp/action-slack-notify@v2.0.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 'core'
          SLACK_USERNAME: 'CrisisCleanup Bot'
          SLACK_ICON: ${{ secrets.SLACK_ICON }}
          SLACK_COLOR: '#D94F37'
          SLACK_TITLE: 'Deploy Failed!'
          SLACK_MESSAGE: 'Failed to deploy... someone broke something! :frowning:'
